### ISSUE TITLE
hot-reloading hooks.json file when it changes

### ISSUE THREAD

**Issue by adnanh** [adnanh/webhook#1]

**Comment by edrex** [comment]
First, thanks for making this utility. I appreciate the general-purpose interface and simple implementation.

The `-hotreload` flag isn't working on the two Linux systems I tried (Ubuntu 14.04.1 and Arch). It works fine on OSX, so I think there is a problem with the inotify backend of fsnotify. It doesn't seem like there should be any external dependencies since it is a kernel interface.

Output on starting `webhook` and then modifying the hooks file:

```
% webhook -hotreload -hooks ~/.webhooks.json -verbose
[webhook] 2015/03/25 20:53:20 version 2.3.0 starting
[webhook] 2015/03/25 20:53:20 attempting to load hooks from /home/eric/.webhooks.json
[webhook] 2015/03/25 20:53:20 loaded 2 hook(s) from file
. . .
[webhook] 2015/03/25 20:53:20 setting up file watcher for /home/eric/.webhooks.json
[webhook] 2015/03/25 20:53:20 starting insecure (http) webhook on :9000
```
(`hooks file modified` never gets triggered)

**Comment by edrex** [comment]
I wrote a test program to experiment with this. Modifying the file with `echo bar >> foo` etc generates a WRITE event, but saving a watched file with `vim` (on Linux only) generates the following events:
```
2015/03/25 23:00:40 event: "foo.txt": RENAME
2015/03/25 23:00:40 event: "foo.txt": CHMOD
2015/03/25 23:00:40 event: "foo.txt": REMOVE
```
On subsequent writes, no more events are triggered on the file. 

I'm going to follow up with this on the fs-events issue queue, it seems like it's upstream.

**Comment by edrex** [comment]
this looks like the upstream issue for what I'm complaining about: https://github.com/go-fsnotify/fsnotify/issues/22

**Comment by adnanh** [comment]
Yeah, the fsnotify library is indeed buggy at the moment. They are working on getting a full support and then probably adding it to the core Go packages (os/fsnotify), once they do that, I'll make sure to move to the official package, until then, there isn't much I can do :-(

However, using `nano` or `pico` editor on centos, hotreload worked fine for me, I didn't try ubuntu or arch though...

**Comment by kevinlebrun** [comment]
The feature does not work on OS X Yosemite while editing with Vim. 

Why not simply poll for file change then reload? It would be great if you can setup a USR signal to reload the configuration file.

**Comment by adnanh** [comment]
I agree with you on adding the USR signal, it can certainly come in handy!

I'll reopen this issue until I get it done. :+1:

**Comment by kevinlebrun** [comment]
Great! I'll be happy to test it.

**Comment by edrex** [comment]
Agreed that adding config reloading on USR signal would be nice. For me, on all the platforms I care about, I can use [systemd.path](http://www.freedesktop.org/software/systemd/man/systemd.path.html) to watch the config file and send the signal.

**Comment by adnanh** [comment]
I've tested USR1 signal on raspbian and it worked fine, so it should work on any other Linux distribution.

Have in mind that USR1 signal might not be available on all OS-es (for example on Windows).

**Comment by kevinlebrun** [comment]
I've just tested on OS X without success. With some tinkering, I find that signal codes are different and `syscall.SIGUSR1` doesn't match `syscall.Signal(0xa)` on OS X. I've just pushed a quick fix.
