### ISSUE TITLE
Mention the Debian package in the "Getting started" section of README.md 

### ISSUE THREAD

**Issue by freeekanayaka** [adnanh/webhook#103]
Hello,

I've packaged webhook for Debian:

https://packages.debian.org/sid/webhook

It'd be nice to mention this way of getting webhook ("apt install webhook") in the README.

If you prefer not to, please feel free to close the issue.

PS: FYI, I had to apply a couple of patches to the upstream code, see:

https://anonscm.debian.org/cgit/pkg-go/packages/webhook.git/tree/debian/patches

(mainly package paths and interfaces that have changed). Feel free to merge
whatever makes sense to you.

Take care and thansk

**Comment by adnanh** [comment]
Awesome, thanks for the contribution :-)

**Comment by freeekanayaka** [comment]
Woot, thank you for the code and the quick feedback! See you.

**Comment by adnanh** [comment]
👍
