### ISSUE TITLE
Split the `include-command-output-in-response` into two config options

### ISSUE THREAD

**Issue by orf** [adnanh/webhook#109]
Currently the `include-command-output-in-response` config option does this:

`... boolean whether webhook should wait for the command to finish and return the raw output as a response to the hook initiator. If the command fails to execute or encounters any errors while executing the response will result in 500 Internal Server Error HTTP status code, otherwise the 200 OK status code will be returned.`

It would be great to have two separate config options for this, one to return the output in the response and one to just wait until the command is executed. I.E:

 - `include-command-output-in-response` - Does what it says on the tin and sticks with the current functionality
 - `wait-for-command-completion` - If the command fails to execute or encounters any errors while executing the response will result in 500 Internal Server Error HTTP status code, otherwise the 200 OK status code will be returned. **does not return the command output in the response**

**Comment by adnanh** [comment]
You could also redirect the command stdout and stderr to /dev/null.to get the same behavior :-)
