### ISSUE TITLE
Can't build because of changes in ecbcf111

### ISSUE THREAD

**Issue by wjessop** [adnanh/webhook#110]
It looks like the changes introduced in revision ecbcf111 (issue #106) caused building to fail:

```
$ go test
# github.com/wjessop/webhook
./webhook.go:201: cannot range over errors (type error)
./webhook.go:261: cannot assign error to errors (type []error) in multiple assignment
./webhook.go:269: cannot assign error to errors (type []error) in multiple assignment
FAIL	github.com/wjessop/webhook [build failed]
```

It also looks like the tests don't pass, they still assume ParseJSONParameters returns a single error:

```go
err := h.ParseJSONParameters(tt.headers, tt.query, tt.payload)
```

**Comment by adnanh** [comment]
Your fork is 16 commits behind my master, merge the changes or change the reference to the hook import to use your personal fork and not adnanh/webhook :-) I highly recommend merging.
