### ISSUE TITLE
Optional query parameters

### ISSUE THREAD

**Issue by kachkaev** [adnanh/webhook#112]
It'd be great if it was possible to hit both `my-hook?a=1&b=2` and `my-hook?a=1` if there is something like this in the config:

```
    "pass-environment-to-command":
    [
      {
        "source": "url",
        "name": "a",
        "envname": "A"
      },
      {
        "source": "url",
        "name": "b",
        "envname": "B",
        "default-value": "42"
      }
    ]
```

At the moment the hook is only execute when `b` is mentioned: `my-hook?a=1&b=`.

This feature will make it easier to upgrade hooks while maintaining backwards-compatibility. If one wants to add `b` now, they need to update all CI scripts that trigger the given hook.

**Comment by adnanh** [comment]
What version of webhook are you using? The 2.6.0 version fixes described behavior (there was a bug in the code which stopped hook execution if it couldn't extract an argument). With 2.6.0+, in your example the environment variable B would not be set, so your script can determine that and set the default value.

Cheers.

**Comment by kachkaev** [comment]
It is 2.5.0, as it appears in `docker-compose.yml`. Glad to know that this is no longer the issue in 2.6.0. Can't check myself ATM, but I trust your words :–)

**Comment by kachkaev** [comment]
Does there exist something like `"default-value"` for undefined query params  by a chance?
