### ISSUE TITLE
webhook wont build (error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301)

### ISSUE THREAD

**Issue by adnanh** [adnanh/webhook#114]
webhook build fails with:
```
# cd .; git clone https://gopkg.in/fsnotify.v1 /go/src/gopkg.in/fsnotify.v1
Cloning into '/go/src/gopkg.in/fsnotify.v1'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/fsnotify.v1: exit status 128
```

## Reason
Latest version of git does not follow 301 redirects (https://github.com/niemeyer/gopkg/issues/50)

## Workaround
Here is a workaround until gopkg.in fixes the issue.
```
git config --global http.https://gopkg.in.followRedirects true
```

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by adnanh** [comment]
Awesome! Thanks for the heads up!
