### ISSUE TITLE
Recommendation: Drop the helpers package

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#12]
I think the ``helpers`` package adds unnecessary segmentation into the codebase.  Each function in ``helpers`` is only used by a single package:

  - ``ValuesToMap`` is used by ``main``
  - ``CheckPayloadSignature`` and ``ExtractParameter`` are used by ``hook``

I'd recommend moving those functions and dropping the ``helpers`` package.  What do you think?

**Comment by adnanh** [comment]
Sounds good, could you do the refactoring and create a PR?
