### ISSUE TITLE
Multiple hooks

### ISSUE THREAD

**Issue by prasenforu** [adnanh/webhook#123]
Thanks for this cool project :)

I have multiple hooks with different file names & ids.

how can I add multiple hooks files from a directory ?

**Comment by adnanh** [comment]
Use `-hooks file1.json -hooks file2.json -hooks file3.json` when starting webhook

**Comment by prasenforu** [comment]
Thanks.
 For two or three files its OK.
But more than 5 not ok

Looks like -hook_dir features nèed to add as a enhancement.

**Comment by adnanh** [comment]
Adding hooks dir feature adds unnecessary complexity.
Instead try modelling your problem differently. Leverage multiple webhook instances, ability to define multiple hooks inside one file, and the ability to use multiple hooks files within one webhook instance.

**Comment by prasenforu** [comment]
Thanks .  Can you please  suggest how?

I have below two hooks files.

file1.json 
[
  {
    "id": "ose-webhook-dn",
    "execute-command": "/etc/webhook/osedn.sh",
    "command-working-directory": "/etc/webhook"
  }
]

----------
file2.json
[

  {
    "id": "ose-webhook-up",
    "execute-command": "/etc/webhook/oseup.sh",
    "command-working-directory": "/etc/webhook"
  }
]

**Comment by adnanh** [comment]
```json
[
	{
		"id": "ose-webhook-dn",
		"execute-command": "/etc/webhook/osedn.sh",
		"command-working-directory": "/etc/webhook"
	},
	{
		"id": "ose-webhook-up",
		"execute-command": "/etc/webhook/oseup.sh",
		"command-working-directory": "/etc/webhook"
	}
]
```

**Comment by prasenforu** [comment]
Hmmm ...

I tried same 😀

Looks like I was missing one coma (,) in between.

Anyways thanks for prompt response .

Thanks once more time for this nice and cool project.

👍

**Comment by adnanh** [comment]
You're welcome :-) Enjoy!
