### ISSUE TITLE
Question: TravisCI build notification

### ISSUE THREAD

**Issue by vladgh** [adnanh/webhook#128]
Is there a possibility of using this webhook with a build notification from TravisCI?

The workflow is documented their [website](https://docs.travis-ci.com/user/notifications#Verifying-Webhook-requests):

> The POST request comes with the custom HTTP header `Signature`. Using the published SSL public key, you can verify the signature of the payload.
> 
> Pick up the `payload` data from the HTTP request’s body.
> Obtain the `Signature` header value, and base64-decode it.
> Obtain the public key corresponding to the private key that signed the payload. This is available at the `/config` endpoint’s `config.notifications.webhook.public_key` on the relevant API server. (e.g., https://api.travis-ci.org/config)
> Verify the signature using the public key and SHA1 digest.

**Comment by adnanh** [comment]
Yes, but without the verification part.

**Comment by adnanh** [comment]
Alternatively, you can provide a token in the url to limit the scope of blind hits.

**Comment by vladgh** [comment]
Thank you so much for your very fast response. This is the way I have it  currently set up. I was just wondering if there is a better way.

**Comment by adnanh** [comment]
:+1:
