### ISSUE TITLE
Unable to run curl commands in the shell scripts when started as a service

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [adnanh/webhook#129]
Firstly, everything works properly if I run webhook from the commandline.
I can't seem to make it work as a service though. A workaround we're currently using is tmux.

Whenever I start webhook as a service, I can't seem to run any curl commands. I see the following in the terminal.

![image](https://cloud.githubusercontent.com/assets/26975170/25687759/0097ed4c-302e-11e7-878a-224fcd5648ff.png)

For every hook, multiple processes are created and then after a while they are killed (i guess).

But I'm unable to actually send POST back to Github to update my PR status.

**Comment by moorereason** [comment]
I use webhook as a service, and it works fine.  I think this is likely a system problem, not a webhook problem.  Are you using selinux?

**Comment by adnanh** [comment]
Could it be an issue with how [systemd handles execution](https://www.freedesktop.org/software/systemd/man/systemd.exec.html)

**Comment by sridhar-vadlamani-ck** [comment]
@moorereason I'm on CentOS on AWS. Any ideas for debugging/fixing this? Works perfectly if I just start webhook from the terminal. All issues are when I run it as a service. I used and modified the `webhook.init` script I found in `webhook-contrib`.

**Comment by sridhar-vadlamani-ck** [comment]
It was an issue with the company Proxy. Took me a while to figure it out. As @adnanh mentioned, `systemd` was unsetting all environment variables. I'd totally forgotten about the `HTTP_PROXY` env variable.

**Comment by adnanh** [comment]
Awesome! :+1:
