### ISSUE TITLE
How to specify pass-environment-to-command

### ISSUE THREAD

**Issue by emmjaykay** [adnanh/webhook#131]
It's not clear to me how to specify an environment variables. I can't really glean how to from the source code and the tests don't seem to have any coverage. If I specify this I can get a variable called PATH but it's blank.

     "pass-environment-to-command": [
          {
            "source": "string",
            "args": "/usr/bin/:/usr/local/bin",
            "envname": "PATH"
          }
        ]

**Comment by adnanh** [comment]
Substitute `args` with `name` and it will work. Check out https://github.com/adnanh/webhook/wiki/Hook-Definition
