### ISSUE TITLE
Can I run Python Scripts?

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [adnanh/webhook#132]
Does Webhook support the ability to run Python scripts? In the examples, it's all `bash` scripts.
Or even ruby?

Edit : Or do I have to run the python script from the bash script?

**Comment by vsivsi** [comment]
You should be able to run a python script by doing two things:

1. Ensure that the script has its execute bits set, e.g. `chmod +x myscript.py`
2. Add a "shebang" line at the top of the python file.  See here for more info:
http://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take#19305076

**Comment by jiangmitiao** [comment]
Whether it is a shell file or a python file, they all need to increase the permissions to execute

**Comment by adnanh** [comment]
Everything they said, or run it like `python script.py`, `ruby script.rb`

**Comment by adnanh** [comment]
Hint: `script.py` or `script.rb` is an argument to the appropriate command, and it needs to be passed via `pass-arguments-to-command` hook property.

**Comment by sridhar-vadlamani-ck** [comment]
So the command would be `python` and the argument would be `script.py` ? How do I pass parameters to this script?

**Comment by adnanh** [comment]
Any argument after `python script.py` would be passed to the script I believe, no?

**Comment by sridhar-vadlamani-ck** [comment]
🤷‍♂️ I'll test it and let you know.

**Comment by sridhar-vadlamani-ck** [comment]
So arguments work just like `bash`. Given the `shebang` for python, using `sys.argv` to get the arguments gives you the file as the first parameter followed by everything specified in `hooks.json`.
