### ISSUE TITLE
Windows, best strategy for daemonization...

### ISSUE THREAD

**Issue by sullyme** [adnanh/webhook#133]
How can I daemonize webhook?

`/path/to/webhook -hooks hooks.json -verbose`

I need to restart Windows and I need webhook ON... **Best strategy?**

**Comment by adnanh** [comment]
Could something like this help? https://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/

**Comment by sullyme** [comment]
Yes, but anything else? Like forever for linux...

**Comment by adnanh** [comment]
I am afraid I can't help you there, I don't use Windows at all :(

**Comment by msenturk** [comment]
@sullyme try https://nssm.cc
