### ISSUE TITLE
Send rich messages like html image in webhook response

### ISSUE THREAD

**Issue by jonatasrenan** [adnanh/webhook#136]
Hi,

I could send a rich-html through the response-message like a image with css styles ? 

Regards.

**Comment by adnanh** [comment]
If you set the proper headers for the hook, theoretically you could send HTML.

**Comment by jonatasrenan** [comment]
I tried "Content-Type: text/html; charset=utf-8" but it didn't works.

**Comment by adnanh** [comment]
Could you paste your hook definition you tried?

**Comment by adnanh** [comment]
Anyway, for further reference, yes, it's possible to return HTML, here's an example hook. One would obviously replace echo command with their own command that returns dynamically generated HTML:
```json
[
{
    "id": "example",
    "include-command-output-in-response": true,
    "response-headers": [
      {
        "name": "Content-Type",
        "value": "text/html"
      }
    ],
    "execute-command": "echo",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "<html><title>Test</title><body><h1 style='font-weight: bold; color: red;'>Hello from the other side.</h1><p style='padding: 10px; background-color: #eee; border-radius: 10px;'>This is a paragraph</p></body></html>"
      }
    ]
  }
]
```

---

The output looks something like this:

![image](https://cloud.githubusercontent.com/assets/82367/26506578/7426c748-424d-11e7-9086-f2cc6d4dcdab.png)

**Comment by actuariat** [comment]
Thank you, this is great, but I want to add this to another, already existing command, say:
    "execute-command": "/var/webhook/email.sh"

**Comment by actuariat** [comment]
Got it! just add headers:

    "response-headers": [
      {
        "name": "Content-Type",
        "value": "text/html;charset=utf-8"
      }
    ]

This will fix diacritics as well.

**Comment by actuariat** [comment]
Well, how about posting an image. Where should I save the image on the server? 
located in the same folder as the current page
So where is standard location
