### ISSUE TITLE
Can I have more than one id?

### ISSUE THREAD

**Issue by gouvmarc** [adnanh/webhook#137]
Hi Friends, I need a help with webhook

Can I have more than one id?

If I can, how do I do?

[
  {
    "id": "redeploy-webhook",
    "execute-command": "/var/scripts/redeploy.sh",
    "command-working-directory": "/var/webhook",
    "response-message": "Webhook UP"

    "id": "test1",
    "execute-command": "/var/scripts/test1.sh",
    "command-working-directory": "/var/webhook",
    "response-message": "Webhook UP1"
  }

]

Or
------

[
  {
    "id": "redeploy-webhook",
    "execute-command": "/var/scripts/redeploy.sh",
    "command-working-directory": "/var/webhook",
    "response-message": "Webhook UP"
 }
 {
    "id": "test1",
    "execute-command": "/var/scripts/test1.sh",
    "command-working-directory": "/var/webhook",
    "response-message": "Webhook UP1"
  }

]
The two way did not work

**Comment by adnanh** [comment]
You're missing a comma. If you run your second proposal through the JSON linter you will see it's not a valid JSON.

```
[
    {
        "id": "redeploy-webhook",
        "execute-command": "/var/scripts/redeploy.sh",
        "command-working-directory": "/var/webhook",
        "response-message": "Webhook UP"
    },
    {
        "id": "test1",
        "execute-command": "/var/scripts/test1.sh",
        "command-working-directory": "/var/webhook",
        "response-message": "Webhook UP1"
    }
]
```
