### ISSUE TITLE
Swagger Configuration

### ISSUE THREAD

**Issue by markrey** [adnanh/webhook#145]
It would be great if a user can define and generate Swagger JSON configuration.
It can be dynamically created or statically defined.

**Comment by adnanh** [comment]
That's a great task for a community contributed tool, however webhook should not deal with it. :-)

If you create a such tool, I'd be more than glad to merge it into [webhook-contrib](https://github.com/adnanh/webhook-contrib) repository, and reference it in the main README file in this repository.

Thank you for suggestions!
