### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by markrey** [adnanh/webhook#146]
Any way I can configure JWT Authentication for created API endpoint?

- I created a small hook for "ethernet down" and "ethernet up"
- I want to implement JWT based auth to configure the same so it is not available to everyone. 

(JWT is generated by some other auth provider and I will be just using it)

**Comment by adnanh** [comment]
Currently your best shot is to create the validation inside your script, and use webhook to pass the token from the request to the script.

Best solution would be to implement the JWT verification as a trigger rule. If you want to implement the trigger rule that verifies the JWT, I'd be more than glad to accept a PR for it!
