### ISSUE TITLE
git pull doesn't work

### ISSUE THREAD

**Issue by hobakill** [adnanh/webhook#153]
I have a very very basic script that will lead to something more complex. However I need to figure out what's going on first before continuing. 

```
#!/usr/bin/env bash

cd /home/ubuntu/some/repo/here
git pull origin master
```

works just fine if i run it from the command line:

```
server % ./git.sh                                                                                                                                
From github.com:company/repo
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

If I try running this script in my webhook I get this:

```
[webhook] 2017/07/17 19:22:17 2017-07-17T19:22:17Z | 200 | 	 156.653µs | server.aws.comapany.net:9000 | GET /hooks/git-test
[webhook] 2017/07/17 19:22:17 executing /home/ubuntu/hooks/git.sh (/home/ubuntu/hooks/git.sh) with arguments ["/home/ubuntu/hooks/git.sh"] and environment [] using  as cwd
[webhook] 2017/07/17 19:22:17 command output:
[webhook] 2017/07/17 19:22:17 error occurred: exit status 1
[webhook] 2017/07/17 19:22:17 finished handling git-test
```` 

Any help at all would be great.

**Comment by adnanh** [comment]
Could you also post your hooks.json file so I can try to reproduce the issue?

**Comment by adnanh** [comment]
Also what webhook version are you running?

**Comment by hobakill** [comment]
```
ubuntu@company:~/hooks$ ./webhook --version
webhook version 2.6.4
```

```
[
  {
    "id": "test-webhook",
    "execute-command": "/home/ubuntu/hooks/echo.sh",
    "command-working-directory": "/home/ubuntu/hooks"
  },
  {
    "id": "test2",
    "execute-command": "/home/ubuntu/hooks/echo.sh",
    "command-working-directory": "/home/ubuntu/hooks"
  },
  {
    "id": "git-test",
    "execute-command": "/home/ubuntu/hooks/git.sh",
    "command-working-directory": "/home/ubuntu/hooks"
  }
]
```

thanks for the quick response. i'm brand new to your repo. it's great.

**Comment by hobakill** [comment]
FWIW I have a bit of a workaround but not sure how long this is sustainable:

```
#!/usr/bin/env bash

DBDIR="/some/dir/here"

fetchit() {
  git -C $DBDIR fetch --all
  git -C $DBDIR reset --hard origin/master
}

fetchit
```
the reason this works is because this repo will never be updated on the server where `webhook` is running. still... my ghetto workaround can't be the right answer! 🤣

**Comment by scottstensland** [comment]
One way to to allow `git pull`  to work when the repo lives on github.com is to setup SSH keys then use those keys when running your script.   This question is probably better asked/answered as it has many times over on https://stackoverflow.com/

**Comment by hobakill** [comment]
@scottstensland the server in question already has keys on GitHub. Why would `git pull` work in a standalone shell and a standalone shell script but not in `webhook`? AFAIK `webhook` runs as the login user. in this case it's `ubuntu`. That said you might have given me an idea. I may be closing this ticket in the next 10 minutes.

**Comment by hobakill** [comment]
@scottstensland thanks for the tip. I was running `webhook` as with `sudo` in front. while the `ubuntu` user has keys on GH, `root` does not. took the appropriate actions and all is well again in the world

@adnanh PEBKAC!!!

thanks!

**Comment by adnanh** [comment]
:+1:

**Comment by tvld** [comment]
@hobakill  have same problems... but you describe "took appropriate actions" .. would be nice to know which ?

**Comment by adnanh** [comment]
The problem was that he was running webhook as root user which did not have appropriate ssh keys on the GitHub. He either: ran webhook as user whose keys were on GitHub or he added root ssh keys to the GitHub.

**Comment by AAverin** [comment]
What would be a good way to debug this?
Script only outputs "exit status 1", it would be very helpful to see the full message.

**Comment by AAverin** [comment]
@adnanh which user would be executing webhook if it's setup as a service in ubuntu (installed via apt-get)?

**Comment by AAverin** [comment]
Ok, I figured this out.
Some tips for others.

You can run this in your script to get better errors output and make sure the key is added:
```
echo $(whoami)
eval $(ssh-agent) 2>&1
ssh-add -L 2>&1
ssh-add ~/.ssh/github_readonly_rsa 2>&1
git pull 2>&1 || { echo "failed with $?"; exit 1; }
```
Also, follow this to persist your keys: https://stackoverflow.com/questions/3466626/how-to-permanently-add-a-private-key-with-ssh-add-on-ubuntu

**Comment by injitools** [comment]
you need load bash enviroment. 
exec bash first, not sh script

```
{
  "id": "deploy-project",
  "execute-command": "/bin/bash",
  "command-working-directory": "/path/to/your/project",
  "include-command-output-in-response": true,
  "args": [
    "-l",
    "-c",
    "deploy.sh"
  ]
}
```
