### ISSUE TITLE
Issue passing payload data to script - User Error??

### ISSUE THREAD

**Issue by hassanbabaie** [adnanh/webhook#154]
I seem to be having an issue passing the payload from my webhook post to the script the Go webhook service is executing.

For now it is really simple: I'm passing a chunk of data including:

**"data":{  
      "SCALR_INTERNAL_IP":"172.18.4.14",
      "SCALR_SERVER_HOSTNAME":"USA1042LV000659"**

My hooks.json is:

**[
  {
    "id": "redeploy-webhook",
    "execute-command": "/webhook/src/redeploy.sh",
    "command-working-directory": "/webhook/src",
    "pass-arguments-to-command": [
        {"source": "payload", "name": "data.SCALR_INTERNAL_IP"},
        {"source": "payload", "name": "data.SCALR_SERVER_HOSTNAME"}
    ]
  }
]**

And my script has:

**#!/bin/sh
echo test $SCALR_INTERNAL_IP**

The log below shows the payload information is being pulled but I can seem to get the data into the script and so the result is I just get "**echo test**"

**[root@localhost hassan]# nano /webhook/site/hooks.json
[root@localhost hassan]# /usr/local/webhook-linux-amd64/webhook -hooks /webhook/site/hooks.json -verbose
[webhook] 2017/07/20 16:36:00 version 2.6.4 starting
[webhook] 2017/07/20 16:36:00 setting up os signal watcher
[webhook] 2017/07/20 16:36:00 attempting to load hooks from /webhook/site/hooks.json
[webhook] 2017/07/20 16:36:00 found 1 hook(s) in file
[webhook] 2017/07/20 16:36:00   loaded: redeploy-webhook
[webhook] 2017/07/20 16:36:00 os signal watcher ready
[webhook] 2017/07/20 16:36:00 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2017/07/20 16:38:02 incoming HTTP request from 13.129.107.213:41969
[webhook] 2017/07/20 16:38:02 redeploy-webhook got matched
[webhook] 2017/07/20 16:38:02 redeploy-webhook hook triggered successfully
[webhook] 2017/07/20 16:38:02 2017-07-20T16:38:02-04:00 | 200 |          480.815µs | 10.97.154.22:9000 | POST /hooks/redeploy-webhook
[webhook] 2017/07/20 16:38:02 executing /webhook/src/redeploy.sh (/webhook/src/redeploy.sh) with arguments ["/webhook/src/redeploy.sh" "172.18.4.14" "USA1042LV000659"] and environment [] using /webhook/src as cwd
[webhook] 2017/07/20 16:38:02 command output: test**

Please let me know your thoughts and thanks in advance!

Hass

**Comment by hassanbabaie** [comment]
Ok so I tested the one item I didn't think would work and it did... 

I'm assuming I have to use $1 downward depending on however items I'm calling out of the payload?

**#!/bin/sh
echo test $1**

Correct?, and just to confirm, I think the app is great!

**Comment by hassanbabaie** [comment]
Yep, all tested this can be closed!

Thanks

Hass

**Comment by adnanh** [comment]
You probably wanted to pass these arguments via environment variables and not parameters.

It would look like this:

---

`hooks.json`
```json
[
	{
		"id": "redeploy-webhook",
		"execute-command": "/webhook/src/redeploy.sh",
		"command-working-directory": "/webhook/src",
		"pass-environment-to-command": [
			{
			        "envname": "SCALR_INTERNAL_IP",
				"source": "payload",
				"name": "data.SCALR_INTERNAL_IP"
			},
			{
			        "envname": "SCALR_SERVER_HOSTNAME",
				"source": "payload",
				"name": "data.SCALR_SERVER_HOSTNAME"
			}
		]
	}
]
```

---

`redeploy.sh`

```bash
#!/bin/sh
echo $SCALR_SERVER_HOSTNAME
echo $SCALR_INTERNAL_IP
```

**Comment by hassanbabaie** [comment]
Thanks @adnanh , you might be right however using the $1 etc.. is now working very well and doesn't risk clashing with existing EVN variables on the local server running the webhook app.

**Comment by adnanh** [comment]
:+1: Whichever works best for you :-)
