### ISSUE TITLE
how to add unknown amount of args in unknown form via http?

### ISSUE THREAD

**Issue by yosefy** [adnanh/webhook#157]
like:
http://127.0.0.1:9000/hooks/hook?myargs="-l -h"
so hook will  run: ls -l  -h
and may be next time we need just: ls -l  only...

because sometime i just don't know what will come with parameter but i know i want to add it all after the command

thanks

**Comment by adnanh** [comment]
Do not use ls directly, instead pass the myargs variable to your shell script, decode the args inside of the script yourself and then invoke the ls with those parameters. :-)
