### ISSUE TITLE
How to Echo Back Challange Parameter from DropBox

### ISSUE THREAD

**Issue by zukinaru** [adnanh/webhook#163]
I want to echo back challange parameters from DropBox Webhook API 

Is this possible ?

for example, i need to echo back below request...

Error: TTP code 503 from proxy after CONNECT

Request:
GET https://example.org/hooks/produkto?challenge=examplechallangecode

Response:
(No headers)

Response Body (First 256 bytes):
(No response body)

Reference : https://www.dropbox.com/developers/reference/webhooks

**Comment by adnanh** [comment]
Yes, it is possible.

A sample hook definition could look something like this:

```json
{
    "id": "dropbox-echo",
    "execute-command": "/bin/echo",
    "pass-arguments-to-command": [
        {
            "source": "query",
            "name": "challenge"
        }
    ],
    "include-command-output-in-response": true
}
```
