### ISSUE TITLE
make build does not build from local hook

### ISSUE THREAD

**Issue by col-panic** [adnanh/webhook#168]
In webhook.go import,  "github.com/adnanh/webhook/hook" is referenced. Due to this changes done within hook/ will not be considered for build, as not this module is picked up.

**Comment by moorereason** [comment]
It sounds like you need to use git remotes if you intend to do development work in webhook.

**Comment by col-panic** [comment]
Why? hook is a subdirectory of the given repository, but instead of referencing the own co-located code, it refers to the one stored in the github page (via the import that i am trying to correct)! I don't see the reason to reference to the github version on build?!

**Comment by col-panic** [comment]
Please see the pull request https://github.com/adnanh/webhook/pull/169

**Comment by moorereason** [comment]
I already saw your PR, and I understand your reasoning.  It's just not the _right_ thing to do.  Some advice from [Best practices for a new Go developer](https://blog.rubylearning.com/best-practices-for-a-new-go-developer-8660384302fc):

> Take the time to work with, and understand, the conventions in Go. ... Learn about how packages and import paths work. Go is not a “TMTOWTDI — There’s More Than One Way To Do It” — language. There is a Go way. Learn how Go does things and do it that way. You’ll appreciate the benefits soon enough.

I could be wrong, I guess, but I don't know anyone in the Go community that does what you're proposing.  I'd be curious to know if you've seen others doing this.

Again, the simplest way forward is git remotes.  See the [Hugo Contributing Guide](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#using-git-remotes), which I helped write, for a short synopsis of the workflow.

**Comment by col-panic** [comment]
Thanks a lot for your explanation! I think I got it now - https://splice.com/blog/contributing-open-source-git-repositories-go/ is a good explanation of the problem! 

The problem, however, is that in case I make a feature add and a PR, the code in my forked repository will not compile (to a third party not configuring the remote) until the PR was accepted by the importing project. Is this accepted as fact by the convention?

Consider https://github.com/col-panic/webhook/commit/34c4b1c16686ec07beef6671684cc7f012a835a1 - if you would checkout my forked repository, and I would not have changed the import to "./hook" then the code would not compile until you would also manually set the resp. remote to "override" the import of "github.com/adnanh/webhook/hook". Is this accepted as-is by the go community? google says there is quite some discussion on this ... e.g. https://groups.google.com/forum/#!topic/golang-nuts/AL8UyjGl948

**Comment by adnanh** [comment]
If you plan on developing features for the upstream, create a simple symlink $GOPATH/src/github.com/adnanh to point to your $GOPATH/src/github.com/col-panic
