### ISSUE TITLE
Allow the ability to specify user to run execute-command as

### ISSUE THREAD

**Issue by dharrigan** [adnanh/webhook#170]
Hi,

When configuring webhooks to run as a service, it would be useful to allow the execute-command to be run as a particular user. Of course, this can be done within the execute-command string itself, i.e., sudo, but perhaps a more elegant approach could be something like:

```
[
    {
        "id": "push-push-push",
        "execute-command": "./post-something-witty-to-slack.sh",
        "execute-command-as": "foo",
        "command-working-directory": "/home/foo/bin"
    }
]
```

This would be very attractive from a security PoV.

Thank you.

-=david=-

**Comment by moorereason** [comment]
All webhook is going to do is run `su` in the background.  This feels like feature creep to me.

**Comment by adnanh** [comment]
I completely agree with @moorereason
