### ISSUE TITLE
How to check logs?

### ISSUE THREAD

**Issue by CarlosEvo** [adnanh/webhook#177]
Hi, I have been running some issues that some web requests made by python scripts under the webhook not working. I tried to access the logs, but the `journalctl` is not giving much info except `500 Internal Server Error`. For the record the python scripts run fine standalone.

Is there a log file specific for `webhook`? I couldn't find it described anywhere in this repo. I will much appreciate any help.

**Comment by hassanbabaie** [comment]
Hi @CarlosEvo running in non-interactive mode I;ve been using 

`journalctl -u webhook`

And while it is light on the logs it should give some info, have you tried hitting the webhook directly from a web browser to see what happens?

**Comment by adnanh** [comment]
Webhook will log to the stdout/stderr if you use the -verbose flag when starting it up. So make sure to redirect that output to a file of your choice.

If the webhook is running as a service, make sure that it is started in the verbose mode (with the -verbose flag) and check out the journal logs.

**Comment by CarlosEvo** [comment]
@hassanbabaie I did used `jornalctl -u webhook` to debug. Unfortunately my hook requires `POST` data, so I can't really debug it with a browser (Zapier doesn't help either). It is more of a python script problem. Nonetheless @adnanh helped me a lot with the -verbose option.

Thank you both, really appreciate it.

**Comment by adnanh** [comment]
Glad to hear that :-) Cheers!
