### ISSUE TITLE
Running webhook in the background

### ISSUE THREAD

**Issue by FaisalDefry** [adnanh/webhook#181]
Hi, is there any correct way to run webhook in the background?  i do able to use "nohup" to send the process to backgroung, but this is only works if i execute it directly on terminal. it doesn't work if i put it in cron / other script.

thank you in advance

**Comment by scottstensland** [comment]
Lookup a tool called supervisor which will launch a process (webhook) as well as take care of rotating stdout/stderr log files and relaunching process on box reboot ...  http://supervisord.org/
additionally you can in turn wrap supervisor to be a systemd started task 

webhook is a daemon so if launched by cron assure you avoid multiple instances of it attempting to run (they will fight over ports) ... if cron launch fails make sure you are sourcing the necessary environment variables neede by your webhook

**Comment by FaisalDefry** [comment]
Hi , thank you for the reply. Yes, i think that's the solution i need for , totally forgot about supervisord because i usually only use that on docker container. Wrapping supervisord in systemd sounds like a good idea, because what i'm trying to do is trying to do with cron earlier is a "at reboot" trigger ensure the webhook still running on server reboot.
________________________________
