### ISSUE TITLE
got matched, but didn't get triggered because the trigger rules were not satisfied

### ISSUE THREAD

**Issue by fredguy** [adnanh/webhook#182]
Hello all,

I'm running the following hook : 

```
[
  {
    "id": "play",
    "execute-command": "/test.sh",
    "command-working-directory": "/",
    "trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "media.play",
        "parameter":
        {
          "source": "payload",
          "name": "event"
        }
      }
    }
}
]
```

But once the payload arrives : 
```
Content-Disposition: form-data; name="payload"
Content-Type: application/json

{"event":"media.play","user":true,"owner":true,"Account" [...]
```

I doesn't seem to work out so well. I don't get what i'm doing wrong. 

Logs give me the following : 

> [webhook] 2017/10/16 12:01:00 version 2.6.5 starting
> [webhook] 2017/10/16 12:01:00 setting up os signal watcher
> [webhook] 2017/10/16 12:01:00 attempting to load hooks from play.json
> [webhook] 2017/10/16 12:01:00 os signal watcher ready
> [webhook] 2017/10/16 12:01:00 found 1 hook(s) in file
> [webhook] 2017/10/16 12:01:00   loaded: play
> [webhook] 2017/10/16 12:01:00 serving hooks on http://192.168.0.150:9000/hooks/{id}
> [webhook] 2017/10/16 12:01:03 incoming HTTP request from 192.168.0.110:46641
> [webhook] 2017/10/16 12:01:03 play got matched
> [webhook] 2017/10/16 12:01:03 error parsing form payload invalid URL escape "%\xf0\xc5"
> [webhook] 2017/10/16 12:01:03 play got matched, but didn't get triggered because the trigger rules were not satisfied
> [webhook] 2017/10/16 12:01:03 200 | 2.027064ms | 192.168.0.150:9000 | POST /hooks/play
>

**Comment by fredguy** [comment]
Also tried an alternative : 
```
[
  {
    "id": "play",
    "execute-command": "/test.sh",
    "command-working-directory": "/",
        "parse-parameters-as-json":
[
      {
        "source": "payload",
        "name": "event"
      }
],
"trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "media.play",
        "parameter":
        {
          "source": "payload",
          "name": "event"
        }
      }
    }
}
]
```

but htat gets me:

> [webhook] 2017/10/16 14:10:59 version 2.6.5 starting
> [webhook] 2017/10/16 14:10:59 setting up os signal watcher
> [webhook] 2017/10/16 14:10:59 attempting to load hooks from play.json
> [webhook] 2017/10/16 14:10:59 os signal watcher ready
> [webhook] 2017/10/16 14:10:59 found 1 hook(s) in file
> [webhook] 2017/10/16 14:10:59   loaded: play
> [webhook] 2017/10/16 14:10:59 serving hooks on http://192.168.0.150:9000/hooks/{id}
> [webhook] 2017/10/16 14:11:23 incoming HTTP request from 192.168.0.110:46880
> [webhook] 2017/10/16 14:11:23 play got matched
> [webhook] 2017/10/16 14:11:23 error parsing form payload invalid URL escape "%)\u007f"
> [webhook] 2017/10/16 14:11:23 error parsing JSON parameters: couldn't retrieve argument for {Source:payload Name:event EnvName:}
> [webhook] 2017/10/16 14:11:23 play got matched, but didn't get triggered because the trigger rules were not satisfied
> [webhook] 2017/10/16 14:11:23 200 | 1.161037ms | 192.168.0.150:9000 | POST /hooks/play
>

**Comment by fredguy** [comment]
Hi Again. 
the post i'm dealing with seems to be a multipart with Json payload and then come a jpeg. 
Would that be a showstopper for adnanh/webhook ? Is there a way to process the Payload only part ? 

This is actually a dump of the post received : 
```
Content-Disposition: form-data; name="payload"
Content-Type: application/json

{"event":"media.play","user":true,"owner":true}
------------------------------33d2ecba7af4
Content-Disposition: form-data; name="thumb"; filename="thumb.jpg"
Content-Type: image/jpeg

ÿØÿàJFIFHHÿÛC		

 $.' ",#(7),01444'9=82<.342ÿÛC			

2!!22222222222222222222222222222222222222222222222222ÿÀqÈÿÄÿÄ7	!1RS¡"3AQq2BCa#$brsÑÿÄÿÄÿÚ?üþUi0¹/-ÑûÉè}ä½tE>ò@CÒaÞH
=2÷$ÇL¤úêH=*{?i4îOÐÑ©5ñgèè´ø³ôK¼ Ðô»Ùúèz]ìý£R»?ô-ö~BÑïgà¢Qï§àÏGÖõõê'ö@e&mâ³í|ÓÐ­ãÕZ§ å£Q]UgèJrÃ«?]cømgsmJ¥KÛÎqM¤£°®ÿ¬mæãÛª8*YT@OrrÃ,Ä)exK;/ZO`1ä	È9ÙÄ`2[ÖÄÀÚ¯pq<÷WÞ`Rrù =-ÕÝÞA?ÉÄ²Ômi%¤º>§ñ¥÷å;e,e-Ä'¸âÒØ&Ó/9°q %u` Ø
------------------------------33d2ecba7af4--
```

**Comment by adnanh** [comment]
It appears that the JPEG contents is messing up the payload parsing. Is there any way you could base64 encode the JPEG image on the client and send that as a parameter?

**Comment by fredguy** [comment]
I wish i could. Sadly the payload is originating from Plex media server, and this is pretty much locked down. I request from their side that they enable a Json payload only option... but this may take forever. :(

**Comment by adnanh** [comment]
Unfortunately, your only option would be rolling out your own solution to receive the Plex's payload and then either handle the execution yourself, or forward the request with proper payload to the webhook.

Sorry :-(

**Comment by fredguy** [comment]
I understand. 
I was wondering though. would there be a way to apply a regex filter on the whole post regardless of this being the payload or anything else. That way i could trigger the actin based on the presence of a specific string. ?

**Comment by adnanh** [comment]
Not really, turns out that your post body contains invalid byte sequence that messes up golang's form parsing library. We can't do anything with that payload :-(

**Comment by fredguy** [comment]
Hi Just checking if the latest version allowed support of multi-part payload - or if there is any hope to address this in any sort of future ?

**Comment by gregor-hh** [comment]
hi @fredguy ,
have you at the meantime found an other solution??? want the same like you. 
best regards

**Comment by fredguy** [comment]
hi @gregor-hh 
I switch to an alternatie solution locate on the endoint (jeedom home automation). They have a plugin that is called "http remote event" https://jeedom.github.io/documentation/third_plugin/httpRemoteEvent/fr_FR/index.html
and a script that allows me to parse the payload properly. 

I guess that won't be much help for you in your case. 
GL
Cheers

**Comment by gregor-hh** [comment]
thank you very much for this tip/hint.
I must think about it, maybe its a bit „oversized“ :)
but it looks, like a cool home automation software, I dont have one, maybe its a new project in the future^^. for now I only want grab the media.play events from plex to the telegram web api (bot) for push notifications...

have a nice day
best regards

**Comment by maximelafarie** [comment]
Sad it's still unsupported. Got `[webhook] 2024/01/22 01:18:43 [62c88a] error parsing form payload invalid URL escape "%9\x1f"`.

It would be interesting to add a "sanitizer" option that deletes all files attached to a webhook.

I'm using webhook version 2.6.9 (debian)
