### ISSUE TITLE
got matched, but didn't get triggered because the trigger rules were not satisfied

### ISSUE THREAD

**Issue by NathanAhlstrom** [adnanh/webhook#183]
Hi Adnan,

Thanks for building webhook.  I am attempting to use it with gitlab - I have the attached hooks.json and the webhook call data from gitlab.  Everytime it matches the id, but doesn't trigger because says the rules were not satisfied.  

Do you have any insights to this?  It seems like I have everything setup correctly, but I could be missing something.

Thanks!
Nathan

[webhook-json-input.txt](https://github.com/adnanh/webhook/files/1416375/webhook-json-input.txt)
[hook.json.txt](https://github.com/adnanh/webhook/files/1416379/hook.json.txt)

**Comment by adnanh** [comment]
Hey, don't have an access to the computer right now, I'll check it out tomorrow and hopefully get back to you with a solution.

**Comment by adnanh** [comment]
You should omit `payload.` from the `"name": "payload.project.default_branch"` and it should work.

**Comment by adnanh** [comment]
Sorry for the late response :-)
