### ISSUE TITLE
Option to specify file for output

### ISSUE THREAD

**Issue by dcj** [adnanh/webhook#197]
I'm running webhook via a rc.d script on OpenBSD, and attempting to use stdout/stderr redirection is problematic.  A command line option for a filename that webhook would append its output into would facilitate this use case.  Would you be amenable to a pull request adding this?

**Comment by adnanh** [comment]
:+1:

Most definitely, just make logfile flag default to "-" which would mean stdout/stderr and anything other than that would be understood as a filename to write/append to.

That way we keep the default behavior compatible with old versions.

**Comment by hassanbabaie** [comment]
@dcj do you think we could use this to have two independent webhooks (HA) writing to a shared file?

**Comment by dcj** [comment]
@hassanbabaie I am not sure I understand what you are asking... The output I am proposing to write to a file is the output of webhook itself, which provides info about what hooks are called and details of what happened then.  I currently feel individual/specific hooks should take care of their own logging, if any.  If you run two instances of webhook on the same server (e.g. on different ports), then no, I am not proposing to combine their outputs.  IMHO each of these instances should write to their own log file.
A more comprehensive logging feature might be to log to some sort of (networked) logging framework, syslog, logstash, etc.  but I am not proposing to implement that sort of feature....

**Comment by hassanbabaie** [comment]
Currently the way we're using Webhook is that it is running on a CentOS VM and just does it's thing to the point we forget about it. Were about to start using it more and need to ensure there is uptime and an easier way to troubleshoot if something goes wrong down the line. 

I plan on deploying these on two VM and using DNS to load balance and auto fail over if one goes down. The hard part is having the log to sense check. My idea is to try and gets these both on a single file that can be used by the others in the team; I'm not a pro at this stuff but working it out now and your PR request sounds good

**Comment by adnanh** [comment]
@hassanbabaie Sounds like you should try [Logstash](https://www.elastic.co/products/logstash) for centralizing your logs. If I recall correctly, by default stdout and stderr of a systemd unit are sent to syslog, which means if you're running one or two instances of webhook as a service, they would be logged properly in the syslog.

**Comment by hassanbabaie** [comment]
Thanks @adnanh  we're in the process of spinning up an ELK stack so I will see how it goes.

Just to confirm though this product really just works so well!!1

FYI, we talked to a company we use that sends out a large amount of webhooks to see how we can get it to support with a signing key.

https://github.com/scalr-tutorials/webhook

They forked it to get it working for us in our testing. Just out of interest would this be something you would support a PR for or is this too specific to one users req? If you do I'll ask them to do a PR

Hass

**Comment by adnanh** [comment]
Sounds okay to me to bake in support for their signature verification :-)

**Comment by hassanbabaie** [comment]
Great, I'll let them know,

@dcj yes sorry for change subject (all in a good cause!)

**Comment by moorereason** [comment]
Merged into master as 569921c.
