### ISSUE TITLE
Support options to drop privilege level after opening port, and chroot 

### ISSUE THREAD

**Issue by dcj** [adnanh/webhook#198]
I am running webhook on OpenBSD, a non-Linux....
I have encountered at least one instance where a web service requires the destination ports to be 80/443 (namely, Jira Cloud)
I vastly prefer to run webhook as a non-root user, so running on privileged ports is problematic, therefore I propose the classic workaround of starting as root, opening the port, and then dropping privilege to a specified uid.

Separately, but related, would be an option to chroot webhook to a specified path/directory on startup (before dropping privilege)

As a work-around to the privileged port issue, I am using PF to redirect 443 to a non-privledged port where webhook is running, but that is not ideal....

**Comment by adnanh** [comment]
That would indeed be a handy feature. Currently I use nginx in front of my webhook instances that are listening on unprivileged ports.

**Comment by moorereason** [comment]
This feature looks possible for most Unix platforms.  Unsupported on Linux (see https://github.com/golang/go/issues/1435).

**Comment by adnanh** [comment]
Partial support will be available as of 2.7.0. Unfortunately, Linux is not supported by Golang's implementation of setuid and setgid.
