### ISSUE TITLE
Update references to negroni

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#201]
The negroni package has been moved from `github.com/codegangsta/negroni` to `github.com/urfave/negroni`.  We should update import paths and vendoring.

**Comment by freeekanayaka** [comment]
Note that this makes it necessary to patch the upstream code for distributions like Debian, see [here](https://salsa.debian.org/go-team/packages/webhook/blob/master/debian/patches/0002-Use-urfave-negroni-package-and-not-the-one-from-code.patch) for example.

**Comment by adnanh** [comment]
:+1: will do this ASAP.

**Comment by moorereason** [comment]
Superseded by #374
