### ISSUE TITLE
Usability: Missing validation on secret value when using hmac

### ISSUE THREAD

**Issue by manicmonkey** [adnanh/webhook#207]
When using a trigger of payload-hash-sha256 (and presumably sha1) if you forget the 'secret' parameter, you won't get any notification in the logs to make it apparent.

Awesome project though, really like the json parsing!!

**Comment by simbo1905** [comment]
This just bit me.  Using webhook version 2.6.9 I misconfigured a payload-hash-sha1 match with "value" not "secret" such as: 

```
{
        "match":
        {
          "type": "payload-hash-sha1",
          "value": "{{ getenv "WEBHOOK_SECRET" | js }}", // <-- WRONG! "secret" not "value"
          "parameter":
          {
            "source": "header",
            "name": "X-Hub-Signature"
          }
        }
}
```

The mistake isn't validated at load time. If you don't pass the X-Hub-Signature you get the correct "rules not matched" 200 response. If you do pass the header you get a 500 response code and response body "Error occurred while evaluating hook rules." What is logged is:

```
[webhook] 2019/01/02 21:00:25 [0748c1] error evaluating hook: invalid payload signature 0dcb8309afa36a67d6565a2ab972883a06a642ef
```

If the match rule was validated at load time then folks wouldn't run into the 500 error.

**Comment by jack1142** [comment]
I think this could be checked for all types of matches as it's quite easy to not notice that you didn't change key name to the right one. So I think match rule should check if required key is provided (`value`, `regex`, `secret`, `ip-range` depending on match type)
