### ISSUE TITLE
JSON with top-level array results in a parsing error

### ISSUE THREAD

**Issue by juliengb** [adnanh/webhook#215]
Using this software to handle JSON data with a top-level array results in a parsing error.

Looking at the code, the JSON is systematically [parsed](https://github.com/adnanh/webhook/blob/a811db410bf321f0820f4464f51f371ebb012db1/webhook.go#L238) into a [map[string]interface{}](https://github.com/adnanh/webhook/blob/a811db410bf321f0820f4464f51f371ebb012db1/webhook.go#L230), resulting in the error.

An example of top-level array can be found in [Sendgrid's event webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Event-POST-Example)

**Comment by adnanh** [comment]
Ah yes, I was waiting for the first real world use case of top level arrays in JSON :-)

Sure, this needs to be fixed now.

**Comment by tvld** [comment]
Not sure if this is related, but BitBucket webhook sends arrays. I found:
Standard json with ``push.changes[0].new`` does **not** work, but this works:

```json
{
        "source": "payload",
        "name": "push.changes.0.new.target.message"
      },
      {
        "source": "payload",
        "name": "push.changes.0.new.target.author.raw"
      }
```

**Comment by adnanh** [comment]
The original issue refers to the payload being an array, not an object with arrays :-)

**Comment by tvld** [comment]
Thanks... the tool is excellent by the way. It' s in production ;-)
