### ISSUE TITLE
go install faild

### ISSUE THREAD

**Issue by shining01** [adnanh/webhook#216]
Hello,

i geht the follawing error when i install webhook with "go install" on raspberry pi 3 with jessie:
```

root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go install
# github.com/gorilla/mux
../../gorilla/mux/mux.go:114: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
../../gorilla/mux/regexp.go:171: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
../../gorilla/mux/regexp.go:281: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/env_unix.go:30: undefined: syscall.Unsetenv
```

**Comment by ChrisHardie** [comment]
FWIW I encountered a similar error and it ended up requiring removing the outdated version of Go that came with Ubuntu's package management and installing the latest stable release.

**Comment by shining01** [comment]
Thanks for your answer. No i have installed go 1.9.2

`root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go install
webhook.go:16:2: cannot find package "github.com/adnanh/webhook/hook" in any of:
        /usr/local/go/src/github.com/adnanh/webhook/hook (from $GOROOT)
        /opt/go/src/github.com/adnanh/webhook/hook (from $GOPATH)
webhook.go:18:2: cannot find package "github.com/codegangsta/negroni" in any of:
        /usr/local/go/src/github.com/codegangsta/negroni (from $GOROOT)
        /opt/go/src/github.com/codegangsta/negroni (from $GOPATH)
webhook.go:19:2: cannot find package "github.com/gorilla/mux" in any of:
        /usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
        /opt/go/src/github.com/gorilla/mux (from $GOPATH)
webhook.go:20:2: cannot find package "github.com/satori/go.uuid" in any of:
        /usr/local/go/src/github.com/satori/go.uuid (from $GOROOT)
        /opt/go/src/github.com/satori/go.uuid (from $GOPATH)
webhook.go:22:2: cannot find package "gopkg.in/fsnotify.v1" in any of:
        /usr/local/go/src/gopkg.in/fsnotify.v1 (from $GOROOT)
        /opt/go/src/gopkg.in/fsnotify.v1 (from $GOPATH)
`

`root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build798987959=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
`

**Comment by shining01** [comment]
How can i run webhook with which command?

i have tried: 

`root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# webhook.go -hooks /opt/webhook/hooks.json -verbose
bash: webhook.go: Kommando nicht gefunden.
root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go webhook.go -hooks /opt/webhook/hooks.json -verbose
go: unknown subcommand "webhook.go"
Run 'go help' for usage.
root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go webhook -hooks /opt/webhook/hooks.json -verbose
go: unknown subcommand "webhook"
Run 'go help' for usage.
root@raspberrypi:/opt/go/packages/src/github.com/adnanh/webhook# go run webhook -hooks /opt/webhook/hooks.json -verbose
go run: no go files listed
`

**Comment by shining01** [comment]
GOPATH where wrong. Must be point to the folder where webhook packages are
