### ISSUE TITLE
Can hooks.json support logic comparing multiple numerical values like <,>,=,<=,>=

### ISSUE THREAD

**Issue by psmith3** [adnanh/webhook#217]
I have a new challenge and want to look at the fields in the data below and if roomName="Kitchen" and newVolume is greater than previousVolume, execute script vol-key-up.sh. If roomName="Kitchen" and newVolume is lower than previousVolume, execute script vol-key-down.sh. 

`{"type":"volume-change","data":{"uuid":"RINCON_000E583A2E2401400","previousVolume":49,"newVolume":35,"roomName":"Kitchen"}}`

@adnanh , is there any way to do this that you know of? Looking at the hook rules, I don't see I way that I can identify.

**Comment by adnanh** [comment]
Not in the context of trigger rules, but you can do that easily in your shell script :-)

**Comment by moorereason** [comment]
There's really two new ideas here that webhook can't do (yet?):

1. Using `gt`, `lt`, `ge`, and `le` operators in a Match rule (`value` handles the `eq` case).
1. Getting both operands in a Match rule from parameters.
