### ISSUE TITLE
Sending a request to a URL

### ISSUE THREAD

**Issue by RandomWolf** [adnanh/webhook#219]
Hi there,
I have recently found out about the whole webhook deal and wanted to use it for a little fun project:
A website that sends a text input via webhook to ifttt, to display it on my phone.
I've already got the API URL an' everything, but I lack the knowledge to use it.

How can I send the payload ( the user-input text ) to an URL like https://maker.ifttt.com/use/vABCDEFGHIJKLM-JDIOjit59K34NrKR, using this webhook software, so IFTTT can grab it and execute it?

**Comment by adnanh** [comment]
You can define a hook to execute a `curl` command with appropriate parameters. If you want me to help you with creating a hook definition, I would need to know exact payload your API will send to webhook, and the exact payload IFTTT wants to receive to send you an SMS.
