### ISSUE TITLE
GitLab support?

### ISSUE THREAD

**Issue by denji** [adnanh/webhook#22]
- [Diff GitHub-GitLab Hook](https://github.com/dimfeld/unwebhook/blob/master/event_test.go#L23-L144) [[1]](https://github.com/ulrichSchreiner/gl#gl) [[2]](https://github.com/dimfeld/unwebhook)
 - [gitlabhq-7.9 Web hooks](https://github.com/gitlabhq/gitlabhq/blob/7-9-stable/doc/web_hooks/web_hooks.md#push-events)

**Comment by moorereason** [comment]
Have you tried to use GitLab with webhook?  I haven't tested it, but I don't see any reason why it wouldn't work.

It looks like you'd want to check that ``object_kind`` equals ``push`` in your trigger rules.  Let us know how your testing goes.

**Comment by adnanh** [comment]
Did you open an issue on the wrong repository by any chance?

**Comment by adnanh** [comment]
There is no reason for the webhook not to be able to parse the incoming Gitlab webhook considering the Gitlab makes a valid POST request to webhook with the JSON payload and correctly specified Content-Type header...
```http
Content-Type: application/json
```

Please refer to the [wiki pages](https://github.com/adnanh/webhook/wiki) to see how to create a hook.
