### ISSUE TITLE
hotreload not working

### ISSUE THREAD

**Issue by ptflp** [adnanh/webhook#221]
not working hotreload, when using it inside docker container.

**Comment by hassanbabaie** [comment]
Hi @ptflp sorry I've not tested using hot reload in a container so hoepfully someone else might comment. 

However just out of interest I would have expected you to treat the container as immutable and so only performed this task during container creation at which point I don;t think you need to use the hot reload do you?

**Comment by adnanh** [comment]
@ptflp Are you editing the file outside of docker container?

**Comment by ptflp** [comment]
@adnanh, hooks.json updates from host machine when webhook is triggered

**Comment by sh33pz0r** [comment]
@ptflp - how do you mount your file into the guest container? make sure to mount folder and not a specific file,
my tests with the latest version of webhook work as expected,

that's from docker logs:
```
[webhook] 2018/03/01 13:32:01 hooks file hooks.yaml overwritten
[webhook] 2018/03/01 13:32:01 attempting to reload hooks from hooks.yaml
[webhook] 2018/03/01 13:32:01 found 2 hook(s) in file
[webhook] 2018/03/01 13:32:01 	loaded: import
[webhook] 2018/03/01 13:32:01 	loaded: export
```

**Comment by ptflp** [comment]
@sh33pz0r, Thank you! folder bind mount, instead file, solved it!
