### ISSUE TITLE
Community packaged version of webhook on Ubuntu does not exist

### ISSUE THREAD

**Issue by whimzee** [adnanh/webhook#222]
In the readme it is stated that you can install webhook on Ubuntu by running `sudo apt-get install webhook`. The package does not exist on apt-get.

```
$ sudo apt-get install webhook
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package webhook
```

**Comment by scottstensland** [comment]
The readme say its for ubuntu 17.04 or above ... an alternative is to directly install the ubuntu deb 

https://packages.debian.org/sid/webhook

choose your architecture then download the appropriate deb file ... once downloaded a typical install is

`sudo dpkg -i webhook_2.5.0-2_amd64.deb
`

**Comment by adnanh** [comment]
Thank you @scottstensland

**Comment by sbrl** [comment]
For those finding this issue after discovering that `webhook` is not available in their distro's default repos, I've now got packaged in my personal apt repository: https://apt.starbeamrainbowlabs.com/

I don't have a Go compiler installed, so I've written a script to auto-package the binaries attached to the latest releases on GitHub, using `fpm`. The `webhook-service` package uses `pleaserun` to auto-generate service file definitions based on your service manager (OpenRC, systemd, and more supported) - though you may want to customise the auto-generated service file if you use this package.
