### ISSUE TITLE
Continue receiving a 404

### ISSUE THREAD

**Issue by tress777** [adnanh/webhook#223]
I'm using the sample hooks.json file in the README. I continue to get the following message:

[webhook] 2018/02/13 21:27:37 [d539a8] incoming HTTP request from 172.21.9.14:45960
[webhook] 2018/02/13 21:27:37 404 | 178.255µs | 172.21.13.134:9000 | GET /hooks/redeploy-hook

Are there specific permissions/ownership necessary on the files? Thank you very much for your assistance.

**Comment by moorereason** [comment]
The sample `hooks.json` file has a different hook `id` from the example in the README.  Hit `/hooks/webhook`.

**Comment by tress777** [comment]
Still the same result, but it's likely that I'm making a boneheaded mistake. Here is my hooks.json, located in user home directory.
`[
  {
    "id": "redeploy-webhook",
    "execute-command": "var/scripts/redeploy.sh",
    "command-working-directory": "/var/webhook",
    "response-message": "Executing redeploy script"
  }
]
`

The bash script is located at: `/var/scripts/redeploy.sh`

The command I run is:

`
~/go/bin/webhook -hooks ~/hooks.json -verbose
`

**Comment by tress777** [comment]
My apologies. I just realized what you meant by the wrong id. I was just using uri:9000/webhook instead of uri:9000/redeploy-webhook. I told you it was probably something boneheaded. Thank you very much!
