### ISSUE TITLE
rename webhook prebuilt binary to webhook.exe

### ISSUE THREAD

**Issue by macau23** [adnanh/webhook#224]
Could the prebuilt binary be named webhook.exe for Windows? Then it can be launched from the command prompt easily.

**Comment by adnanh** [comment]
@macau23 Most definitely!

**Comment by moorereason** [comment]
@adnanh, we use [goreleaser](https://github.com/goreleaser/goreleaser) in [Hugo](https://github.com/gohugoio/hugo/blob/master/goreleaser.yml).  Might make your life a little easier if you have time to play with it.

**Comment by adnanh** [comment]
@moorereason I'll play around with it :-)

**Comment by macau23** [comment]
This hit me again today. Is there a goreleaser config file in git somewhere, so I can submit a patch to add

    -name webhook.exe

**Comment by adnanh** [comment]
As of webhook 2.6.9 this should be respected
