### ISSUE TITLE
did not find expected hexdecimal number

### ISSUE THREAD

**Issue by macau23** [adnanh/webhook#225]
On Windows, my hooks.json contains this:

`"execute-command": "C:\Users\someuser\somescript.bat",`

But the `\U` is interpreted as a hexadecimal number:

`did not find expected hexdecimal number`

Even though the \U is uppercase.

Escaping the backslash does not change the error. The workaround is to use forward slashes.

**Comment by adnanh** [comment]
@macau23 Thanks for bringing this issue up!

@moorereason perhaps we could do path normalization along with a check if the specified command to execute exists for all defined hooks?

The check could spit out warnings, or terminate the process if the webhook is running in the silent mode (in the same way we do when we cannot load hooks file). 

Thoughts?

**Comment by moorereason** [comment]
@macau23,
You definitely need to escape the backslashes due to the JSON/YAML string specs.  But as you mentioned, the problem remains even with the escaping.

@adnanh,
I should be able to test this on a Windows box today.

**Comment by moorereason** [comment]
@macau23,
I'm unable to reproduce this issue.  When I escape the backslashes, the hook works for me.  Can you provide us with your hooks configuration and the verbose logs of the error?

**Comment by macau23** [comment]
@moorereason the escaping is working for me now too. I must have made a mistake, apologies.

**Comment by adnanh** [comment]
Cool, I still think we should add a warning if the command cannot be found at the hooks loading time.

**Comment by macau23** [comment]
Close?
