### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#226]
Some of our existing tests fail on Windows.  We need cross-platform CI to help catch these issues.

- [x] Travis CI (or equivalent) for Linux and macOS
- [x] Appveyor for Windows

I can help with these configurations, but we probably need accounts setup in each service.

**Comment by adnanh** [comment]
Sounds great, if you could create the configurations I can set up the accounts and the required integrations.

**Comment by adnanh** [comment]
We can close this one now, right?
