### ISSUE TITLE
Universal configuration library parser

### ISSUE THREAD

**Issue by denji** [adnanh/webhook#23]
I have a suggestion to use a generic parser configs, will choose what is more to taste.
URL: https://github.com/vstakhov/libucl#basic-structure
Support syntax: `JSON`, `Compacted JSON`, `nginx style`, `YAML`
- [Go modules](https://github.com/search?l=Go&q=libucl&type=Repositories&utf8=%E2%9C%93)

```
ucl: parsed input in 0.3002 seconds
ucl: emitted config in 0.1174 seconds
ucl: emitted json in 0.1174 seconds
ucl: emitted compact json in 0.0991 seconds
ucl: emitted yaml in 0.1354 seconds
```

**Comment by adnanh** [comment]
Thanks for your suggestion, however, adding this feature to webhook would just increase the application complexity without providing any significant improvement.

If you wish, you could make a converter tool that converts webhook configuration files in specified formats into the webhook json format. I'd be more than glad to link to it on the [wiki](https://github.com/adnanh/webhook/wiki) and the [README](https://github.com/adnanh/webhook/blob/master/README.md) pages :-)
