### ISSUE TITLE
feature: include a health-check endpoint

### ISSUE THREAD

**Issue by fbartels** [adnanh/webhook#233]
Hi,

I was thinking of packaging up webhook for https://cloudron.io/. Cloudron utilities internal healthchecks for apps, where they are constantly calling an url and report the app back as "working" if there is a 200 response.

Unfortunaty calling any url that does not belong to a valid hook gives a 404 in webhook, which means Cloudron recognizes webhook as "not responding".

The idea would be to have a "/health-check" endpoint in webhook that always returns http 200.

**Comment by hassanbabaie** [comment]
@fbartels just a thought, could you do a dedicated health-check hook for this purpose?

**Comment by fbartels** [comment]
Yes, that could be a workaround for the moment. But this is prone to errors, since the end user could delete such a good!.

**Comment by moorereason** [comment]
And then Cloudron would alert this error-prone user not to delete that hook, right?

**Comment by hassanbabaie** [comment]
We use DNS polling on port 9000 so don;t have this issue but I think by doing a custom health hook you can also drive a custom response to the health checker outside of just a HTTP200

**Comment by fbartels** [comment]
> And then Cloudron would alert this error-prone user not to delete that hook, right?

No, management of hooks would still be through the json file without a web gui around this. But what I could do is include a comment in the default hook file warning the user not to delete it.

If the user would delete the healthcheck hook, cloudron would mark the apps as "not responding" and send out an email alert to the admin of the system. Other hooks would continue to work. Its not optimal but could work.

I'm not a go developer, but if there is general interest I could try to stitch together a patch for this following the example in https://github.com/Kopano-dev/konnect/commit/974d57447c5a410ef8ab917820db1b0426be2ef3.

**Comment by adnanh** [comment]
Let's make the `/` route return 200 OK...

**Comment by adnanh** [comment]
Done, will be released next in the 2.6.10
