### ISSUE TITLE
Allow disabling GET requests globally.

### ISSUE THREAD

**Issue by wrouesnel** [adnanh/webhook#248]
There's a certain hazard with having GET requests trigger direct action - i.e. if someone drops a link into Slack, then it's pretty likely to fire the hook a whole lot.

It would be nice to, at least globally, disable GET requests from activating webhooks altogether and allowing only POST. Currently I accomplish this by putting nginx with a deny rule in front of it, but that's not a lightweight solution.

**Comment by adnanh** [comment]
I completely agree with you. I propose we add `allowed-http-verbs` in a way we did with response headers. (Global setting and per hook setting)
