### ISSUE TITLE
Send file content with webhook

### ISSUE THREAD

**Issue by matejzero** [adnanh/webhook#249]
Hello,

I have a use case, where I would like to send a content of a file via webhook and then run a command to restart the service.

As part of a deploy CI job, I would like to do the following:
 - CI job would call the webhook
 - it would pass it a content of docker-compose file
 - webhook would save this file to a local path (working-dir would be great)
 - webhook daemon would run docker-compose pull & docker-compose up

Is that possible to do without extra scripts on client side?

**Comment by adnanh** [comment]
Sounds to me like you could use `pass-file-to-command` hook property to serialize input field into a file, which you could then use as you described. See more about hook properties and what do they do [here](https://github.com/adnanh/webhook/blob/master/docs/Hook-Definition.md).

Please note that you would need to use webhook 2.6.8 for this property.

**Comment by matejzero** [comment]
Thanks, I'll have a look.
