### ISSUE TITLE
How to upload a script then excute?

### ISSUE THREAD

**Issue by m2acgi** [adnanh/webhook#252]
How to upload a script then excute? I need some example codes. Thank u.

**Comment by scottstensland** [comment]
The machine where you are executing your webhook server can execute a script already on that machine ... are you asking how to get a script onto your server ? or how to have your webhook launch a script on the server which in turn uploads a script which it then executes ?

**Comment by m2acgi** [comment]
Yes, I want to upload a script from my PC to webhook sever then excute it on webhook server.

**Comment by scottstensland** [comment]
For the webhook  to work it needs to execute on a server which is visable from the internet ... if you do not already have a server you can get yourself one from any cloud hosting provider ... a small one will set you back less than $4 per month over at https://www.ovh.com/world/vps/

**Comment by moorereason** [comment]
Webhook provides everything you need to ingest a given payload and hand it off to a separate program, but providing an example program is outside the scope of this support channel.
