### ISSUE TITLE
Support for custom return status codes

### ISSUE THREAD

**Issue by aioobe** [adnanh/webhook#258]
I'm using webhook to process form submissions from my webpage.

Unfortunately, after the user has submitted the form, he/she ends up on a blank page (status: 200, without content). I would like webhook to allow me to send a 302 http status, for this specific hook.

Is this possible? Has it been considered as a feature?

**Comment by aioobe** [comment]
Created a PR for this feature: https://github.com/adnanh/webhook/pull/259

**Comment by moorereason** [comment]
Fixed in #266 and included in v2.6.10.
