### ISSUE TITLE
Couldn't load hooks from file

### ISSUE THREAD

**Issue by marcinZglinicki** [adnanh/webhook#260]
After run webhook server hooks are not found. 

[webhook] 2018/06/26 12:32:55 version 2.6.8 starting
[webhook] 2018/06/26 12:32:55 setting up os signal watcher
[webhook] 2018/06/26 12:32:55 attempting to load hooks from hooks.json
[webhook] 2018/06/26 12:32:55 **couldn't load hooks from file! open hooks.json: no such file or directory**
[webhook] 2018/06/26 12:32:55 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2018/06/26 12:32:55 os signal watcher ready

Could you please help me to solve this issue?

**Comment by moorereason** [comment]
Do you have a hooks.json file?  If so, where is it located on the disk in relation to webhook?  How are you executing webhook?

**Comment by marcinZglinicki** [comment]
Thanks for response! Issie is solved. I was starting the webhook server in wrong location.
