### ISSUE TITLE
Pass entire-payload to file

### ISSUE THREAD

**Issue by soufiane8096** [adnanh/webhook#265]
Hello,

I met some problem about ; double free or corruption and it was so hard to debug. So I've decide to change my way to do some work. I juste want to save the entire-payload to a file, but impossible. I have no specific logs. Here is my configuration : 
[
        {
                "id": "hook_master",
                "execute-command": "/var/scripts/redeploy_master.sh",
                "command-working-directory": "/var/myfolder/",
                "pass-arguments-to-command": [
                        {
                                "source": "entire-payload",
                                "envname":"WEBHOOK_PAYLOAD_FILE"
                        }
                ],
                 "pass-environment-to-command":[
                         {
                                "source": "entire-payload",
                                "envname": "ENV_VARIABLE",
                                "base64decode": false
                        }
                ],
                 "pass-file-to-command":[
                        {
                                "source": "entire-payload",
                                "name": "zippedBinary",
                                "envname": "ENV_VARIABLE",
                                "filename": "binaryFile.zip",
                                "base64decode": true
                        }
                ]
        },
        
        {
                "id":"healthcheck",
                "response-message":"Im fine"
        }
]

Everything seems to be fine. 
Many thanks in advance !

**Comment by scottstensland** [comment]
same json formatted

```
[
  {
    "id": "hook_master",
    "execute-command": "/var/scripts/redeploy_master.sh",
    "command-working-directory": "/var/myfolder/",
    "pass-arguments-to-command": [
      {
        "source": "entire-payload",
        "envname": "WEBHOOK_PAYLOAD_FILE"
      }
    ],
    "pass-environment-to-command": [
      {
        "source": "entire-payload",
        "envname": "ENV_VARIABLE",
        "base64decode": false
      }
    ],
    "pass-file-to-command": [
      {
        "source": "entire-payload",
        "name": "zippedBinary",
        "envname": "ENV_VARIABLE",
        "filename": "binaryFile.zip",
        "base64decode": true
      }
    ]
  },
  {
    "id": "healthcheck",
    "response-message": "Im fine"
  }
]

```

**Comment by soufiane8096** [comment]
My JSON run without any probleme when I run my webhook

**Comment by adnanh** [comment]
I'm not sure what's the problem here. What exactly is not working for you, passing file to command?
