### ISSUE TITLE
Allow Webhook Configuration File To Resolve Values From Environment Variables

### ISSUE THREAD

**Issue by eschizoid** [adnanh/webhook#270]
It would be ideal if after parsing the configuration file, environment variables can be resolved. Something like the following:

```
[
  {
    "id": "redeploy-webhook",
    "execute-command": "/home/adnan/redeploy-go-webhook.sh",
    "command-working-directory": "/home/adnan/go",
    "response-message": "Executing redeploy script",
    "trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "${ENV_SLACK_TOKEN}",
        "parameter":
        {
          "source": "payload",
          "name": "token"
        }
      }
    }
  }
]
```

Some `scala` projects such as [pureconfig](https://github.com/pureconfig/pureconfig) already do that.

**Comment by eschizoid** [comment]
```
[
  {
    "id": "redeploy-webhook",
    "execute-command": "/home/adnan/redeploy-go-webhook.sh",
    "command-working-directory": "/home/adnan/go",
    "response-message": "Executing redeploy script",
    "trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "${ENV_SLACK_TOKEN}",
        "parameter":
        {
          "source": "payload",
          "name": "token"
        }
      }
    }
  }
]
```

**Comment by scottstensland** [comment]
what I do is prior to launching just copy config file to elsewhere then issue

    sed -i -- "s|ENV_SLACK_TOKEN|${ENV_SLACK_TOKEN}|g"  $curr_file

to translate the value of env var into that string `ENV_SLACK_TOKEN` found in config file

**Comment by adnanh** [comment]
Hi, please take a look at https://github.com/adnanh/webhook/blob/master/docs/Templates.md

:-)

**Comment by eschizoid** [comment]
@adnanh Sorry, I should have done a better research :(

 @scottstensland Thanks for you answer, I think I am going to move with the OOTS seems like a _cleaner_ approach (I think you should do the same :))
