### ISSUE TITLE
Is There An OOTB Admin Page (Resource) To See Available Hooks?

### ISSUE THREAD

**Issue by eschizoid** [adnanh/webhook#271]

**Comment by adnanh** [comment]
Nope, but you can expose a hook that will execute script with
```bash
#!/bin/sh 
cat hooks.json | grep id
```
and have it return the output in the response :-)

**Comment by adnanh** [comment]
Or if you have `jq` available on your system:
```bash
#!/bin/sh
cat hooks.json | jq .[].id
```

**Comment by eschizoid** [comment]
I tried that, how would you pass the ```stdout``` to the ```response-message``` though?

**Comment by eschizoid** [comment]
found it :)

```
{
    "id": "admin",
    "execute-command": "/opt/webhook-linux-amd64/admin.sh",
    "include-command-output-in-response": true
}
```

**Comment by adnanh** [comment]
Awesome, glad it worked out for you... :-)
