### ISSUE TITLE
process stops working after reboot

### ISSUE THREAD

**Issue by markmaurerrr** [adnanh/webhook#279]
Hello,

i'm running the webhook process like this:

`nohup ~/xx/bin/webhook -hooks /xx/hooks.json -verbose -hotreload & `

And it works perfect – i absolutely love it! But for some reasons the process kills itself after a few days. It also gets killed when i restart the server.

Is there any way to force this process to be always on, even after a reload?

Thanks a lot in advance!

**Comment by adnanh** [comment]
Sounds like you should consider [running webhook as a systemd service](https://github.com/adnanh/webhook/issues/155). :-)
