### ISSUE TITLE
How to install webhook in linux alpine

### ISSUE THREAD

**Issue by nkv16786** [adnanh/webhook#284]
is there any apk package for webhook

**Comment by adnanh** [comment]
Hi, there are no official apk packages, I presume you're asking because you woulid like to run webhook in Docker? If that is the case, please check out [almir/docker-webhook](https://github.com/almir/docker-webhook)

**Comment by nkv16786** [comment]
I have a alpine container, inside that i want to install webhook. I am not able to install it directly as there are no apk package. I tried with binary distribution also but no luck
