### ISSUE TITLE
webhook parse string to json

### ISSUE THREAD

**Issue by SloanChang** [adnanh/webhook#285]
I have an app that will send the following message to webhook：
![image](https://user-images.githubusercontent.com/43361382/49138514-4b29b280-f32a-11e8-8919-c57c9c48b1a5.png)
 can see that the message field is a string in json format.The source can't make changes, is there any way to parse it?Can be quoted like this：
![image](https://user-images.githubusercontent.com/43361382/49139264-436b0d80-f32c-11e8-8066-524359c3b8e8.png)
I tried using the parse-parameters-as-json parameter,But no effect，Is there any good way?

**Comment by adnanh** [comment]
Hello, first of all the `message` field value should have escaped quotes like so `"message": "{\"id\": "1", \"data\":\"this is a test!\"|"`

To turn this string into usable JSON object, you should add parse parameters as json directive to the hook like so:
```json
"parse-parameters-as-json": [
  { "source": "payload", "name": "message.data" }
]
```

and it should work.

**Comment by SloanChang** [comment]
> Hello, first of all the `message` field value should have escaped quotes like so `"message": "{\"id\": \"1\", \"data\":\"this is a test!\"}"`
> 
> To turn this string into usable JSON object, you should add parse parameters as json directive to the hook like so:
> 
> ```json
> "parse-parameters-as-json": [
>   { "source": "payload", "name": "message" }
> ]
> ```
> 
> and it should work.

@adnanh 
I have tried it, but the result is not very good.
First of all, when I don't use the escape character, the data received by webhook is like this：

![image](https://user-images.githubusercontent.com/43361382/49555642-8be18700-f93b-11e8-8848-790bf8f9bb71.png)

When I use the escape character, the data received by webhook is like this：

![image](https://user-images.githubusercontent.com/43361382/49555663-9b60d000-f93b-11e8-936b-c80080c88f0d.png)


Webhook configuration is like this：
![a](https://user-images.githubusercontent.com/43361382/49555436-d3b3de80-f93a-11e8-86a7-06859190769e.png)


But in both ways, I finally got the same error as follows.
![b](https://user-images.githubusercontent.com/43361382/49555833-52f5e200-f93c-11e8-9020-1a626767b2d9.png)

**Comment by adnanh** [comment]
Mhm, looks like there's an unhandled case in the `GetParameter` method. I will investigate this further, and get back to you.

**Comment by dexpota** [comment]
I looked into this issue and it looks like it has been solved but I am not sure I correctly understood the issue.

The following is the configuration file where the script `hello.sh` simply echos the arguments.

```
[
  {
    "id": "webhook",
    "execute-command": "./hello.sh",
    "response-message": "I got the payload!",
    "response-headers": [
      {
        "name": "Access-Control-Allow-Origin",
        "value": "*"
      }
    ],
    "pass-arguments-to-command": [
      {
        "source": "payload",
        "name": "message.data"
      }
    ],
    "parse-parameters-as-json": [
      {
        "source": "payload",
        "name": "message"
      }
    ]
  }
]
```

This is the json sent to the webhook:

```
{
  "message": "{ \"data\": \"data data data\" }"
}
```

And the output is `data data data`.

**Comment by moorereason** [comment]
@SloanChang,
Can you verify that this issue is unresolved?
