### ISSUE TITLE
Listen on IPv6 address?

### ISSUE THREAD

**Issue by sbrl** [adnanh/webhook#287]
Hello,

I'd like to get _Webhook_ to listen on an IPv6 address, but it doesn't appear to like it. I get this if I try `::1` for testing purposes:

```
$ /usr/bin/webhook -nopanic -hooks /etc/webhook.conf -ip ::1 -port 3060 -verbose
[webhook] 2018/11/30 20:20:42 version 2.5.0 starting
[webhook] 2018/11/30 20:20:42 setting up os signal watcher
[webhook] 2018/11/30 20:20:42 attempting to load hooks from /etc/webhook.conf
[webhook] 2018/11/30 20:20:42 os signal watcher ready
[webhook] 2018/11/30 20:20:42 couldn't load hooks from file! invalid character '}' looking for beginning of object key string
[webhook] 2018/11/30 20:20:42 serving hooks on http://::1:3060/hooks/{id}
[webhook] 2018/11/30 20:20:42 listen tcp: too many colons in address ::1:3060
```

....ignore the error about loading a hooks from a file. That's an error on my end - I haven't finished writing my config file yet :P

**Comment by adnanh** [comment]
Hey, try wrapping the IP address like so `[::1]` :-)

**Comment by sbrl** [comment]
Awesome, thanks! Sometimes you need the `[]`, and sometimes you don't. It can get confusing :P
