### ISSUE TITLE
Better documentation for payload-hash-sha1 and payload-hash-sha256

### ISSUE THREAD

**Issue by computator** [adnanh/webhook#289]
None of the documentation for `payload-hash-sha1` references that it refers to a HMAC and not something else such as a plain sha1 hash. Documentation of support for `payload-hash-sha256` is also missing entirely.

Depending on the level of backwards compatibility you wish to maintain, I might suggest that `payload-hash-sha1` (and sha256) be renamed to `payload-hmac-sha1`, possibly leaving the old names as an alias for backward support.

**Comment by adnanh** [comment]
I always forget GitHub doesn't send notifications for reactions...
I completely agree with you. :+1:

**Comment by CarlosEvo** [comment]
@adnanh Wow, appreciate for the information!

**Comment by adnanh** [comment]
@CarlosEvo It's definitely an interesting topic, and can be applied in a lot of segments :-)
