### ISSUE TITLE
Whitelisting multiple IP addresses/ranges?

### ISSUE THREAD

**Issue by ChrisHardie** [adnanh/webhook#290]
BitBucket now has [quite the list of IP address ranges it says that outbound webook connections can originate from](https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html) - looks like 50 or more. I know the `ip-whitelist` rule was introduced, but it appears to support a single value, unless I'm reading the documentation and code wrong. (Even if that did support a comma separated list, it would be a bit unwieldy to maintain that many values on a single line, so an array or loading values from a file may be better.)

What would you recommend as a best practice for whitelisting multiple IP addresses/ranges for a hook configuration?

**Comment by adnanh** [comment]
For now: your best bet would be to use OR rule in combination with the ip-whitelist rule :(
As for the future improvement, there should definitely be a more compact way to specify multiple IP address ranges.

**Comment by ChrisHardie** [comment]
What do you think about a generic approach within the rule logic to have the comparison value obtained from the return result of an external script? 

That would allow us to address this case - I could write a simple cron job that fetches the latest BitBucket IP ranges and puts them in a local text file, and then just cat that file in the rule flow - but could also be useful for folks who want to dynamically handle rules based on other external inputs.

**Comment by adnanh** [comment]
Definitely an idea worth exploring!

**Comment by jpmorris** [comment]
I could be wrong, but it looks like the webhook calls only come from the 3 addresses in the expandable list in [the docs](https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html)
If I'm wrong, could we just add "bitbucket.org" to the whitelist and resolve the current IPs?

As an aside:
- It doesn't look like this merge is in the newest version, right? 
- There is a big lack of documentation.  It was hard to even find out how to use 'orrule' and I couldn't find out how to test with curl.

**Comment by moorereason** [comment]
@adnanh, isn't this issue resolved?

**Comment by adnanh** [comment]
@moorereason Yes, yes it is. I somehow missed this issue...

**Comment by chanyshev** [comment]
> Change rule to "ip-range": "{{ readFile "bitbucket_ip_list.txt" }}"
Can I specify a rule in this format ?

**Comment by moorereason** [comment]
@chanyshev,
This issue has been closed for a couple years.  Please open a new discussion or issue.
