### ISSUE TITLE
Inject html to index page?

### ISSUE THREAD

**Issue by lukasmrtvy** [adnanh/webhook#293]
Is possible to somehow inject html static conent to root (/) context ?
I would like to use something like 
```
<h1>Webhook</h1>
<h2>status:ok</h2>
```
, instead of `404 page not found`
Thanks

**Comment by adnanh** [comment]
Hi, upcoming release 2.6.10 includes a `/` healthcheck route which will return `200 OK` status, you can compile it yourself by cloning the `development` branch :-)

Current workaround to get an endpoint with described behavior is to create a hook which will invoke a script that returns desired HTML

**Comment by lukasmrtvy** [comment]
Thanks

Workaround can be done only if I am not using -urlprefix , right ? (If its even possible)
Or can I overide -urlprefix in hooks.json ?

**Comment by adnanh** [comment]
Ugh, didn't see the reply, sorry for the late response.

Yes, you are correct, you can't trigger a hook with an empty name.

**Comment by mterron** [comment]
Any idea when 2.6.10 is going to be released?

**Comment by adnanh** [comment]
@mterron I'll compile it and release it Wednesday night

**Comment by adnanh** [comment]
@mterron done
