### ISSUE TITLE
Webhook does not execute my .sh file

### ISSUE THREAD

**Issue by dmnktoe** [adnanh/webhook#300]
I installed the webhook server and configured it the proper way I think - Github gives me a 200 response, the webhook-url is accessible and another execution is already working. I also ran the .sh file by itself via CLI - also works.

Link to webhook: [https://webhooks.dmnktoe.de/hooks/pull-dmnktoe](https://webhooks.dmnktoe.de/hooks/pull-dmnktoe)

But how can I debug why the webhook server doesn't execute my .sh-file after a successful commit?

```
{
    "id": "pull-dmnktoe",
    "execute-command": "/var/www/html/webhooks/commands/pull-dmnktoe-de.sh",
    "command-working-directory": "/var/www/html/dmnktoe-de-webhooks/webhook",
    "trigger-rule": {
      "and": [{
        "match": {
          "type": "payload-hash-sha1",
          "secret": "Hannes1996elmo!",
          "parameter": {
            "source": "header",
            "name": "X-Hub-Signature"
          }
        }
      }]
    }
  },
```

pull-dmnktoe-de.sh:

```
#! /bin/bash
cd /var/www/html/dmnktoe-de/$1
git stash
git pull
gulp serve:dist
```

Update, there's an error in the nginx error log:
`2019/01/25 15:17:33 [error] 12297#12297: *4771 connect() failed (111: Connection refused) while connecting to upstream, client: 91.42.172.89, server: webhooks.dmnktoe.de, request: "GET /hooks/pull-dmnktoe HTTP/1.1", upstream: "http://127.0.0.1:9001/hooks/pull-dmnktoe", host: "webhooks.dmnktoe.de"`

Can you help? 😬

**Comment by adnanh** [comment]
Hi, the nginx error indicates that the webhook is not running on the port 9001. Did you forget `-port 9001` flag while starting webhook, or did you misconfigure nginx upstream to the wrong port?

**Comment by adnanh** [comment]
@dmnktoe any update on this one?

**Comment by dmnktoe** [comment]
Ohh, sorry for my late reply but this can be closed. I made a mistake in my configuration at some point. 👍
