### ISSUE TITLE
Provide current webhook version for debian apt install

### ISSUE THREAD

**Issue by col-panic** [adnanh/webhook#301]
What is the reason, that default debian sid still provides the old 2.5.0 version? I'd really like to have a newer version that simply installed :)

**Comment by moorereason** [comment]
You should ask the maintainers of the Debian package.

**Comment by adnanh** [comment]
@freeekanayaka

**Comment by freeekanayaka** [comment]
Good call, I haven't been updating the package in a while. I'll do that shortly.

**Comment by adnanh** [comment]
@freeekanayaka <3

**Comment by freeekanayaka** [comment]
[Done](https://packages.debian.org/sid/webhook)!

**Comment by col-panic** [comment]
Sweeet! :)
