### ISSUE TITLE
access source ip address

### ISSUE THREAD

**Issue by adamaze** [adnanh/webhook#312]
I was hoping to be able to pass the source IP along to the script, but i couldn't find a way to access it through the [request-values](https://github.com/adnanh/webhook/blob/master/docs/Referencing-Request-Values.md) section
Am I missing something? Or is my only real option to parse the stdout of webhook and attempt to grab the last line with "incoming HTTP request from" (if that would even work...)

any pointers would be greatly appreciated!

**Comment by adnanh** [comment]
Hey, sorry for the late reply. So far there isn't support in webhook for fetching the source IP but it's on the roadmap and should be included in the next version.

Current workaround is to put nginx in front of webhook and have it pass the source IP via X-Forwarded-For header, which you can then read using the webhook.

**Comment by adamaze** [comment]
Cool. Thanks for the response. It is good to know that it is on the roadmap. Feel free to close this if you like

**Comment by adnanh** [comment]
I'll close it once the feature lands in the development branch :-)

**Comment by adnanh** [comment]
Tagging this with #356 as it should provide a powerful mechanism to craft a solution to this problem.

**Comment by moorereason** [comment]
If we include this in webhook, here's a proposed usage:

```
{
  "source": "request",
  "name": "remote-addr"
}
```

Potentially relevant `name` values from [http.Request](https://golang.org/pkg/net/http/#Request): `method` and `remote-addr`.

**Comment by Emremir10** [comment]
> If we include this in webhook, here's a proposed usage:
> 
> ```
> {
>   "source": "request",
>   "name": "remote-addr"
> }
> ```
> 
> Potentially relevant `name` values from [http.Request](https://golang.org/pkg/net/http/#Request): `method` and `remote-addr`.

Is this still working? As I am getting the following error message:

`[webhook] 2023/05/10 16:38:16 [0f27d9] error extracting command arguments: couldn't retrieve argument for {Source:request Name:remote-addr EnvName: Base64Decode:false}
`
