### ISSUE TITLE
Match Hook-Rule Question

### ISSUE THREAD

**Issue by alexthecamel** [adnanh/webhook#317]
Hi,
Apologies for the beginners question. Relatively new to Linux. 

Got Webhooks up and running and have configured to my liking.
It seems someone has edited the Hook-Rules.md doc, but last time I looked it stated not to use the Match rule in production as it was insecure (or words to that effect). I note that has been removed, or at least edited.
Was that because there is an inherent weakness in using the Match rule as an authentication method, or just that in the original example the value to Match was "42" which is obviously easily guessable?

I have Webhooks setup using HTTPS so just Matching a value feels sufficient?

Many Thanks

**Comment by adnanh** [comment]
Hey,
there is no inherent weakness in the Match rule, it's just that you are relying on the fact that only you know the value you are using for the authentication, also known as security through obscurity :-)
