### ISSUE TITLE
same url for multiple payloads?

### ISSUE THREAD

**Issue by rasputnik** [adnanh/webhook#32]
Hi, this looks really promising, thanks!

Is there a way to have a single id filter based on payload? I may have misread the docs
but it seems like each endpoint can have multiple filters but I can't expose multiple commands
via a single id (so it's not possible to put several commands at one web hook URL).

I'm hoping to use this with marathon, so can specify a single URL for all web hooks

(specced here for reference: https://mesosphere.github.io/marathon/docs/event-bus.html )

There are about a dozen different payloads sent to that URL and I'd like to ignore some,
and run different commands based on the payload fields.

**Comment by adnanh** [comment]
It's possible to do it with the current version, but it would be ugly. Your script would have to receive all possible arguments and would then have to enumerate through them and decide what to do.

I will add a support to define hooks with the same id, and the webhook will execute the first one that satisfies all the trigger rules. I believe this would solve your problem, it would allow you to define specific rules and commands for your hooks.

Other thing that I'm going to implement is to allow webhook to pass whole payload or a subset of it as a JSON string to the command. This would make the current working solution (workaround) to your problem at least a bit prettier.

**Comment by rasputnik** [comment]
Thanks, that sounds like it'd do the trick. And +1 for passing json body to the script (via stdin i guess) - default to that and allow a jq type filter to bring in a subset, right?
