### ISSUE TITLE
Use request value as a part of command argument

### ISSUE THREAD

**Issue by jack1142** [adnanh/webhook#324]
It would be nice to be able to put some value from request as part of command argument. To keep it simple, let's assume this is a part of payload:
```json
{
  "part_of_directory": "foo/bar"
}
```
and we want to use the `part_of_directory` as part of the string argument:
```json
{
  {
    "execute-command": "/bin/ls",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "/home/ubuntu/{{part_of_directory}}/blah"
      }
    ]
  }
}
```
From what I know, this can't be currently done. I also tried putting `part_of_directory` in environment variable using `pass-environment-to-command` and use `/home/ubuntu/$HOOK_PART_OF_DIRECTORY/blah` as string argument, but that didn't work either.

**Comment by adnanh** [comment]
The workaround for this would be to write a wrapper script which would receive the "part_of_directory" value from payload, and then construct and run the actual command like you described.

**Comment by jack1142** [comment]
That's what I'm doing now, I just think it would be a great addition.
