### ISSUE TITLE
Add sha512 payload check

### ISSUE THREAD

**Issue by AndrewSav** [adnanh/webhook#329]
Hello,

could you please add sha512 payload check.

Thank you in advance!

**Comment by AndrewSav** [comment]
I was looking if I can impliment it in a hook script, but it appears that webhook mangles the payload before passing it script, (that is put it through json serializer / deserializer that removes all formatting) so one cannot do that on the script level either.

This is a separate request, but it would be nice, if we could get _unmodifed_ payload to the hook script.

A live example using inconfigurable sha 512 mac is [netbox](https://netbox.readthedocs.io/en/stable/additional-features/webhooks/)

**Comment by AndrewSav** [comment]
@moorereason, ok: https://github.com/adnanh/webhook/issues/330

**Comment by adnanh** [comment]
Will be released with 2.6.11 next week.

**Comment by adnanh** [comment]
Released :-)
