### ISSUE TITLE
getenv function prevents the hooks.json file from being parsed

### ISSUE THREAD

**Issue by otmos** [adnanh/webhook#334]
Good Morning / Evening,

I'm having a strange issue where a sample code involving getting an environnement variable isn't working and throwing a YAML to JSON parsing error as you can see in the screenshot below.

Thank you very much for your assistance

![Screenshot from 2019-08-30 14-59-51](https://user-images.githubusercontent.com/43470049/64026651-15269280-cb37-11e9-83cd-ee36d609f248.png)

**Comment by moorereason** [comment]
It looks like you may be missing the `-template` command-line option, so webhook tries to read the config as JSON (which fails parsing due to the mismatched double-quotes) then as YAML (which it's clearly not) and finally yields an somewhat-unexpected YAML to JSON error.

**Comment by otmos** [comment]
Thank You so much , i spent quite the time re reading the documentation and i understood that i need the -template flag to parse and use the getenv function , thank you so much for the detailed explanation
