### ISSUE TITLE
Mailgun error parsing form payload invalid URL escape "%\xf3\xdb"

### ISSUE THREAD

**Issue by sfxworks** [adnanh/webhook#335]
Hiya!
Love this! I wanted to get mailgun to work with my zammad server, but running into an issue.

When sending a sample post from mailgun.com to webhook, I get the following error:
```
[webhook] 2019/09/04 23:11:07 [07d321] incoming HTTP request from 172.69.34.21:33718
[webhook] 2019/09/04 23:11:07 [07d321] mailgun-to-zammad got matched
[webhook] 2019/09/04 23:11:07 [07d321] error parsing form payload invalid URL escape "%\xf3\xdb"
[webhook] 2019/09/04 23:11:07 [07d321] mailgun-to-zammad hook triggered successfully
```
This may also be related to https://github.com/adnanh/webhook/issues/311#issuecomment-479556064 and mailgun is likely sending a fake attachment here, I just wanted to submit this issue for tracking/for anyone else experiencing this issue until webhook supports multi-part messages.

**Comment by adnanh** [comment]
For now #360 should make it a bit more clear in logs what's really going on. And #356 should provide a temporary workaround mechanism. But the real implementation is proper multipart form handling.

**Comment by moorereason** [comment]
We added multipart form data handling in v2.7.0.  @sfxworks, are you able to test your use case again to see if this is resolved?

**Comment by sfxworks** [comment]
Perfect timing! Sure, start testing this today.

**Comment by moorereason** [comment]
@sfxworks, anything to report?

**Comment by moorereason** [comment]
This should be resolved.
