### ISSUE TITLE
Permission Denied error when running su -c command

### ISSUE THREAD

**Issue by ProggerPete** [adnanh/webhook#340]
I've got a hook that looks like this:

```
  {
    "id": "test",
    "execute-command": "/bin/su",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "gitbot"
      },
      {
        "source": "string",
        "name": "-c"
      },
      {
        "source": "string",
        "name": "'~/typeit/updateAndRedeploy.sh'"
      }
    ]
  }
```

When the hook is executed I get this error:

> [webhook] 2019/09/19 13:13:05 [5e3873] executing /bin/su (/bin/su) with arguments ["/bin/su" "gitbot" "-c" "'~/typeit/updateAndRedeploy.sh'"] and environment [] using  as cwd
> [webhook] 2019/09/19 13:13:05 [5e3873] command output: bash: ~/typeit/updateAndRedeploy.sh: Permission denied
> 
> [webhook] 2019/09/19 13:13:05 [5e3873] error occurred: exit status 126
> [webhook] 2019/09/19 13:13:05 [5e3873] finished handling test

However I'm able to execute this command when running as root:

>  su gitbot -c '~/typeit/updateAndRedeploy.sh'

How can I execute the command successfully via a hook?

**Comment by moorereason** [comment]
I doubt this is an issue with `webhook`, but... What user is webhook running as?  What are the permissions on `~/typeit/updateAndRedeploy.sh`?

**Comment by ProggerPete** [comment]
webhook is running as root.

> root      9543  1714  0 13:20 pts/0    00:00:00 webhook -hooks /etc/webhook/hoo s.json -verbose

the script file is executable by all

> -rwxrwxr-x 1 gitbot gitbot   67 Sep 19 12:47 updateAndRedeploy.sh

**Comment by moorereason** [comment]
Try prepending the command parameter with bash (ie. `-c '/usr/bin/bash /home/gitbot/typeit/...'`).  I'm also a fan of using absolute paths instead of the tilde.

**Comment by ProggerPete** [comment]
Removing the tilde seems to have helped and I can now run the command.  However I need to change the working directory and my attempt at doing so breaks things again.

From the command line this works:

su gitbot -c 'cd /home/gitbot/typeit ; /home/gitbot/typeit/updateAndRedeploy.sh'

However prepending the change directory command:

```
{
    "id": "test",
    "execute-command": "/bin/su",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "gitbot"
      },
      {
        "source": "string",
        "name": "-c"
      },
      {
        "source": "string",
        "name": "'cd /home/gitbot/typeit ; /home/gitbot/typeit/updateAndRedeplo$
      }
    ]
  }
```

Results in permission denied again.

> [webhook] 2019/09/19 14:24:48 [9a5d0f] executing /bin/su (/bin/su) with arguments ["/bin/su" "gitbot" "-c" "'cd /home/gitbot/typeit ; /home/gitbot/typeit/updateAndRedeploy.sh'"] and environment [] using  as cwd
> [webhook] 2019/09/19 14:24:48 [9a5d0f] command output: bash: cd /home/gitbot/typeit ; /home/gitbot/typeit/updateAndRedeploy.sh: Permission denied

**Comment by ProggerPete** [comment]
I've worked around my latest issue by modifying the updateAndRedeploy script to deal with running from any path.

Thanks very much for your help.
