### ISSUE TITLE
Grafana Webhook - Output for a batch

### ISSUE THREAD

**Issue by sralus** [adnanh/webhook#347]
Hi
I would like to use the webhook service from Grafana.
Then the issue is local to my Rasperry Pi run.
As a URL I have "http: // localhost: 9000 / hooks / redeploy-webhook" registered in grafana.
When I send test I get in the terminal:

[webhook] 2019/09/26 21:30:36 version 2.6.9 starting
[webhook] 2019/09/26 21:30:36 setting up os signal watcher
[webhook] 2019/09/26 21:30:36 attempting to load hooks from hooks.json
[webhook] 2019/09/26 21:30:36 os signal watcher ready
[webhook] 2019/09/26 21:30:36 found 1 hook (s) in file
[webhook] 2019/09/26 21:30:36 loaded: webhook
serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2019/09/26 21:39:45 Started PUT / hooks / redeploy-webhook
[webhook] 2019/09/26 21:39:45 [1d6dab] incoming HTTP request from 127.0.0.1:42462
[webhook] 2019/09/26 21:39:45 Completed 404 Not Found in 351.98μs

Sorry I do not know where I have to adjust something so I can see the issue.

On the webside http://192.168.0.69:9000/hooks/redeploy-webhook comes only the message: Hook not found.

Can someone tell me what to do?
Best regards
Sralus

**Comment by adnanh** [comment]
Looks like your hook name is `webhook` and not `redeploy-webhook` :-)

**Comment by sralus** [comment]
Thank you for your answer.
Unfortunately, I am a beginner what Webhook is concerned.

So my idea is that I want to use the Webhook service from Grafana.
In Grafana Values are written by InfluxDB.
Now I want to do an alert in grafana then via webhook locally a bash command to switch a GPIO.

Maybe you have an idea for me as I can implement that.
Best regards
Sralus
