### ISSUE TITLE
Running webhook inside docker container can't find command working directory

### ISSUE THREAD

**Issue by Tunjidir** [adnanh/webhook#359]
Running webhook inside a docker container with the following Dockerfile
```
FROM almir/webhook
RUN mkdir -p /var/scripts
WORKDIR /var/scripts

COPY ["update.sh", "hooks.json", "/var/scripts/"]
RUN chmod +x /var/scripts/update.sh
CMD ["-verbose", "-hotreload"]
```
here is a copy of my hooks.json

```
[
    {
      "id": "update-hook",
      "execute-command": "/var/scripts/update.sh",
      "command-working-directory": "/home/olatunji/Documents/workspaces/folder/",
      "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "olatunji.oniyide@mail.com"
      }
    ]
     }
  ]
```

and this is the output of my docker logs container-name

```
[webhook] 2019/12/02 10:35:01 version 2.6.10 starting
[webhook] 2019/12/02 10:35:01 setting up os signal watcher
[webhook] 2019/12/02 10:35:01 attempting to load hooks from hooks.json
[webhook] 2019/12/02 10:35:01 os signal watcher ready
[webhook] 2019/12/02 10:35:01 found 1 hook(s) in file
[webhook] 2019/12/02 10:35:01 	loaded: update-hook
[webhook] 2019/12/02 10:35:01 setting up file watcher for hooks.json
[webhook] 2019/12/02 10:35:01 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2019/12/02 10:35:15 [a5a168] incoming HTTP request from 172.17.0.1:54662
[webhook] 2019/12/02 10:35:15 [a5a168] update-hook got matched
[webhook] 2019/12/02 10:35:15 [a5a168] update-hook hook triggered successfully
[webhook] 2019/12/02 10:35:15 200 | 140.758µs | localhost:9000 | GET /hooks/update-hook 
[webhook] 2019/12/02 10:35:15 [a5a168] error extracting command arguments: couldn't retrieve argument for {Source:payload Name:olatunji.oniyide@mail.com EnvName: Base64Decode:false}
[webhook] 2019/12/02 10:35:15 [a5a168] executing /var/scripts/update.sh (/var/scripts/update.sh) with arguments ["/var/scripts/update.sh" ""] and environment [] using /home/olatunji/Documents/workspaces/folder/ as cwd
[webhook] 2019/12/02 10:35:15 [a5a168] command output: 
[webhook] 2019/12/02 10:35:15 [a5a168] error occurred: chdir /home/olatunji/Documents/workspaces/folder: no such file or directory
[webhook] 2019/12/02 10:35:15 [a5a168] finished handling update-hook

```

steps to reproduce: 
Run webhook inside a docker container. using: https://github.com/adnanh/webhook-contrib/tree/master/docker

am i supposed to mount the command working directory as a path in the docker file? please help. Thanks.

**Comment by adnanh** [comment]
What does your incoming payload look like?


This definition:
```
{
  "source": "payload",
   "name": "olatunji.oniyide@mail.com"
}
```
essentially looks for a key named 'olatunji.oniyide@mail.com' in your payload which is probably not what you wanted. :-)

**Comment by Tunjidir** [comment]
Oh? Okay going to remove that from the hooks.json file. Thanks for the quick response. Please any idea how to make the folder path accessible inside of docker? do i pass it as a volume? Thanks...

**Comment by Tunjidir** [comment]
I've been able to make the folder accessible in docker by mounting it as a volume, but i still get this. error. 
`[webhook] 2019/12/02 11:28:07 [382dda] command output: /var/scripts/update.sh: line 2: git: not found`
any help will be appreciated. 

this is just the content of my update.sh script: 

```
#!/bin/sh
git reset --hard && git pull
```

**Comment by adnanh** [comment]
Make sure you have git available in docker

**Comment by Tunjidir** [comment]
If i have git installed already on the server. do you mean i should also have git installed on docker?

**Comment by Tunjidir** [comment]
Please i have tried everything possible to get git to run in a container if i'm following what you said currently, apparently i can't find any way to go about this, perhaps, any help you could offer would be appreciated. Thanks.

**Comment by adnanh** [comment]
@almir could you share a tip or two on how to get git running inside the docker?

**Comment by moorereason** [comment]
@Tunjidir,
This is more of a Docker issue than a Webhook issue.  `/home/olatunji/Documents/workspaces/folder` is not in the container.

Either remove `command-working-directory` from your webhook config or [read this](https://stackoverflow.com/a/23455537/4236609) for hints on how to use Docker.

**Comment by adnanh** [comment]
On the other hand, what is the problem you are trying to solve? Do you really need webhook running inside docker? Can it run on the host?

**Comment by Tunjidir** [comment]
I mounted the working directory as a volume when running the docker container, apparently the issue i happen to be having right now, involves the webhook being unable to execute the `git` command specified in the update.sh i am passing. fails with this error. 

```
[webhook] 2019/12/02 13:50:20 [5cf041] command output: /var/scripts/update.sh: line 2: git: not found

[webhook] 2019/12/02 13:50:20 [5cf041] error occurred: exit status 127

```

**Comment by Tunjidir** [comment]
> On the other hand, what is the problem you are trying to solve? Do you really need webhook running inside docker? Can it run on the host?

oh, the webhook is supposed to trigger the git command on the server repo, and we are already running docker on the server, i just felt it'd be better to run it inside a container since we have docker installed on the server, apparently i can't get it to work. will resolve to running it bare metal if  i can't fix this by the end of the day.

**Comment by moorereason** [comment]
@Tunjidir,
The Docker image you're using doesn't ship with `git` installed.  Use something like this in your Dockerfile:

```
RUN         apk add --update -t git
```

**Comment by Tunjidir** [comment]
added this line built to the dockerfile, built the docker image, ran it and still the same error. Thanks anyway. @moorereason

**Comment by Tunjidir** [comment]
@moorereason  it worked after i removed the --update -t flag from the RUN command. Thanks. closing this issue now.

**Comment by adnanh** [comment]
:+1:
