### ISSUE TITLE
[Suggestion] Fail immediately if no hooks file found and hotreload is false

### ISSUE THREAD

**Issue by ciarand** [adnanh/webhook#36]
Current  behavior in verbose mode:
```
λ webhook.exe -verbose 
[webhook] 2015/07/22 22:01:25 version 2.3.4 starting                                                            
[webhook] 2015/07/22 22:01:25 attempting to load hooks from hooks.json                                          
[webhook] 2015/07/22 22:01:25 couldn't load hooks from file! open hooks.json: The system cannot find the file specified.                                                                                                            
[webhook] 2015/07/22 22:01:25 starting insecure (http) webhook on :9000
```
Without the `-verbose` flag the program silently fails to find the `hooks.json` file (expectedly), but doesn't tell the user that. I think it would be helpful to fail immediately if no hooks file is found (and assuming `-hotreload` is false). What are your thoughts?

**Comment by adnanh** [comment]
I was thinking of having verbose output set to on by default, and have a separate switch for silent mode for those that do not want the output.

**Comment by ciarand** [comment]
:+1:

**Comment by adnanh** [comment]
Decided to use your approach. The webhook 2.3.5 will now fail under those conditions, unless you provide a -nopanic flag to it.
