### ISSUE TITLE
Rework middleware with gorilla

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#374]
I was looking at updating `negroni`, but eventually decided to just dump it.  Since webhook was originally released, `gorilla/mux` has added middleware support.  Therefore, I propose that we use `gorilla/mux` for routing and middleware.

I also looked at several other routers, but I think `gorilla/mux` is good enough for us and will make for a smaller PR.

I have a [working feature branch](https://github.com/moorereason/webhook/tree/feature/gorilla-only) that implements this proposal and also adds some additional, internal middleware:

- Request ID generation is moved to middleware.
- Request ID middleware can use `X-Request-ID` header if webhook is behind a proxy (enabled with cli option).
- New Logger middleware customized to match our existing logging format (mostly, I also output the size of the response).
- New Dumper middleware for dumping request and response header/body.  Implemented behind a debug cli option.  Very handy.

Thoughts?

**Comment by adnanh** [comment]
Sounds good, I chose negroni simply because it was the hot thing back then and had everything I needed for the prototype. :-)

**Comment by adnanh** [comment]
Fixed in #375
