### ISSUE TITLE
SystemD not executing shell script

### ISSUE THREAD

**Issue by ralphotowo** [adnanh/webhook#377]
Hi, 

Great solution. I'm trying to use webhook and I'm unable to get systemd to execute my shell script. It only works when I start webhook from the command line. 

**/etc/webhook.conf**
```
[
  {
    "id": "app-api",
    "execute-command": "/srv/scripts/webhooks/git_webhook.sh",
    "command-working-directory": "/var/www/api.domain.com",
    "response-message": "Executing deployment script"
  }
]
```
**/srv/scripts/webhooks/git_webhook.sh**
```
#!/usr/bin/env bash

# Redirect stdout/stderr to a file
DS=`date +%Y-%m-%d`; mkdir -p /var/log/webhook/$DS/
exec > /var/log/webhook/$DS/webhook_output.log 2>&1

# Locate and assign git binary.
git=$(which git)
app_path=/var/www/api.domain.com/

cd $app_path && $git fetch && $git pull

# Restart PM2 webserver
/usr/bin/pm2 restart all
```
When I execute the following, the script runs and everything works:
`/usr/bin/webhook -nopanic -hooks /etc/webhook.conf -verbose`

When I start webhook "systemctl start webhook" which runs the same command above without the -verbose flag, I get the return message but my shell script isn't executed at all.

Any help is appreciated.

**Comment by moorereason** [comment]
Please share your systemd service definition file for webhook.

**Comment by ralphotowo** [comment]
@moorereason Thank you for responding.

**/lib/systemd/system/webhook.service**

```
[Unit]
Description=Small server for creating HTTP endpoints (hooks)
Documentation=https://github.com/adnanh/webhook/

[Service]
ExecStart=/usr/bin/webhook -nopanic -hooks /etc/webhook.conf -verbose

[Install]
WantedBy=multi-user.target
```

**Comment by moorereason** [comment]
I'm assuming this is a permissions issue.  I use the following directives to have the process run as the user+group that I want:

```ini
[Service]
User=webhook
Group=webhook
```

**Comment by ralphotowo** [comment]
I updated it as follows, same issue: 

```
[Unit]
Description=Small server for creating HTTP endpoints (hooks)
Documentation=https://github.com/adnanh/webhook/

[Service]
ExecStart=/usr/bin/webhook -nopanic -hooks /etc/webhook.conf -verbose

[Install]
WantedBy=multi-user.target
```

**Comment by ralphotowo** [comment]
This is now fixed. I updated /etc/webhook.conf as follows
