### ISSUE TITLE
Questions regarding a shared hosting environment

### ISSUE THREAD

**Issue by JacobDB** [adnanh/webhook#382]
At the company where I work, we maintain our own Linux servers for a number of clients &ndash; several hundred across multiple servers. We currently use FTP to upload changes to sites, but I've long wanted to change this to a more modern workflow.

I found your project today, and did some local testing &ndash; it seems really powerful and like it'll fit our needs perfectly, but I had a few questions about how this would work for a shared hosting environment like ours.

Let's say I have 50 websites on a server, each with its own account and domains. I want to set up deployment scripts for each of the 50 sites individually, so that each webhook can be triggered independent of each other.

- To accomplish this, would I need to set up a unified configuration that contains objects like `deploy-site1`, `deploy-site2`, and so on, or could I set up a configuration on each account individually?
- If unique configurations can be set up for each account, would one instance of webhook need to be running for each account, or would one service be able to combine all configurations?
- Would each configuration only be accessible from its own domain, or would there be a single unified "hooks" URL that would allow access to all hooks on the server?
 
Please forgive me if these are ignorant questions, this is a rather new concept to me and I'm not directly involved with server management so I'm not sure how this sort of thing typically works.

**Comment by moorereason** [comment]
Lot of questions and unknown details about your environment, so I'll outline some guidelines:

1. A single instance of `webhook` can serve many hooks.
1. `webhook` is pretty lean, so if you needed to run an instance per site, it would probably be fine from a resource standpoint.
1. The hook definitions can be in multiple files (with multiple `-hooks` options).<sup>1</sup>
1. I don't know where your webhooks would be coming from, but if you'll be accepting requests from the public internet, I would recommend putting `webhook` behind a proxy (such as nginx or whatever is already running on the web server).

As a sysadmin, I would recommend talking to your server management team soon.  :smile:

<sup>1</sup> We should probably support a `hooks.d`-style directory.  Hmm...
