### ISSUE TITLE
webhook as a service - not executing associated script

### ISSUE THREAD

**Issue by stlbucket** [adnanh/webhook#390]
i've got my /etc/webhook.conf file set up:
```
[
  {
    "id": "dev-deploy-ui",
    "execute-command": "/var/www/myapp/scripts/deploy-ui.sh",
    "command-working-directory": "/var/www/myapp/scripts",
    "response-message": "initiated ui deployment"
  }
]
```
if i run webhook as a sudo user from the command line:
```
webhook --hooks /etc/webhook.conf --verbose &
```
everything works fine.  but if i run as a service:
```
sudo systemctl start webhook
```
then the hook actually fires.   however, the deploy-ui.sh script does not run.
myapp and lower directories are owned by my sudo user, not root.  could this be the issue?

**Comment by stlbucket** [comment]
output from systemctl status
```
Jan 11 01:36:37 dev-ctl-dev-1 webhook[8200]: [webhook] 2020/01/11 01:36:37 Started GET /hooks/dev-deploy-ui
Jan 11 01:36:37 dev-ctl-dev-1 webhook[8200]: [webhook] 2020/01/11 01:36:37 Completed 200 OK in 1.162059ms
```

**Comment by stlbucket** [comment]
this looks to be a duplicate of https://github.com/adnanh/webhook/issues/377 but i can't seem to implement the same fix.

my deploy script looks like:

```
#!/bin/sh

cd /var/www/myapprootdir/ui
git pull origin master
#rm -rf node_modules
cp /var/www/myapprootdir/scripts/index.html.building /var/www/myapprootdir/dist/ui/index.html
rm -rf node_modules
npm install
npm run build
rm -rf /var/www/myapprootdir/dist/ui
cp -R /var/www/myapprootdir/ui/dist /var/www/myapprootdir/dist/ui
```
and my service definition file:
```
[Unit]
Description=Small server for creating HTTP endpoints (hooks)
Documentation=https://github.com/adnanh/webhook/

[Service]
ExecStart=/usr/bin/webhook -nopanic -hooks /etc/webhook.conf --verbose
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

**Comment by moorereason** [comment]
> [Service]
> ExecStart=/usr/bin/webhook -nopanic -hooks /etc/webhook.conf --verbose

Is `--verbose` a typo?  The option is `-verbose`.

What version of webhook are you running?

**Comment by stlbucket** [comment]
yes - typo.  i fixed it with no difference in results.

webhook/bionic,now 2.5.0-2 amd64 [installed] - is my version

installed via apt

**Comment by stlbucket** [comment]
i built and installed from github.   this seems to have fixed my issue

webhook version 2.6.11
