### ISSUE TITLE
Custom Favicon possible?

### ISSUE THREAD

**Issue by ITCMD** [adnanh/webhook#401]
I was wondering if it would be possible to add a custom favicon / website ico to the program?

**Comment by adnanh** [comment]
Hey, thanks for opening an issue.
At the moment, it's not possible without modifying the code and compiling your own version. 

We didn't put any effort on allowing such customizations because the scope of the webhook as a tool is mainly aimed towards the automation pipelines, which means that it's mostly invoked by computers and not humans.

Could you tell us more about your use-case for this feature?

Thanks in advance!

**Comment by ITCMD** [comment]
Hi adnanh! Sorry for the late reply! I've been using the webhook tool to launch games and programs on my computer. Then, I like to save the links to them to the home screen on my phone. When I do this they have the ugly white icon instead of something customizable.

**Comment by adnanh** [comment]
@ITCMD Sorry for the late reply as well :-( Anyway, one way of doing it would be using `response-message` field to return the valid HTML using the base64 encoded data url favicon like this:
```
"response-message": "<html><head><title>Favicon example</title><link href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAACbUlEQVRIx7WUsU/qUBTGv96WSlWeEBZijJggxrREdwYixMnByYEyOvgfsBAMG0xuDsZ/QGc3NDFhgTioiYsmkhBYGLSBkLYR0va8gSjvQXiIT7/l5ibfOd/v3pN7gSmVSMTj8ThRfzdYk8lkMpl83/+AVFVVVXU0eHiVJEmSpB8DIcpkMplsdhCYz+fzhQJROBwOh8PDQN+oQCAQCASIRFEURZHI45GkP0/e7Xa73e70AMJnjel0Op1OA6oaDB4eAkAw6PcDvZ5t6zrw/Hx2trAw/cHYZ426ruu6DtzcGEYuBzQa19etFvD4WKtls4AoRqMPDwBjjLGPrt84ilgsFovF6EOapmmaRiP6O/jbAIguL4vFYpHGqlKpVCoVomq1Wq1Wibxer9fn+w+Q9+cUiUQikQhNrfdgWZZlWf4yyGhj27Zt254MUK/X6/X6F0aiKIqiKIOCYRmGYRjGZADLsizLIgqFQqHV1SkAnp5OTn79ItK0qyuPZ7SxaZqmaU4GKJfPzxmbfAPc/f3pqaIQLS8vLtZqgOP0bYyJoiAARC5Xrwf4/Vtbb2+Th1YqlUqlErC01GgkEkCz2WxyHLC+LsuiCAiCJLlcgM+3vd3pcBzXaJTLR0dEs7Ptdv+D4TiOG/A6DsBxQKvV621sAGtru7vl8ngAjuvXv7xcXIgiwNjMjCj2h+k4fQfPA4LA8xwHCO323V2hABiG223bwPy8xwMAbvfcHGMAY32j47y+3t4OAsZpZ2dzEwAsy7IcBxAExhwHMIxOx3GAlZVUyjT/1WFIudzenstFlEpFo9M8o+Pj/X2eJzo4SCR4fnzdb2N4Pyv9cduVAAAAAElFTkSuQmCC\" rel=\"icon\" type=\"image/x-icon\" /></head><body></body>"
```

Would that work for you? If you're unsure how to get the base64 encoded blob, you could use tool such as [this](https://ezgif.com/image-to-datauri)
