### ISSUE TITLE
Binary file cannot run in Alpine

### ISSUE THREAD

**Issue by sagerenn** [adnanh/webhook#402]
[The glibc (webhook requires?) programs cannot run in Alpine Linux.](https://wiki.alpinelinux.org/wiki/Running_glibc_programs). 

I have to do additional steps to make sure the glibc is available in Alpine.

```
apk --no-cache add ca-certificates wget
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
apk add glibc-2.28-r0.apk
```
See detail: https://stackoverflow.com/questions/37818831/is-there-a-best-practice-on-setting-up-glibc-on-docker-alpine-linux-base-image

Is there a way to solve the problem when building the binary file?

**Comment by moorereason** [comment]
You need to build a static binary or build it inside of an Alpine container.  The internet can help with that, but try this for a static binary:

```
CGO_ENABLED=0 go build -a -ldflags="-s -w" -installsuffix cgo
```
To see if the binary is static or dynamically linked, use `ldd`.
