### ISSUE TITLE
Webhook started, but timeout/can't connect

### ISSUE THREAD

**Issue by EmmanuelBeziat** [adnanh/webhook#405]
Hi there,

I try to set my server to use webhook, Followed the steps described [here](https://willbrowning.me/setting-up-automatic-deployment-and-builds-using-webhooks/), but somehow I can't manage to access to :9000.

## Steps

I launch my command:
```bash
/root/go/bin/webhook -hooks /usr/share/hooks/hooks.json -ip "xx.xx.xx.xx" -verbose
```

Here’s the output:

```bash
[webhook] 2020/03/31 13:00:36 version 2.6.11 starting
[webhook] 2020/03/31 13:00:36 setting up os signal watcher
[webhook] 2020/03/31 13:00:36 attempting to load hooks from /usr/share/hooks/hooks.json
[webhook] 2020/03/31 13:00:36 found 1 hook(s) in file
[webhook] 2020/03/31 13:00:36   loaded: deploy-mysite
[webhook] 2020/03/31 13:00:36 serving hooks on http://xx.xx.xx.xx:9000/hooks/{id}
```

Default port is open:
```
bash
webhook   32663     root    3u  IPv4 83405246      0t0  TCP xx.xx.xx.xx:9000 (LISTEN)
```

So I go to `http://xx.xx.xx.xx:9000/hooks/deploy-mysite`, and as described in the article I followed, it should return "Hook rules were not satisfied"; instead, I got the generic "timeout" browser error page. But it’s not an issue with the IP itself, it's working whenever I try to access the ip without specified port.

Knowing that wouldn't work, I kept going to the full Github hook integration. As I expected, when I did push from my local repo to github, the webhooks shows that the last delivery failed, because it failed to connect.

The console isn't showing anything more, it's still running and waiting.

Not sure what I missed. This may be a server configuration issue rather than webhook, but I haven’t got any access problem with others entry path (nginx, apache and node are running well through a whole bunch of ports).

If anyone have a clue from where to search? Thanks.

**Comment by moorereason** [comment]
Check the firewall settings on the server.

**Comment by EmmanuelBeziat** [comment]
Okay, now I’m ashamed. Totally forgot about Iptables… Thanks!

**Comment by justingivens** [comment]
Did the same exact thing today!
