### ISSUE TITLE
didn't get triggered because the trigger rules were not satisfied

### ISSUE THREAD

**Issue by sri-05** [adnanh/webhook#407]
Hi I am running sample webhook when I push the code I get an error in the server side as below 
```
[webhook] 2020/04/15 07:51:19 [ef513b] incoming HTTP request from 14.98.146.10:39656
[webhook] 2020/04/15 07:51:19 [ef513b] deployment-tutorial got matched
[webhook] 2020/04/15 07:51:19 [ef513b] deployment-tutorial got matched, but didn't get triggered because the trigger rules were not satisfied
[webhook] 2020/04/15 07:51:19 200 | 634.196µs | 10.0.1.11:9000 | POST /hooks/deployment-tutorial
```

**Comment by moorereason** [comment]
That doesn't tell us much.  Can you post your config? It would help to see a sample payload, too.

**Comment by igalic** [comment]
i have a bunch of rules, it'd be nice to know which one didn't match.

**Comment by moorereason** [comment]
@igalic, agreed.  There's [more logging coming](https://github.com/adnanh/webhook/pull/384) in the next release that _may_ help with that (will log missing node lookups).  If you want to discuss these enhancements, please open a new issue.
