### ISSUE TITLE
How to configure hooks.json with two hooks

### ISSUE THREAD

**Issue by alexw22** [adnanh/webhook#408]
I am trying to define 2 hooks in the hooks.json file.
What is the correct syntax for this? I can't get it to work and the examples don't mention two hook id's in a single file.

I am trying to do something like this in my hooks.json file:

```
[
  {
    "id": "webhook",
    "execute-command": "/var/scripts/webhook.sh",
    "command-working-directory": "/var/webhook",
  }
 {
    "id": "webhook2",
    "execute-command": "/var/scripts/webhook2.sh",
    "command-working-directory": "/var/webhook"
  }
]
```

**Comment by adnanh** [comment]
You are missing a comma `,` in between the objects `[ {...}, {...} ]` :-)

**Comment by alexw22** [comment]
Could have known it! Anyways, thank you very much! It solved my issues :-)
This webhook utility is great!

**Comment by adnanh** [comment]
You're welcome :-) Glad you found it useful!
