### ISSUE TITLE
Cant passing PayLoad result to command (Nothing Print in Output)

### ISSUE THREAD

**Issue by zukinaru** [adnanh/webhook#409]
Hi,

I'm new to webhook, this is a great tool, however, for a newbie like me, it's still confusing...

I have read the documentation on how to read PayLoad here --> https://github.com/adnanh/webhook/wiki/Hook-Examples
but in my webhook log, it still failed to read payload using echo and Nothing seems to be printed in the output.

my **JSON**:

```
{
  "links": {
    "api_self": {
      "href": "/example,
      "method": "get"
    },
    "artifacts": [
      {
        "files": [
          {
            "filename": "example.pdf",
            "href": "http://example.com/this_is_the_file.pdf",
...
}
```

I want to get the links...
and below is my **hooks.json:**

```
[
  {
    "id": "example",
    "execute-command": "/opt/scripts/redeploy_rk.sh",
    "command-working-directory": "/opt/scripts",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "links.artifacts.files.href"
      }
    ]
  }
]   
```

and below **the scripts (.sh)** :

```
#!/bin/bash -e
link_pdf=$1 #link to download PDF example
echo "running scripts..."
echo $1
echo "${link_pdf}"
```

WebHook Log / Response:

```
[webhook] 2020/04/19 12:44:14 found 1 hook(s) in file
[webhook] 2020/04/19 12:44:14   loaded: run_example
[webhook] 2020/04/19 12:44:14 serving hooks on https://0.0.0.0:9000/hooks/{id}
[webhook] 2020/04/19 12:44:14 os signal watcher ready
[webhook] 2020/04/19 12:52:58 Started POST /hooks/run_example
[webhook] 2020/04/19 12:52:58 run_example got matched
[webhook] 2020/04/19 12:52:58 run_example hook triggered successfully
[webhook] 2020/04/19 12:52:58 Completed 200 OK in 501.314µs
[webhook] 2020/04/19 12:52:58 error extracting command arguments: couldn't retrieve argument for {Source:payload Name:links.artifacts.files.href EnvName:}
[webhook] 2020/04/19 12:52:58 executing /opt/scripts/run_example.sh (/opt/scripts/run_example.sh) with arguments ["/opt/scripts/run_example.sh" ""] and environment [] using /opt/scripts as cwd
[webhook] 2020/04/19 12:52:58 command output: running scripts...
...
 and

[webhook] 2020/04/19 12:52:58 finished handling run run_example
```

What I want to achive: Download the url using wget

Any Idea ?
                    
Note:
(1) WebHook version = Installed: 2.5.0-2
(2) Installed in Ubuntu using apt-get

**Comment by moorereason** [comment]
In your payload, `artifacts` and `files` are arrays, so you need to use an index for those lookups: `links.artifacts.0.files.0.href`

**Comment by zukinaru** [comment]
> In your payload, `artifacts` and `files` are arrays, so you need to use an index for those lookups: `links.artifacts.0.files.0.href`

Thank You, I think this one should be written in Documentation. so can help newbie....

**Comment by moorereason** [comment]
It's mentioned in [Referencing Request Values](https://github.com/adnanh/webhook/blob/master/docs/Referencing-Request-Values.md#referencing-request-values) under type 3, *"Payload (JSON or form-value encoded)."*  Not saying the docs couldn't be better, but it is mentioned.  😉

If you can come up with a good example, I'd welcome a PR.  Just make sure your PR is against the `development` branch (that trips up most first-time contributors).
