### ISSUE TITLE
WooCommerce webhook page will not accept VPS webhook url

### ISSUE THREAD

**Issue by g4spow** [adnanh/webhook#410]
I use an Ionos VPS which has port 9000 open and runs the adnan ```webhook``` program fine.

I am trying to send a payload from an external WooCommerce(WordPress) website but the URL will just not be accepted by WooCommerce. I can send a basic CURL request to the VPS URL and it triggers the VPS webhook and executes the script.

The WooCommerce error is:

Error: Delivery URL cannot be reached: A valid URL was not provided.
https://prnt.sc/s38vsa
(I have changed my URL to example.com just to mask it in this screenshot)

Here is my hooks.json content, there are many pieces of data in the WooCommerce webhook, but for the moment I just wish to use the ```ID```, ```number``` and ```billing.email```

```
[
    {
        "id": "redeploy-app",
        "execute-command": "/opt/scripts/redeploy.sh",
        "command-working-directory": "/home/",
        "response-message": "I got the payload!",
        "response-headers": [
            {
                "name": "Access-Control-Allow-Origin",
                "value": "*"
            }
        ],
        "pass-arguments-to-command": [
            {
                "source": "payload",
                "name": "id"
            },
            {
                "source": "payload",
                "name": "number"
            },
            {
                "source": "payload",
                "name": "billing.email"
            }
        ]
    }
]
```

If anyone wishes to quickly replicate this in a few minutes, you can setup WordPress then install WooCommerce plugin and create a simple product such as Book for £5 and just switch on Cash on Delivery - only takes a couple of minutes. Then just pop your port 9000 URL in  WooCommerce->Settings->Webhooks (Order Created)

**Comment by moorereason** [comment]
Can you provide an example request payload?

**Comment by g4spow** [comment]
Here is an example of a WooCommerce payload

https://github.com/woocommerce/woocommerce/issues/12463

**Comment by moorereason** [comment]
What version of webhook are you running?  Can you run webhook with `-verbose` and share the output?

**Comment by adnanh** [comment]
What status code does your hook return? According to the source code, that error can be result of an non 200 HTTP response status code.

**Comment by adnanh** [comment]
@g4spow for the sake of the community, would you mind writing down what was the root caude and how you solved the issue?
