### ISSUE TITLE
TLS handshake error after Test Query to WebHook URL

### ISSUE THREAD

**Issue by zukinaru** [adnanh/webhook#411]
Running my webhook, but after a testing request (just type URL on browser) to my webhook url (https) i got below error:

```
[webhook] 2020/04/22 02:59:51 version 2.5.0 starting
[webhook] 2020/04/22 02:59:51 setting up os signal watcher
[webhook] 2020/04/22 02:59:51 attempting to load hooks from hooks/hooks_sy_myapps.json
[webhook] 2020/04/22 02:59:51 found 1 hook(s) in file
[webhook] 2020/04/22 02:59:51   loaded: myapps
[webhook] 2020/04/22 02:59:51 serving hooks on https://0.0.0.0:9000/hooks/{id}
[webhook] 2020/04/22 02:59:51 os signal watcher ready
[webhook] 2020/04/22 02:59:56 http: TLS handshake error from a.b.c.d:50416: tls: first record does not look like a TLS handshake
```

my command to running webhook:

`webhook -hooks hooks/hooks_apps.json  -key ssl-key/privkey.pem -secure -verbose -cert ssl-key/cert.pem` 

my hook configuration:

```
[
  {
    "id": "uploader-myapps",
    "execute-command": "/opt/Uploader/scripts/scripts_sy_myapps/redeploy_sy_myapps.sh",
    "command-working-directory": "/opt/Uploader/scripts/scripts_sy_myapps",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "links.artifacts.0.files.0.href"
      }
    ]
  }
]   
```

any idea?

**Comment by moorereason** [comment]
Can you verify your claim with `curl`?  It looks like your browser is not initiating a TLS request.

**Comment by zukinaru** [comment]
@moorereason Using curl -v i get below response:

`*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to xxxxxx.xyz (x.x.x.x) port 9000 (#0)
> GET /hooks/uploader HTTP/1.1
> Host: xxxxx.xyz:9000
> User-Agent: curl/7.54.0
> Accept: */*
> 

* Connection #0 to host xxxxx.xyz left intact`

**Comment by moorereason** [comment]
It looks like webhook is not using TLS.  Here's a TLS example:

```
$ curl -v --http1.1 https://www.httpbin.org/get
*   Trying 3.232.168.170:443...
* Connected to www.httpbin.org (3.232.168.170) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Jan 18 00:00:00 2020 GMT
*  expire date: Feb 18 12:00:00 2021 GMT
*  subjectAltName: host "www.httpbin.org" matched cert's "*.httpbin.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /get HTTP/1.1
> Host: www.httpbin.org
> User-Agent: curl/7.69.1
> Accept: */*
>
...
```

From your previous issue, you mentioned using webhook v2.5.0.  That's pretty old (4.5yrs) and potentially insecure.  I would recommend downloading the [latest release](https://github.com/adnanh/webhook/releases/latest) from Github and giving that a try.

**Comment by zukinaru** [comment]
@moorereason 

I try to upgrade WebHook, but it said this is the latest version:

```
% sudo apt-get --only-upgrade install webhook
Reading package lists... Done
Building dependency tree
Reading state information... Done
webhook is already the newest version (2.5.0-2).
0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
```

Note: I'm using Ubuntu Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-96-generic x86_64)

**Comment by moorereason** [comment]
The Ubuntu LTS series will generally pick a version and stick with it forever.  I doubt they're be updating the version they're shipping, so you'll likely need to go outside of the Ubuntu packaging ecosystem.  It's up to you if you're comfortable managing binaries outside of your distro's package management.

If it were me, I would uninstall the Ubuntu package, download the latest release binary from Github, and put the webhook binary in the appropriate place (like `/usr/local/bin`).  The nice thing about webhook (and most anything written in Go) is that it's just a single binary.  The dependencies are very minimal (mainly just libc, IIRC).

**Comment by zukinaru** [comment]
I found this solved by using go (not ubuntu). this case can be closed...
