### ISSUE TITLE
Is it possible to have one webhook pass one argument to a script depending on supplied request parameters?

### ISSUE THREAD

**Issue by noelforte** [adnanh/webhook#412]
Let's say I have a script to deploy a site set up, but I want it to be triggered either from a request sent from a Git host (via `"source": "payload"`)or from a hit from the browser (via `"source": "url"`). Is it possible to set up a rule within the hook to grab either the payload, or the query string, and pass one argument to my script? Or would it be better to have multiple hooks handle this?

**Comment by moorereason** [comment]
I think you'll need multiple hooks.

**Comment by noelforte** [comment]
Ok. That's probably what I'll do. Probably best to keep them isolated.
