### ISSUE TITLE
How to run webhook on port 80 or 443 (https) ?

### ISSUE THREAD

**Issue by zukinaru** [adnanh/webhook#418]
Hi, I want my webhook to run on port 80/443 (https), not on a random port like 9000 etc.

i have tried it but return `permission denied`
any idea How to achieve this?

Thanks In Advance...

**Comment by adnanh** [comment]
Ports 1-1023 are by default privileged ports. To bind to a privileged port, a process must be running with root permissions. Ports that are greater than 1023 are by default non-privileged.

**Comment by zukinaru** [comment]
Hi @adnanh thank you for the suggestion. 

I found a method by using the Apache Reverse Proxy.

However, in Configuration at `/etc/apache2/mods-available/proxy.conf` it said:

>If you want to use apache2 as a forward proxy, uncomment the
        # 'ProxyRequests On' line and the <Proxy *> block below.
        # WARNING: Be careful to restrict access inside the <Proxy *> block.
        # Open proxy servers are dangerous both to your network and to the
        # Internet at large.  

My Question, What Condition make it dangerous when we're using Reverse Proxy?

Are we safe to use below config (`Allow from all`)?

```
ProxyRequests On
<Proxy *>
   Order Deny,Allow
   Deny from all
   Allow from all
</Proxy>    
```
