### ISSUE TITLE
go get github.com/adnanh/webhook not creating bin folder on EC2

### ISSUE THREAD

**Issue by AleksandarTokarev** [adnanh/webhook#419]
Hello i am using Amazon EC2 and i want to setup webhooks there. 
I am installing go and doin `go get github.com/adnanh/webhook` but here is what i get
`/home/ec2-user/go/src/github.com/adnanh/webhook`. I do not get any bin folder or something to reference it as the guide
`$ /path/to/webhook -hooks hooks.json -verbose` 
What would that path to webhook be in this case?
Thanks a lot in advance

**Comment by adnanh** [comment]
Try `go build github.com/adnanh/webhook`. That should produce a binary :-)

**Comment by moorereason** [comment]
I don't remember if `go get` will build and install the binary or not.  If it does, see `go help install` for where the installed binary should be located.
