### ISSUE TITLE
Need to help about trigger-rule

### ISSUE THREAD

**Issue by bientt210** [adnanh/webhook#436]
I have some information as below:
**alertmanager: level=debug ts=2020-07-01T03:00:45.377Z caller=dispatch.go:473 component=dispatcher aggrGroup="{}/{send_webhook=~\"^(?:true)$\"}:{alertname=\"Server_Down\"}" msg=flushing alerts=[Server_Down[2e70eb5][active]]**

now I need to set **trigger-rule** like this:
```json
{
"and":
  [
    {
      "match":
      {
        "type": "value",
        "value": "refs/heads/master",
        "parameter":
        {
          "source": "payload",
          "name": "ref"
        }
      }
    },
    {
      "match":
      {
        "type": "regex",
        "regex": ".*",
        "parameter":
        {
          "source": "payload",
          "name": "repository.owner.name"
        }
      }
    }
  ]
}
```
But I don't know how to do this.
Can anyone help me to config exacly **trigger-rule**

Thanks you so much!

**Comment by moorereason** [comment]
It looks like you are showing a log message from an `alertmanager` system, which I'm not familiar with.  I'm not sure what you're wanting `webhook` to do.  `webhook` doesn't parse log messages.

**Comment by bientt210** [comment]
> It looks like you are showing a log message from an `alertmanager` system, which I'm not familiar with. I'm not sure what you're wanting `webhook` to do. `webhook` doesn't parse log messages.

Thanks for your answer,

Exactly, it is **alertmanager** system, so I want to use **trigger-rule** for **match** with a **label** such as _alertname_...or a label I define... but after a long time investigate, I don't know how to do. Can you give me some solution in this case?

Thanks you so much!

**Comment by moorereason** [comment]
I'm assuming you're talking about this:  https://prometheus.io/docs/alerting/latest/configuration/#webhook_config

It would be helpful to see a complete JSON payload from alertmanager.

Looking at the alertmanager docs, I think a potential trigger rule might look like this:

```json
{
    "match":
    {
        "type": "value",
        "value": "mylabel",
        "parameter":
        {
          "source": "payload",
          "name": "alerts.0.labels"
        }
    }
}
```
If the `labels` field can have multiple labels in it's value, you may need to use a regex rule.  It all depends on what alertmanager is sending.

**Comment by bientt210** [comment]
@moorereason  Thanks you so much for support me,

Follow your suggestion I setup as below:
**- id: reboot
  execute-command: /opt/webhook/reboot.sh
  command-working-directory: /opt/webhook
  trigger-rule:
    and:
    - match:
        type: value
        value: send_webhook
        parameter:
          source: payload
          name: alerts.0.labels**

I has define my label as `send_webhook` but when Alertmanager system notify, nothing happen with my webhook.
Can you support me in this case?

Thanks you

**Comment by moorereason** [comment]
Can you provide us with the verbose `webhook` logs when a request is received?  What version of `webhook` are you running?  If you are using v2.7.0, you can show debug logs that would be particularly helpful here.

**Comment by bientt210** [comment]
I'm using the latest version 2.7, here the logs when I run with debug mode:

**[webhook] 2020/07/03 09:54:46 [cd55ba] 404 | 15 B | 182.908µs | 172.27.100.114:9000 | POST /hooks/root
[webhook] 2020/07/03 09:55:16 [6e4bb8] incoming HTTP POST request from 172.27.100.114:60110
> [6e4bb8] POST /hooks/root
> [6e4bb8] Content-Length: 1083
> [6e4bb8] Content-Type: application/json
> [6e4bb8] User-Agent: Alertmanager/0.21.0
> [6e4bb8] id:
> [6e4bb8] {"receiver":"webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"Server_Down","alias":"test-server","instance":"172.27.100.115:9100","job":"test","send_webhook":"true","severity":"critical"},"annotations":{"description":"test-server has been down for more than 1 minutes","summary":"Instance test-server down"},"startsAt":"2020-07-02T16:56:05.366565107+07:00","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://bientt1-monitor-stack.novalocal:9090/graph?g0.expr=up%7Binstance%3D~%22.%2A%3A9100%22%7D+%3D%3D+0\u0026g0.tab=1","fingerprint":"2e70eb50e042907f"}],"groupLabels":{"alertname":"Server_Down"},"commonLabels":{"alertname":"Server_Down","alias":"test-server","instance":"172.27.100.115:9100","job":"test","send_webhook":"true","severity":"critical"},"commonAnnotations":{"description":"test-server has been down for more than 1 minutes","summary":"Instance test-server down"},"externalURL":"http://bientt1-monitor-stack.novalocal:9093","version":"4","groupKey":"{}/{send_webhook=~\"^(?:true)$\"}:{alertname=\"Server_Down\"}","truncatedAlerts":0}
> [6e4bb8]

< [6e4bb8] Not Found
< [6e4bb8] Hook not found.**

Could you help me define a right `trigger-rule` with `labels`

Thanks you so much.

**Comment by moorereason** [comment]
> ```< [6e4bb8] Hook not found.```

Based on your previous comments, it looks like you've created a `reboot` hook, but the request from `alertmanager` is hitting `/hooks/root` instead of `/hooks/reboot`.

**Comment by bientt210** [comment]
Thanks for your support @moorereason , 

Here the full logs I run with your suggest, It's run success with no `trigger-rule`, can you help add the right trigger-rule:
`[webhook] 2020/07/07 10:33:15 [bfa131] reboot hook triggered successfully
> [e96fed] POST /hooks/reboot
> [e96fed] Content-Length: 1121
> [e96fed] Content-Type: application/json
> [e96fed] User-Agent: Alertmanager/0.21.0
> [e96fed] id:
> [e96fed] {"receiver":"webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"Memory_Free_Low","alias":"prometheus-server","instance":"172.27.100.114:9100","job":"prometheus-server","severity":"warning"},"annotations":{"description":"5.5%","summary":"Instance prometheus-server is high memory usage"},"startsAt":"2020-07-07T10:33:05.366565107+07:00","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://monitor-stack.novalocal:9090/graph?g0.expr=100+-+100+%2A+%28%28node_memory_MemFree_bytes+%2B+node_memory_Buffers_bytes+%2B+node_memory_Cached_bytes%29+%2F+node_memory_MemTotal_bytes%29+%3E%3D+5\u0026g0.tab=1","fingerprint":"acabc112b21104a4"}],"groupLabels":{"alertname":"Memory_Free_Low"},"commonLabels":{"alertname":"Memory_Free_Low","alias":"prometheus-server","instance":"172.27.100.114:9100","job":"prometheus-server","severity":"warning"},"commonAnnotations":{"description":"5.5%","summary":"Instance prometheus-server is high memory usage"},"externalURL":"http://monitor-stack.novalocal:9093","version":"4","groupKey":"{}/{}:{alertname=\"Memory_Free_Low\"}","truncatedAlerts":0}
> [e96fed]

< [e96fed]
[webhook] 2020/07/07 10:33:15 [e96fed] 200 | 0 B | 937.166µs | 172.27.100.114:9000 | POST /hooks/reboot
> [bfa131] POST /hooks/reboot
> [bfa131] Content-Length: 1055
> [bfa131] Content-Type: application/json
> [bfa131] User-Agent: Alertmanager/0.21.0
> [bfa131] id:
> [bfa131] {"receiver":"webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"Server_Down","alias":"test-server","instance":"172.27.100.115:9100","job":"test","send_webhook":"true","severity":"critical"},"annotations":{"description":"test-server has been down for more than 1 minutes","summary":"Instance test-server down"},"startsAt":"2020-07-07T10:33:05.366565107+07:00","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://monitor-stack.novalocal:9090/graph?g0.expr=up%7Binstance%3D~%22.%2A%3A9100%22%7D+%3D%3D+0\u0026g0.tab=1","fingerprint":"2e70eb50e042907f"}],"groupLabels":{"alertname":"Server_Down"},"commonLabels":{"alertname":"Server_Down","alias":"test-server","instance":"172.27.100.115:9100","job":"test","send_webhook":"true","severity":"critical"},"commonAnnotations":{"description":"test-server has been down for more than 1 minutes","summary":"Instance test-server down"},"externalURL":"http://monitor-stack.novalocal:9093","version":"4","groupKey":"{}/{}:{alertname=\"Server_Down\"}","truncatedAlerts":0}
> [bfa131]

< [bfa131]
[webhook] 2020/07/07 10:33:15 [bfa131] executing /opt/webhook/reboot.sh (/opt/webhook/reboot.sh) with arguments ["/opt/webhook/reboot.sh"] and environment [] using /opt/webhook as cwd
[webhook] 2020/07/07 10:33:15 [bfa131] 200 | 0 B | 1.226279ms | 172.27.100.114:9000 | POST /hooks/reboot
[webhook] 2020/07/07 10:33:15 [e96fed] executing /opt/webhook/reboot.sh (/opt/webhook/reboot.sh) with arguments ["/opt/webhook/reboot.sh"] and environment [] using /opt/webhook as cwd
[webhook] 2020/07/07 10:33:15 [e96fed] command output: Shutdown scheduled for Tue 2020-07-07 10:34:16 +07, use 'shutdown -c' to cancel.

[webhook] 2020/07/07 10:33:15 [e96fed] finished handling reboot
[webhook] 2020/07/07 10:33:15 [bfa131] command output: Shutdown scheduled for Tue 2020-07-07 10:34:16 +07, use 'shutdown -c' to cancel.

[webhook] 2020/07/07 10:33:15 [bfa131] finished handling reboot`

**Comment by moorereason** [comment]
Try this:
```
- id: reboot
  execute-command: /opt/webhook/reboot.sh
  command-working-directory: /opt/webhook
  trigger-rule:
    and:
    - match:
        type: value
        value: true
        parameter:
          source: payload
          name: alerts.0.labels.send_webhook
```

**Comment by bientt210** [comment]
Thanks you @moorereason,

I follow your suggestion, It's worked!!!

Thanks you so much,
Have a nice day :)
