### ISSUE TITLE
Payload as Content-Type text/plain as argument to script

### ISSUE THREAD

**Issue by Mbwh1989** [adnanh/webhook#439]
Hi, 

I'm trying to configure webhook to also send a payload, configured as text/plain to my script.

I got the following hooks.json
```
[
        {
                "id": "testHook",
                "execute-command": "/var/script/test.sh",
                "command-working-directory": "/my/working/dir",
                "pass-arguments-to-command": [
                        {
                                "source": "entire-payload"
                        }
                ]
        }
]
```
My test.sh is just:
```
#!/bin/sh

PARAM=$1

echo "Test Texecuted"
echo "Param: "
echo $PARAM
```
If I send a payload like {"test": "test2"} I get the desired output. 

But if I send this payload as a content-type text/plain, only null is passed. The problem is, I can get JSON-conform payloads as well as payloads that are just a string. I only want to pass the complete payload to my script, is that somehow possible? Thanks in advance!

**Comment by adnanh** [comment]
Not yet, but there is a feature in progress which can allow you to do that.

**Comment by Mbwh1989** [comment]
Thank you very much for the fast response! Can you give a rough estimate when it could be available?

**Comment by moorereason** [comment]
I was looking at this request and wanted to share some notes.

`webhook` assumes that it will be parsing JSON, XML, or URL-encoded form data in the payload.  Additionally, the `entire-payload` source option will send the **parsed** payload data structure **as JSON** to the command (even if it was XML to begin with).  We're not actually sending the raw payload.  As @adnanh alluded, watch #356 for that feature.
