### ISSUE TITLE
My webhook has stopped working

### ISSUE THREAD

**Issue by koniecznytomek** [adnanh/webhook#444]
Hello,
Some time ago I created a webhook which, after initialization, downloaded the updated repository from github and placed it in the right place on my vps server. Everything worked fine. However, today I see the webhook not working and i have the message "Hook rules were not satisfied." and in log file:

0|hook  | [webhook] 2020/07/26 14:29:26 deploy-webhook got matched
0|hook  | [webhook] 2020/07/26 14:29:26 deploy-webhook got matched, but didn't get triggered because the trigger rules were not satisfied

I haven't changed anything in the meantime. Please help.

My hooks.json configuration:

```
[
  {
    "id": "deploy-webhook",
    "execute-command": "/var/www/webhook/deploy.sh",
    "command-working-directory": "/var/www/domain.com/public_html/",
    "response-message": "Executing deploy script...",
    "trigger-rule": {
      "and": [
        {
          "match": {
            "type": "payload-hash-sha1",
            "secret": "mysecret",
            "parameter": {
              "source": "header",
              "name": "X-Hub-Signature"
            }
          }
        },
        {
          "match": {
            "type": "value",
            "value": "refs/heads/master",
            "parameter": {
              "source": "payload",
              "name": "ref"
            }
          }
        }
      ]
    }
  }
]
```

**Comment by moorereason** [comment]
Can you try the latest version of webhook?  We added a debug option that will spit out the incoming request to the log output which may help diagnose the problem.

**Comment by koniecznytomek** [comment]
Yes, i have newest version (2.5.0-2) installed. 
How can i read output log? is this correct?:

`journalctl -u webhook`

**Comment by moorereason** [comment]
The latest version is v2.7.0, but it sounds like you're using the packaged version from your distribution.  v2.5.0 doesn't have the debug feature.

**Comment by koniecznytomek** [comment]
I'm sorry, i try to build from source the latest version with Go, but it's not going well and I don't know what i'm doing wrong :(
I have latest Go (1.12) and i put this command:

`go build github.com/adnanh/webhook`

# github.com/adnanh/webhook
go/src/github.com/adnanh/webhook/tls.go:11:20: undefined: tls.CipherSuites
go/src/github.com/adnanh/webhook/tls.go:53:15: undefined: tls.CipherSuites
go/src/github.com/adnanh/webhook/webhook.go:262:27: undefined: log.Writer

**Comment by koniecznytomek** [comment]
Ok, I reinstalled the webhook, now i have 2.7.0 but i have the same problem:

```
[webhook] 2020/07/27 19:29:19 [534ddc] incoming HTTP POST request from 140.82.115.250:21921
[webhook] 2020/07/27 19:29:19 [534ddc] deploy-webhook got matched
[webhook] 2020/07/27 19:29:19 [534ddc] parameter node not found: ref
[webhook] 2020/07/27 19:29:19 [534ddc] deploy-webhook got matched, but didn't get triggered because the trigger rules were not satisfied
[webhook] 2020/07/27 19:29:19 [534ddc] 200 | 30 B | 2.675113ms | myip:9000 | POST /hooks/deploy-webhook
```

**Comment by moorereason** [comment]
> parameter node not found: ref

**Comment by moorereason** [comment]
Additionally, add the `-debug` option to the command line, and you'll get the full payload printed into the logs.

**Comment by koniecznytomek** [comment]
Ok, i changed my hooks.json to 

```

[
  {
    "id": "deploy-webhook",
    "execute-command": "/var/www/webhook/deploy.sh",
    "command-working-directory": "/var/www/",
    "response-message": "Executing deploy script...",
    "trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "secret",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
  }
]

```

now everything works as it should :) Thank You!
