### ISSUE TITLE
webhooks_0: ERROR (spawn error)

### ISSUE THREAD

**Issue by simplenotezy** [adnanh/webhook#450]
When I am running `sudo supervisorctl start webhooks:*` I get error: `webhooks:webhooks_0: ERROR (spawn error)`
 
```
root@deployer:~# sudo supervisorctl start webhooks:*
webhooks:webhooks_0: ERROR (spawn error)
```

How can I debug further?

I used to work fine, now it just stopped all of a sudden.

**Comment by moorereason** [comment]
What version of webhook?  What OS/arch?

I've never used supervisor, so you're going to have to help me out.  Is there a config file associated with this service?  Does supervisord log any output from webhook?

**Comment by simplenotezy** [comment]
So this is the error message I am getting from supervisor:

```
[webhook] 2020/08/12 09:24:37 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2020/08/12 09:24:37 listen tcp 0.0.0.0:9000: bind: address already in use
[webhook] 2020/08/12 09:24:40 version 2.5.0 starting
[webhook] 2020/08/12 09:24:40 setting up os signal watcher
[webhook] 2020/08/12 09:24:40 attempting to load hooks from /root/hooks.json
[webhook] 2020/08/12 09:24:40 found 2 hook(s) in file
[webhook] 2020/08/12 09:24:40 	loaded: one-webhook
[webhook] 2020/08/12 09:24:40 	loaded: two-beta-webhook
[webhook] 2020/08/12 09:24:40 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2020/08/12 09:24:40 listen tcp 0.0.0.0:9000: bind: address already in use
```

Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-112-generic x86_64)

I have no clue what version of webhook I am running. But I haven't updated it in a while, and it used to work just fine. I have tried `webhook -v`, `webhook --version`, `man webhook`, etc - no easy way to get the version number.

**Comment by simplenotezy** [comment]
This is what's running on port 9000:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      101        15723      728/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          18993      987/sshd
tcp        0    256 212.356.543.21:22       37.511.159.90:9112      ESTABLISHED 0          168110     17354/sshd: root@pt
tcp        0      0 212.356.543.21:22       97.141.213.126:52884    ESTABLISHED 0          158769     16167/sshd: root@pt
tcp        0      0 212.356.543.21:22       97.141.213.126:64017    ESTABLISHED 0          163200     16764/sshd: root@pt
tcp6       0      0 :::9000                 :::*                    LISTEN      0          17082      909/webhook
tcp6       0      0 :::22                   :::*                    LISTEN      0          18995      987/sshd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           101        15722      728/systemd-resolve
```

**Comment by simplenotezy** [comment]
I solved it by killing the process and then restarting everything. Strange thing is, I did try to reboot the whole server previously, but that didn't work. Killing the pid did however.

**Comment by moorereason** [comment]
For the record, it's `webhook -version`.  😏

**Comment by adnanh** [comment]
Also, please consider upgrading to the latest version. 2.5.0 is very old!

**Comment by simplenotezy** [comment]
Thanks @adnanh I will look into that. Any breaking changes since my version? Can't really check since webhook -version does not exist:

    root@deployer:~# webhook -version
    flag provided but not defined: -version

Also, when a server has been rebooted it wont work. I need to run `killall -9 webhook` before I can restart webhook

**Comment by moorereason** [comment]
If you're using an RPM package, check the package version: `rpm -q webhook`.  Your Ubuntu release looks to package v2.5.0.  The `-version` flag was added in v2.6.0.  To check for breaking changes since your version, read through the release notes at https://github.com/adnanh/webhook/releases.

As for the `killall` business, that's likely a problem with your supervisor setup not `webhook`.

**Comment by simplenotezy** [comment]
Hi @moorereason not using rpm. How can I otherwise check the version?

**Comment by moorereason** [comment]
It will be difficult to determine the version.  If you installed a pre-compiled binary from this Github repository, you can compare the file checksums.

Either way, I would recommend installing the latest webhook release.  Whatever you're running is pretty old.
