### ISSUE TITLE
Document passing string argument to run command

### ISSUE THREAD

**Issue by simplenotezy** [adnanh/webhook#451]
How can I pass arguments to the command being run?

Normally the command I write is `sh deploy.sh production`, but it doesn't work if I append "production" to the command.

It will return: `deploy.sh production: no such file or directory`

**Comment by simplenotezy** [comment]
I tried with this:

    "pass-arguments-to-command": [
        {
            "source": "string",
            "name": "production"
        }
    ]

and it seems to do the trick - not sure though - had to look through the /test/ folder of the repository.

**Comment by simplenotezy** [comment]
To answer your comment, since you closed the issue:


@simplenotezy,
In the future, please don't comment on issues that were closed years ago.  Open a new issue.

To answer your question, see the Github example at https://github.com/adnanh/webhook/blob/master/docs/Hook-Examples.md#incoming-github-webhook

__Originally posted by @moorereason in https://github.com/adnanh/webhook/pull/164#issuecomment-672936985__


The doc you are referring to does indicate a lot of great examples, except for the most simple one, where the argument is simply passed without being part of payload or query string. That's what I meant was missing.

**Comment by moorereason** [comment]
You're right.  We need better reference documentation that explains each object and the possible attributes and values associated with those objects.

**Comment by adnanh** [comment]
Fixed in #489
