### ISSUE TITLE
Full daemonise support.

### ISSUE THREAD

**Issue by eleksir** [adnanh/webhook#454]
Webhook already can write own pid to pidfile. But it is unable to do double fork and go background detaching from stdio.

Also it is unable to drop privileges, if -setgid and -setuid set to ID of desired group and user on linux it prints
`[webhook] 2020/08/30 19:23:38 error dropping privileges: setuid and setgid not supported on linux`
and aborting to start.

**Comment by moorereason** [comment]
> Webhook already can write own pid to pidfile. But it is unable to do double fork and go background detaching from stdio.

I'm starting to regret adding pidfile support.  I'm not interested in adding support for full daemonization.  Forking, TTYs, syslog, blah, blah.  No thanks.  It would simply complicate the code and create more issue reports when almost all systems already have daemon management frameworks built-in.

> error dropping privileges: setuid and setgid not supported on linux

That's an upstream issue in Go:  https://github.com/golang/go/issues/1435

**Comment by eleksir** [comment]
> That's an upstream issue

Hmm... never know - strange issue, but okay, will wait for its resolves... somehow.

> daemon management

Service management, you mean. Service not necessary must be daemon, it can be shell-script that sitting in foreground waiting for some event and shit poorly formed messages to stdout. But daemon is a special case of service that can detach itself from stdio, fork to background, do logging by itself and drop privileges. But it is not important now and here.

> ...TTYs, syslog, blah, blah.

Syslog? that is last thing i can imagine. It _already_ can log by itself, acting like normal system application. 

> It would simply complicate the code and create more issue...

Well it's depends on mastery of author :) Anyway complexity of this _new_ code will be drop-in-the-seas comparing what is already done. But i understand that you do not want to implement "old legacy cruft" in webhook. It looks like it will be used in some relatively rare cases.

Well, i can continue use `sudo --background` for that - it works quite well in my case.

P.S.
Pid-file support eliminate wrapper-that-do-it-for-webhook requirement and that's great! Thanks a lot!
