### ISSUE TITLE
Passing GET query string as arguments to command

### ISSUE THREAD

**Issue by simplenotezy** [adnanh/webhook#458]
Say I have this example of an command:

	{
		"id": "deploy-beta-build",
		"execute-command": "/root/project/deploy.sh",
		"command-working-directory": "/root/project",
		"response-message": "Deploying STAGING build",
		"pass-arguments-to-command": [
			{
				"source": "string",
				"name": "beta"
			},
			{
				"source": "string",
				"name": "THE_QUERY_PARAMETER"
			}
		]
	}

How do I get the second argument passed to the command to be the contents of a query parameter?

Say the webhook link looks like this:

     /deploy-beta-build?someParameter=1234%205678 (may contain spaces in parameter)

So it would end up like this:

    . deploy.sh beta "1234 5678"

If it's too much work, I could probably work out a way to strip the space from the parameter, but nevertheless, really interested in passing the query parameter as a parameter to the run command.

**Comment by simplenotezy** [comment]
I have tried to do like so: https://github.com/adnanh/webhook/issues/357

But I am getting error:

     [webhook] 2020/09/20 00:01:52 error extracting command arguments: couldn't retrieve argument for {Source:query Name:since EnvName:}

When I hit the url /deploy-beta-build?since=1234%205678

**Comment by moorereason** [comment]
Try:
```json
{
  "source": "url",
  "name": "parameter-name"
}
```

**Comment by simplenotezy** [comment]
@moorereason thanks!
