### ISSUE TITLE
Webhook ID not loading - Windows 

### ISSUE THREAD

**Issue by correctbuddy789** [adnanh/webhook#470]
Hi, I am not sure if I am doing something wrong. I have webhook.exe in my working directory but as soon as I try to load the webhook it do not return with any Id. Help would really be appreciated. Thank you 
------------Command Prompt ---------------------------------------------------
```
C:\Users\tusha\Desktop\ghost-local\jamify-starter>webhook -hooks hooks.json -verbose -port 7000
[webhook] 2020/10/14 15:09:53 version 2.7.0 starting
[webhook] 2020/10/14 15:09:53 attempting to load hooks from hooks.json
[webhook] 2020/10/14 15:09:53 found 1 hook(s) in file
[webhook] 2020/10/14 15:09:53   loaded: deploy
[webhook] 2020/10/14 15:09:53 serving hooks on http://0.0.0.0:7000/hooks/{id}
```
-------------------------------------------Hooks.json-----------------------------------------
```json
[
  {
    "id": "deploy",
    "execute-command": "deploy.sh",
    "command-working-directory": "C:/Users/tusha/Desktop/ghost-local/jamify-starter"
  }
]
```

**Comment by moorereason** [comment]
Can you share more logs show when a request is received?  Also, try running in debug mode (`-debug`).

**Comment by correctbuddy789** [comment]
C:\Users\tusha\Desktop\ghost-local\jamify-starter>webhook -hooks hooks.json -verbose -port 7000 **#Initiating the Request** 
[webhook] 2020/10/14 20:06:23 version 2.7.0 starting
[webhook] 2020/10/14 20:06:23 attempting to load hooks from hooks.json
[webhook] 2020/10/14 20:06:23 found 1 hook(s) in file
[webhook] 2020/10/14 20:06:23   loaded: deploy
[webhook] 2020/10/14 20:06:23 serving hooks on http://0.0.0.0:7000/hooks/{id}

-------------------------------------------Hooks.json-----------------------------------------

[
  {
    "id": "deploy",
    "execute-command": "deploy.sh",
    "command-working-directory": "C:/Users/tusha/Desktop/ghost-local/jamify-starter"
  }
]

---------------------------------------Deploy.sh Script ---------------------------------------------
#!/bin/sh

yarn clean
yarn build
netlify deploy --prod

**Comment by moorereason** [comment]
That still doesn't show a received request.  The command you're running only starts the webhook service that listens for incoming HTTP requests.  You need to send a web request to the server, such as `http://localhost:7000/hooks/deploy`.  You should then see logs from the webhook service similar to:
```
[webhook] 2020/09/15 17:09:21 [c8acb1] incoming HTTP GET request from 127.0.0.1:60918
[webhook] 2020/09/15 17:09:21 [c8acb1] deploy got matched
[webhook] 2020/09/15 17:09:21 [c8acb1] deploy hook triggered successfully
[webhook] 2020/09/15 17:09:21 [c8acb1] 200 | 4 B | 68.101µs | localhost:7000 | GET /hooks/deploy
```

**Comment by moorereason** [comment]
@correctbuddy789,
Having any luck?
