### ISSUE TITLE
Running venv Python scripts from deploy.sh - source: not found

### ISSUE THREAD

**Issue by n-a-t-e** [adnanh/webhook#473]
Hi, I am using CentOS Linux release 7.6.1810, webhook v2.7.0 from snap.

I'm getting an error trying to call python via venv from a deploy bash script -

```
[{
    "id": "my_hook",
    "execute-command": "./deploy.sh",
}]
```

deploy.sh: 

```
#!/bin/sh

source venv/bin/activate
python -c 'print("test")'

# ... some other bash scripting would continue here ...
```

`[webhook] 2020/10/28 18:03:29 [f2db3e] command output: ./deploy.sh: 3: ./deploy.sh: source: not found`

Running `./deploy.sh` works fine on it's own, it has +x. I'm trying to run a bash script that does a bunch of things, including running a Python script

**Comment by moorereason** [comment]
You should be able to simply run python from the `venv` path.

```
#!/bin/sh

/path/to/venv/bin/python -c 'print("test")'
```

**Comment by n-a-t-e** [comment]
I tried that too, eg, deploy.sh:

```
#!/bin/sh

./venv/bin/python -c 'print("test")'
```

Runs fine on its own, but via webhook gives me:

`[webhook] 2020/10/28 18:37:14 [d49d98] command output: ./venv/bin/python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory`

**Comment by moorereason** [comment]
How are you running webhook?  Are you running it as a system service?

Where is `libpython3.6m.so.1.0`?  What does `ldd ./venv/bin/python` show?

Also, I'd download a pre-built binary from the [Releases page](https://github.com/adnanh/webhook/releases) and try that.  I'm suspicious of the snap installation.

**Comment by n-a-t-e** [comment]
Thanks, it works fine using the pre-built binary
