### ISSUE TITLE
Document passing string arguments to command

### ISSUE THREAD

**Issue by freshwebs** [adnanh/webhook#487]
Hello,

how can i pass something like "-e 123123 -d hallohallo" to my execute-command .sh script?
`
Thanks for your reply..

**Comment by moorereason** [comment]
This should be documented, but you can pass simple string parameters to the command using the `string` source:

```json
"parameter":
{
  "source": "string",
  "name": "-e"
},
"parameter":
{
  "source": "string",
  "name": "123123"
}
```
