### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by DiptoChakrabarty** [adnanh/webhook#491]
both the commands give the same output 
go build github.com/adnanh/webhook  and go get github.com/adnanh/webhook
# github.com/adnanh/webhook/internal/pidfile
go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:38:54: syntax error: unexpected o755, expecting comma or )
go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:41:76: syntax error: unexpected o600, expecting comma or )

**Comment by moorereason** [comment]
Update your version of Go.  `webhook` requires at least Go 1.14.  Additionally, octal integers were [added to the Go language spec in Go 1.13](https://golang.org/doc/go1.13#language).
