### ISSUE TITLE
error extracting command arguments: couldn't retrieve argument for {Source:payload Name:repository.name EnvName: Base64Decode:false}

### ISSUE THREAD

**Issue by RichaArora93** [adnanh/webhook#496]
using yaml file for hooks configuration and application/json not working for content , only content type application/x-www-form-unrencoded working but getting the argument issue.
Please help

**Comment by RichaArora93** [comment]
error extracting command arguments: couldn't retrieve argument for {Source:payload Name:repository.name EnvName: Base64Decode:false}

**Comment by moorereason** [comment]
What version of webhook?  Can you share your hook rule configuration?  Any information about the request you're processing would be helpful too.

**Comment by RichaArora93** [comment]
Hey there !!!

I am using the webhook version --> webhook version 2.8.0.
As I mentioned earlier it is not working with application/json data format
, returning 403 error code while with content
application/x-www-form-urlenoded in webhook status is 200 but not getting
parameters value.
Here is the simple file i tried both json and yaml format -->

 cat hooks.yaml.example
- id: webhook
  execute-command: /tmp/invoke_ansible.sh
  command-working-directory: /tmp
  response-message: I got the payload!
  response-headers:
  - name: Access-Control-Allow-Origin
    value: '*'
  pass-arguments-to-command:
  - source: payload
    name: repository.name
  - source: payload
    name: repository.id
  trigger-rule:

ERROR --> webhook] 2021/01/05 07:03:48 [5a458d] error extracting command
arguments: couldn't retrieve argument for {Source:payload Name:
repository.name EnvName: Base64Decode:false}
[webhook] 2021/01/05 07:03:48 [5a458d] error extracting command arguments:
couldn't retrieve argument for {Source:payload Name:repository.id EnvName:
Base64Decode:false}
[webhook] 2021/01/05 07:03:48 [5a458d] executing /tmp/invoke_ansible.sh
(/tmp/invoke_ansible.sh) with arguments ["/tmp/invoke_ansible.sh" "" ""]
and environment [] using /tmp as cwd
[webhook] 2021/01/05 07:03:48 [5a458d] command output: hi

Thanks for your help !!

Regards,
Richa Arora

**Comment by moorereason** [comment]
What JSON payload are you receiving?

**Comment by RichaArora93** [comment]
It is a POST method.
Did anyone faced same issue?

**Comment by moorereason** [comment]
The error message says webhook is unable to find `repository.name` in the payload.  I need to see the actual request payload in order to help.  Can you run webhook with the `-debug` flag and share the results?

**Comment by Sagarvt2002** [comment]
Hi there, 
I have my hooks.json as below
[
  {
    "id": "selfheal-webhook",
    "execute-command": "/opt/app/GIT/itoperations/XOPS/AiOpsWebhook/self-heal-routing.sh",
    "command-working-directory": "/tmp",
    "response-message": "CI/CD Job created in Lower Env"
  },
 "pass-arguments-to-command":
      [
        {
          "source": "payload",
          "name": "rtype"
        }
     ]

]
But I am seeing no arguments though pass args 
executing /opt/app/GIT/itoperations/XOPS/AiOpsWebhook/self-heal-routing.sh (/opt/app/GIT/itoperations/XOPS/AiOpsWebhook/self-heal-routing.sh) with arguments ["/opt/app/GIT/itoperations/XOPS/AiOpsWebhook/self-heal-routing.sh"] and environment [] using /tmp as cwd
My CURL Command is:
 curl -H "Content-Type: application/json" "http://catl0xlin24981:9090/hooks/selfheal-webhook?rtype=123"

**Comment by adnanh** [comment]
Change "payload" to "query" in the argument source :)
