### ISSUE TITLE
Problem installing webhook on Linux.

### ISSUE THREAD

**Issue by KPSS123** [adnanh/webhook#498]
Hello team 

I am facing issue in installing webhook with go.

Error Message - 

sudo go build github.com/adnanh/webhook
# github.com/adnanh/webhook/internal/pidfile
../go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:38:54: syntax error: unexpected o755, expecting comma or )
../go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:41:76: syntax error: unexpected o600, expecting comma or )

Please help in resolving this.
Thanks in advance !!!

**Comment by thoo** [comment]
You can download the binary from https://github.com/adnanh/webhook/releases. In my case , I just unzip and place at `/usr/bin/webhook` .
