### ISSUE TITLE
hotreload removed all hooks when pull changes from rep

### ISSUE THREAD

**Issue by Sect0R** [adnanh/webhook#499]
My deployment-hooks.json in github repo.
Webhook runned as `webhook -nopanic -port 55500 -hooks ./deployment-hooks.json  -hotreload`
When I run `git pull` webhook removed all hooks but didn't add new hooks from JSON file

**Comment by moorereason** [comment]
I'm assuming that manually restarting webhook loaded the new hooks, right?

**Comment by Sect0R** [comment]
> I'm assuming that manually restarting webhook loaded the new hooks, right?

yes. manually restarting loaded all new and old hooks

**Comment by moorereason** [comment]
What version of webhook?  What OS?

**Comment by Sect0R** [comment]
**webhook version** 2.6.9
~$ cat /etc/os-release
`
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

~$ lsb_release -a
`
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster`

~$ hostnamectl
` 
Static hostname: ---
         Icon name: computer-vm
           Chassis: vm
    Virtualization: vmware
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-12-amd64
      Architecture: x86-64
`

**Comment by adnanh** [comment]
Ugh, guess the git did unlink and then created new file :/

**Comment by moorereason** [comment]
Yeah, this could be tricky to resolve.  I haven't tried to reproduce this yet, but can you share the verbose logging from webhook when this happens?

For a work-around (and possibly a safer, long-term solution), I would disable hotreload, update to at least v2.7.0, and send a HUP signal to the process after doing a git pull (`kill -HUP $PID` or perhaps `systemctl reload webhook` if using systemd).  That will cause webhook to reload its config (starting in v2.7.0).

**Comment by Sect0R** [comment]
[webhook] 2021/01/18 11:28:50 version 2.6.9 starting
[webhook] 2021/01/18 11:28:50 setting up os signal watcher
[webhook] 2021/01/18 11:28:50 attempting to load hooks from /home/www/deployment/hooks.json
[webhook] 2021/01/18 11:28:50 os signal watcher ready
[webhook] 2021/01/18 11:28:50 found 4 hook(s) in file
[webhook] 2021/01/18 11:28:50 	loaded: platform
[webhook] 2021/01/18 11:28:50 	loaded: admin_app
[webhook] 2021/01/18 11:28:50 	loaded: base_app
[webhook] 2021/01/18 11:28:50 	loaded: users_api_server
[webhook] 2021/01/18 11:28:50 setting up file watcher for /home/www/deployment/hooks.json
[webhook] 2021/01/18 11:28:50 serving hooks on http://0.0.0.0:55500/hooks/{id}
[webhook] 2021/01/18 11:29:46 hooks file /home/www/deployment/hooks.json removed, no longer watching this file for changes, removing hooks that were loaded from it
[webhook] 2021/01/18 11:29:46 	removing: platform
[webhook] 2021/01/18 11:29:46 	removing: admin_app
[webhook] 2021/01/18 11:29:46 	removing: base_app
[webhook] 2021/01/18 11:29:46 	removing: users_api_server
[webhook] 2021/01/18 11:29:46 removed 4 hook(s) that were loaded from file /home/www/deployment/hooks.json
```

**Comment by moorereason** [comment]
I'm leaning towards labeling this as `wontfix`.  Trying work around this by checking if a previously deleted config file was recreated feels like a hack.  I would recommend following the work-around advice in my previous comment instead of using hotreload.

@adnanh, what are your thoughts?

**Comment by adnanh** [comment]
Yeah, I deliberately didn't implement that for this behavior, as it complicates the implementation, and introduces some edge cases. This behavior is also true for some text editors... Best option is to use the described workaround.
