### ISSUE TITLE
Question on Travis CI and project scope

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#50]
I was going to submit changes (something like [this](https://github.com/atotto/travisci-golang-example/blob/master/.travis.yml)) to enable Travis CI testing until I noticed that there's tons of Docker stuff in the existing `.travis.yml` file.  So, I wanted to open a discussion about the scope of this repository.

There's no connection between Docker and webhook, and I don't think the files contributed by @almir belong in this repo.  While they may be useful to some, they are out of place in this repo IMHO.  I'd suggest @almir create his own `webhook-docker` repo for the Docker config.  His Dockerfile could be updated to git-pull the repo before building.  The webhook README or from the wiki pages could link to his repo to make it easier for people to find him work.

Additionally, I've had the misfortune of maintaining RPM specs in the past in a similar situation, and I don't care to go down that road again.  I mean no offense to @timhughes, who did all the heavy lifting, but that's the distro package maintainer's job, and the spec file doesn't belong in the webhook repo.  There's too may distros and too many variations; that noise belongs somewhere else.

I feel the same way about the init script contributed by @timhughes.  Are we going to need to add and maintain a systemd config? nosh? upstart?  Run away!!

If nothing else, I'd like to see these contributions moved to a `contrib` folder, which historically means "we're not maintaining these files, but you can try them if you want..good luck."

I'm only a contributor like everyone else (well, except @adnanh).  I'm empathetic to @timhughes and @almir since I know the work that goes into creating and submitting their changes to this project.  I don't mean to discourage people from contributing.  I'm just worried that the repo is going to turn into a hodgepodge of hacks to get webhook running in everyone's favorite environment when those hacks really belong somewhere else.

**Comment by adnanh** [comment]
Totally agree with you. I think the best solution would be to create a `webhook-contrib` repository where developers could contribute their webhook-oriented stuff that others might find useful, ranging from build spec files to hooks.json management tools. This repo should only contain the webhook source code...

**Comment by timhughes** [comment]
More than fine by me.

**Comment by adnanh** [comment]
:+1:

**Comment by adnanh** [comment]
I've simply moved files to [webhook-contrib](https://github.com/adnanh/webhook-contrib) in their separate folders. They probably need an adjustment now, since they are not in the same repo as the source code. @timhughes @moorereason @almir
