### ISSUE TITLE
Ubuntu package outdated (v2.6.9)

### ISSUE THREAD

**Issue by ahousseini** [adnanh/webhook#500]
The upstream package is outdated when installing with `sudo apt-get install webhook`

**Comment by adnanh** [comment]
**/cc** @freeekanayaka

**Comment by justingivens** [comment]
How could we get this updated to 2.8? There are a couple of features missing in 2.6.9 that are in 2.8 that would be nice to have.

I'm happy to help.

**Comment by ahousseini** [comment]
Any news on this?

**Comment by ahousseini** [comment]
If anyone is interested: I built it with go and created a service manually with `supervisor` to use the newest version.

This article helped me a lot: https://willbrowning.me/setting-up-automatic-deployment-and-builds-using-webhooks/

**Comment by freeekanayaka** [comment]
Sorry for the late reply. I've updated the webhook [package in Debian](https://packages.debian.org/sid/webhook) to version 2.8.0.

**Comment by adnanh** [comment]
> Sorry for the late reply. I've updated the webhook [package in Debian](https://packages.debian.org/sid/webhook) to version 2.8.0.

Fantastic news! Thank you very much!
