### ISSUE TITLE
Issue with  go get github.com/adnanh/webhook

### ISSUE THREAD

**Issue by toppylawz** [adnanh/webhook#507]
When I tried getting the webhook according to [this ](https://medium.com/better-programming/how-to-automatically-deploy-from-github-to-server-using-webhook-79f837dcc4f4) tutorial, with the code  `go get github.com/adnanh/webhook` I get the error 

```
github.com/adnanh/webhook/internal/pidfile
go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:38:54: syntax error: unexpected o755, expecting comma or )
go/src/github.com/adnanh/webhook/internal/pidfile/pidfile.go:41:76: syntax error: unexpected o600, expecting comma or )
```

**Comment by moorereason** [comment]
webhook requires Go 1.14.
