### ISSUE TITLE
Problem pass-arguments-to-command, question parse-parameters-as-json

### ISSUE THREAD

**Issue by no1bob** [adnanh/webhook#511]
Hi, made relatively simple hook and it **works but problem is**:
   CAN NOT get "pass-arguments-to-command" to work anyhow?!

```
[webhook] 2021/02/15 05:15:09 [78d2e1] error extracting command arguments: couldn't retrieve argument for {Source:payload Name:message EnvName: Base64Decode:false}
```

**OS**: Win10
**Command**:
```
curl -H 'Content-Type: application/json; charset=utf-8' -d '{message%3D%7B%22anyname1%22%3A%22ANYDATA1%22%2C%22anyname2%22%3A%22ANYDATA2%22%2C%22anyname3%22%3A%22ANYDATA13%22%7D}' -X POST http://192.168.8.101:9000/hooks/tvhook
```
or
```
curl -H 'Content-Type: application/json; charset=utf-8' -d '{message={"anyname1":"ANYDATA1","anyname2":"ANYDATA2","symbol":"ANYDATA3"}}' -X POST http://192.168.8.101:9000/hooks/tvhook
```
or
without "message="

**Hook**:
```
[
   {
      "id":"tvhook",
      "execute-command":"balert.bat",
      "command-working-directory":"c:/",
      "http-methods":[
         "Post "
      ],
      "include-command-output-in-response":false,
      "response-message":"success",
      "trigger-rule-mismatch-http-response-code":400,
     
      "pass-arguments-to-command":[
         {
        "source": "payload",
        "name": "message"
      }
      ]
   }
]
```
I tried 100x changing almost everything but always same result. Suspected in incompatible libraries so downloaded compiled webhook 2.8 but again the same. Since pass arguments do not work wasnt able to parse parameters as well (wish to parse and send command, as  ANYDATA1, ANYDATA2...)  (or should I try/use "pass-environment-to-command"?) 

**What I  doing wrong  or whats wrong??** _Please help._

**Comment by no1bob** [comment]
**Go**:  version 1.15.6 windows/amd64

**Comment by moorereason** [comment]
You must send valid JSON in the payload.  Use a JSON validator to make sure you're doing that right.  Try something like this:

```
curl -H 'Content-Type: application/json; charset=utf-8' -d '{"message":{"anyname1":"ANYDATA1","anyname2":"ANYDATA2","symbol":"ANYDATA3"}}' -X POST http://192.168.8.101:9000/hooks/tvhook
```

**Comment by no1bob** [comment]
already tested that  but will ty again and post result

**Comment by no1bob** [comment]
sent: curl -H 'Content-Type: application/json; charset=utf-8' -d '{"message":{"anyname1":"ANYDATA1","anyname2":"ANYDATA2","symbol":"ANYDATA3"}}' -X POST http://192.168.8.100:9000/hooks/tvhook

response:
[webhook] 2021/02/16 18:56:17 [a00c94] error occurred: exit status 1
[webhook] 2021/02/16 18:56:17 [a00c94] finished handling tvhook
[webhook] 2021/02/16 19:01:53 [93f390] incoming HTTP POST request from 192.168.8.102:8679
[webhook] 2021/02/16 19:01:53 [93f390] tvhook got matched
[webhook] 2021/02/16 19:01:53 [93f390] tvhook hook triggered successfully
[webhook] 2021/02/16 19:01:53 [93f390] 200 | 7 B | 2.9388ms | 192.168.8.100:9000 | POST /hooks/tvhook
[webhook] 2021/02/16 19:01:53 [93f390] error extracting command arguments: couldn't retrieve argument for {Source:payload Name:message EnvName: Base64Decode:false}
[webhook] 2021/02/16 19:01:53 [93f390] executing balert.bat (c:\balert.bat) with arguments ["balert.bat" ""] and environment [] using c:/ as cwd
[webhook] 2021/02/16 19:01:54 [93f390] command output:
c:\>echo ""

so the same, what else could be wrong ?!

**Comment by no1bob** [comment]
Problem is in syntax how windows send/reead cURL !!!
(finally resolved thanks to https://stackoverflow.com/questions/11834238/curl-post-command-line-on-windows-restful-service)

so the right way is: 
**curl** -H "Content-Type:application/json" -d "{\"message\":{\"anytest1\":\"hi\",\"anytest2\":\"bye\"}}" -X POST http://localhost:9000/hooks/tvhook

Great thanks for support to @adnanh &  @moorereason :)
