### ISSUE TITLE
Open ended Q, getting NULL payload

### ISSUE THREAD

**Issue by ICUMD** [adnanh/webhook#536]
Hi all,

I have been trying to receive webhooks from AppDynamics. For some reason, I am seeing "null" as the incoming payload argument. Any idea what reasons may cause this ? Anyone else faced this issue or did anyone else used it to integrate with AppDynamics?

**Comment by moorereason** [comment]
What version of webhook are you using?  Have you tried using the `-debug` flag?

**Comment by ICUMD** [comment]
@moorereason Yup tried the -debug flag instead of verbose. Caught this error "error parsing JSON payload invalid character 'â' looking for beginning of value". Looks like it's an encoding issue, any idea how to resolve it?

**Comment by ICUMD** [comment]
@moorereason the payload is encoded in UTF-8

**Comment by moorereason** [comment]
What version?  Can you share your config and a sample payload?

**Comment by ICUMD** [comment]
I am using **version 2.8.0**

Here's the config for the hook:

  {
    "id": "appdynamics_alerts",
    "execute-command": "/etc/webhook/sdg_appdynamics.sh",
    "pass-arguments-to-command":
      [
        {
          "source": "entire-payload"
        }
      ]
  }

Here's the payload and other details from the sender (AppDynamics):

Content-Type: application/json; charset=UTF-8
User-Agent: Apache-HttpClient/4.5.13 (Java/1.8.0_282)
Accept-Encoding: gzip,deflate
Request Payload:   
{
  "service" : "labs/42",
  “alert_type" : “POLICY_CONTINUES_CRITICAL",
  "severity" : "minor",
  "message" : "Sample Event Message",
  "timestamp" : "Tue May 18 11:51:49 PDT 2021",
  "alert_id" : "551"
}
Response Status Line:    HTTP/1.1 200 OK

AppDynamics does both URL and payload encoding with UTF-8

Thanks for responding.

**Comment by moorereason** [comment]
The payload you provided has a couple fancy double-quotes on the `alert_type` line.  I'm assuming that's a typo since it's not valid JSON.  Can you confirm?

UTF-8 shouldn't be a problem.

**Comment by ICUMD** [comment]
That's a great catch, I'll confirm if indeed this json is being used. Thanks

**Comment by ICUMD** [comment]
@moorereason That was the cause. Thanks again.
