### ISSUE TITLE
Execute sh as different user

### ISSUE THREAD

**Issue by kerim92** [adnanh/webhook#541]
Hi,

Thank you very much for building such as good webhook server.

i am really very beginner of linux servers and webhooks and i am trying to understand how to run sh script file as different user.

i have a laravel project running on ubuntu 20.04 + nginx server.
as you know composer should not run as root must be user under www-data group or somethink like this.
and also i am using php artisan commands the user, under group of www-data

when i browse my domain with following address everythink looks good.

http://mydomain.tk:9000/hooks/kerim?token=42&subdomain=derkleine

![image](https://user-images.githubusercontent.com/56412326/123526838-2dd84300-d6e3-11eb-80ff-bd318d27c4b1.png)

my sh file running php artisan command and the command creating a  .env file and some folders under storage folder.

but the file and folders creating as root user. 

![Screenshot_1](https://user-images.githubusercontent.com/56412326/123526942-f7e78e80-d6e3-11eb-8269-a7870e11e991.png)

my webhook.conf file:
[
  {
    "id": "kerim",
    "execute-command": "/var/www/ikacreatecustomer.sh",
    "response-message": "Executing simple webhook...",
    "pass-arguments-to-command":[
      {
        "source": "url",
        "name": "subdomain"
      }
    ],
    "trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "42",
        "parameter":
        {
          "source": "url",
          "name": "token"
        }
      }
    }
  }
]

can you please explain me to create files and folders as my www-data user (very basic)

i have little search to run command as different user but i am not able to success.

i am not sure to open this issue(question) here or on stackoverflow or laravel forums. i wanted to try my chance first here :) 
You can simply close issue (question) if i am wrong place.

Thank you,
Kerim

**Comment by adnanh** [comment]
Well, the easiest way would be to prefix your commands in your shell scripts with `sudo -i -u desireduser yourcommand`
