### ISSUE TITLE
HELP! How to send parameters via webhook?

### ISSUE THREAD

**Issue by DgoNascimento** [adnanh/webhook#543]
Good afternoon people,

Could you help me add a variable input via the webhook?

In the json file, I run a shell script that needs a variable as input, but I can't send this value via the webhook url.

```
[
  {
    "id": "restart-service",
    "execute-command": "/tmp/monitoring/restart-service.sh",
    "response-message": "I got the payload!",
    "include-command-output-in-response": true,
        "trigger-rule":
        {
      "and":
      [
            {
          "match":
          {
                      "type": "ip-whitelist",
                      "ip-range": "127.0.0.1/32"
                  }
                }
       ]
        }
  }
]
```

```
#!/bin/sh
servico=$1
STS=`systemctl status $servico |grep Active: |grep running |wc -l`

if [ $servico ! "" ]
then
        echo "Servico nao definido" >> /tmp/monitoring/web_node.log
else
...
```
How could I send this necessary value for the script, through the webhook?

Thank you in advance

**Comment by DgoNascimento** [comment]
@adnanh, could support? Thank you!

**Comment by moorereason** [comment]
See [Pass string arguments to command](https://github.com/adnanh/webhook/blob/master/docs/Hook-Examples.md#pass-string-arguments-to-command)

**Comment by DgoNascimento** [comment]
Hi @moorereason 
Thanks for the feedback and the tip.

However, I would like to use a variable external to the webhook, which I could send in the url.

I would like to use the alertmanager, where the process is restarted, it would be sent by it.

Thanks again!

**Comment by DgoNascimento** [comment]
before setup i received this message:

executing /tmp/monitoring/restart-service.sh (/tmp/monitoring/restart-service.sh) with arguments ["/tmp/monitoring/restart-service.sh"] and environment [] using  as cwd

after setup i got this message:
executing /tmp/monitoring/restart-service.sh (/tmp/monitoring/restart-service.sh) with arguments ["/tmp/monitoring/restart-service.sh" "*" ""] and environment [] using  as cwd

new configuration hooks.json:
[
  {
    "id": "restart-service",
    "execute-command": "/tmp/monitoring/restart-service.sh",
    "response-message": "I got the payload!",
    "include-command-output-in-response": true,
        "pass-arguments-to-command":
        [
           {
             "source": "string",
                 "name": "*"
                },
           {
             "source": "payload",
                 "name": "pusher.email"
                }
        ],
        "trigger-rule":
        {
      "and":
      [
            {
          "match":
          {
                      "type": "ip-whitelist",
                      "ip-range": "127.0.0.1/32"
                  }
                }
       ]
        }
  }
]


Regardless of the configuration, I get the error messages:

error parsing body payload due to unsupported content type header:
error extracting command arguments: couldn't retrieve argument for {Source:payload Name:pusher.email EnvName: Base64Decode:false}

**Comment by moorereason** [comment]
A few things:
1. What version of webhook are you running?
1. I don't understand what command you're meaning to execute.  If you were executing the script by hand, what would you run?
2. It looks like the Content-Type header is missing.  Try setting `incoming-payload-content-type` to `application/json`.  See [Hook Definition](https://github.com/adnanh/webhook/blob/master/docs/Hook-Definition.md) docs.

**Comment by DgoNascimento** [comment]
Hi,

1- Version: webhook version 2.8.0
2- I plan to use it with alertmanager, to restart the service that over the network for it. Running by hand, it would look like this:
/tmp/monitoring/restart-service.sh <service>
[root@dgo monitoring]# ./restart-service.sh node_exporter
Processo node_exporter sendo executado

3- When setting input-payload-content-type in json file, I get error starting webhook:
settings in json file:
    "incoming-payload-content-type': "application/json",
error starting:
couldn't load hooks from file! error converting YAML to JSON: yaml: line 4: did not find expected ',' or '}'

If you don't configure it in the json file, I make the call with the parameters (-H "Content-Type: application/json"), I get other errors:
error parsing JSON payload EOF
error extracting command arguments: couldn't retrieve argument for {Source:payload Name:pusher.email EnvName: Base64Decode:false}

**Comment by adnanh** [comment]
> Hi,
> 
> 1- Version: webhook version 2.8.0
> 2- I plan to use it with alertmanager, to restart the service that over the network for it. Running by hand, it would look like this:
> /tmp/monitoring/restart-service.sh
> [root@dgo monitoring]# ./restart-service.sh node_exporter
> Processo node_exporter sendo executado
> 
> 3- When setting input-payload-content-type in json file, I get error starting webhook:
> settings in json file:
> "incoming-payload-content-type': "application/json",
> error starting:
> couldn't load hooks from file! error converting YAML to JSON: yaml: line 4: did not find expected ',' or '}'
> 
> If you don't configure it in the json file, I make the call with the parameters (-H "Content-Type: application/json"), I get other errors:
> error parsing JSON payload EOF
> error extracting command arguments: couldn't retrieve argument for {Source:payload Name:pusher.email EnvName: Base64Decode:false}

You have a trailing `'` instead of `"`

**Comment by DgoNascimento** [comment]
you're right. But still we have the errors below:
error parsing JSON payload EOF
error extracting command arguments for environment: couldn't retrieve argument for {Source:url Name:parameter-name EnvName: Base64Decode:false}
executing /tmp/monitoring/restart-service.sh (/tmp/monitoring/restart-service.sh) with arguments ["/tmp/monitoring/restart-service.sh"] and environment [] using  as cwd

Follow the configuration:
[
  {
    "id": "restart-service",
    "execute-command": "/tmp/monitoring/restart-service.sh",
    "include-command-output-in-response": true,
    "incoming-payload-content-type": "application/json",
        "pass-environment-to-command":
        [
           {
             "source": "url",
                 "name": "parameter-name"
                },
        ],
        "trigger-rule":
        {
      "and":
      [
            {
          "match":
          {
                      "type": "ip-whitelist",
                      "ip-range": "127.0.0.1/32 192.168.200.79/32 172.21.9.31/32"
                  }
                }
       ]
        }
  }
]

**Comment by adnanh** [comment]
Can you post payload you're receiving?

**Comment by DgoNascimento** [comment]
The result I get is (as if I wasn't sending the necessary parameter for the script to execute):

Servico nao definido

Running the script by hand, without the parameter: 
[root@dgo monitoring]# ./restart-service.sh 
Servico nao definido

Running the script by hand, with the parameter:
[root@dgo monitoring]# ./restart-service.sh node_exporter
Processo node_exporter sendo executado

**Comment by adnanh** [comment]
I meant the payload you're sending to the webhook endpoint. What are you sending to the `restart-service` hook endpoint?

Try this hook definition:
```
[{
	"id": "restart-service",
	"execute-command": "/tmp/monitoring/restart-service.sh",
	"include-command-output-in-response": true,
	"incoming-payload-content-type": "application/json",
	"pass-arguments-to-command": [{
		"source": "url",
		"name": "parameter-name"
	}],
	"trigger-rule": {
		"and": [{
			"match": {
				"type": "ip-whitelist",
				"ip-range": "127.0.0.1/32 192.168.200.79/32 172.21.9.31/32"
			}
		}]
	}
}]
```

And then invoking `http://127.0.0.1:9000/hooks/restart-service?parameter-name=node_exporter

**Comment by DgoNascimento** [comment]
Hi @adnanh,

I greatly appreciate your willingness and help!
That's exactly what I was looking for.

I was trying different ways, but changing the parameter-name to other labels.

Thank you very much!
