### ISSUE TITLE
How to support CORS in HTML?

### ISSUE THREAD

**Issue by stilleshan** [adnanh/webhook#546]
Sorry about my english...

I had install webhook and works fine. I set a domain reverse proxy to webhook with nginx.

Now i can use "curl -X POST https://mydomain.com/hook/test?token=xxxxx -d '{"xxx","xxx"}'"  in terminal to trigger hooks and it's worked

When i use ajax in html to send post to webhook. the webhook had trigger and it's worked , but it show CORS error.

<img width="845" alt="截屏2021-07-27 18 29 47" src="https://user-images.githubusercontent.com/22582966/127140390-020e0cca-2730-41cd-963b-f07d0751fd90.png">

<img width="1211" alt="截屏2021-07-27 18 30 31" src="https://user-images.githubusercontent.com/22582966/127140400-456d750c-5bbf-4a0e-9eb7-166c7d995926.png">

My website is "https://abc.net" , but my webhook's domain is "https://efg.com"

Now what can i do can let it support CORS? 

```
			<script>
				$(document).ready(function() {
					$("#accept").click(function() {
						var token = $("#token").val();
						var data = {};
						var value = $('#datainfo').serializeArray();
						$.each(value, function (index, item) {
							data[item.name] = item.value;
						});
						var postData = JSON.stringify(data);
						console.log('data : ',data);
						$.ajax({
							url:"https://efg.com/hooks/func?token="+token,
							type:'POST',
							dataType:'json',
							contentType :'application/json; charset=utf8',
							data: postData
						});
					});
				});
			</script>
```

**Comment by moorereason** [comment]
You can send back custom headers with the `response-headers` option.  You can see an example of that at https://github.com/adnanh/webhook/blob/master/docs/Templates.md#example-usage.

**Comment by stilleshan** [comment]
> You can send back custom headers with the `response-headers` option. You can see an example of that at https://github.com/adnanh/webhook/blob/master/docs/Templates.md#example-usage.

I add response-headers option. but still CORS error , I think maybe need to configure some opthion by ajax  or  configure nginx conf file

**Comment by fkcptlst** [comment]
Hi, have you solved it? I'm encountering similar issue.
