### ISSUE TITLE
Blog featuring Webhook implementation.

### ISSUE THREAD

**Issue by Anksus** [adnanh/webhook#547]
I have written a blog on how to implement webhook with Github in production environment. Please add it to the README . https://anksus.me/blog/integrate-automatic-deployment-in-20-minutes-using-webhooks

**Comment by Anksus** [comment]
should I create a PR?

**Comment by adnanh** [comment]
Yes please :-)

**Comment by Anksus** [comment]
I created a PR. 
https://github.com/adnanh/webhook/pull/559

**Comment by adnanh** [comment]
Thank you!
