### ISSUE TITLE
Execute a simple command inline defined in hooks.json instead of in a separate script

### ISSUE THREAD

**Issue by mokanfar** [adnanh/webhook#552]
How can I just do this instead of calling a shell script? 
example I am trying:
```json
[
  {
    "id": "foo",
    "execute-command": "/bin/bash open -a 'Slack'"
  }
]

```

result:
`[webhook] 2021/08/19 18:54:55 [53f0a5] error in exec: "/bin/bash open -a 'Slack'": stat /bin/bash open -a 'Slack': no such file or directory
[webhook] 2021/08/19 18:54:55 [53f0a5] use 'pass-arguments-to-command' to specify args for '/bin/bash'`

**Comment by moorereason** [comment]
See [docs/Hook-Examples.md](https://github.com/adnanh/webhook/blob/master/docs/Hook-Examples.md#pass-string-arguments-to-command)

**Comment by mokanfar** [comment]
thanks leaving this here for others who have ADD:

```json
[
  {
    "id": "foo",
    "execute-command": "/bin/bash",
    "pass-arguments-to-command":   [
      {
        "source": "string",
        "name": "-c"
      },
       {
        "source": "string",
        "name": "open -a Slack"
      }
    ]
  }
]
```
