### ISSUE TITLE
Sane default hooks.json for packaging?

### ISSUE THREAD

**Issue by classabbyamp** [adnanh/webhook#560]
I'm working on packaging webhook for [void linux](https://voidlinux.org), and I'd like to include a sane, simple default hooks.json for users of the package. All of the current examples in the repo are a bit too complex and specific for that purpose.

Do you have any suggestions?

**Comment by adnanh** [comment]
Hmm, I'm not really sure what a sane default would be for this case, since it could easily turn into an "unwanted information disclosure" issue :|

Maybe a simple script that returns current time by calling `/bin/date`?

**Comment by classabbyamp** [comment]
yeah that would be simple enough, thanks
