### ISSUE TITLE
ip range from file

### ISSUE THREAD

**Issue by chanyshev** [adnanh/webhook#563]
Hello,
I want to secure the webhook by adding the ip range that I get from here https://api.github.com/meta
How can I do this?

**Comment by moorereason** [comment]
You could accomplish this with the `-hotreload` and `-template` options...**EXCEPT** for the fact that we don't provide a `readFile` template function.  [I had that idea a while back](https://github.com/adnanh/webhook/issues/290#issuecomment-447361334) but never implemented it.

**Comment by chanyshev** [comment]
@moorereason Thanks for the answer, I solved this problem using a firewall
