### ISSUE TITLE
Accessing environment variables

### ISSUE THREAD

**Issue by markhowells** [adnanh/webhook#57]
I'm using webhook in a docker container.  The hook has to store some data from bitbucket into etcd.  Is there any way I can access environment variables passed into the docker container (notably ETCDCTL_ENDPOINT in my case) from within my hook script?  Right now I'm using a bit of a kludge by having a run.sh file save the relevant variables into a file, then launching webhook, and then accessing the contents of the file when the hook is invoked.  I'd really like to define the hook - passing in environment variables along the lines of

"pass-parameter-to-command":
    [
      {
        "source": "environment",
        "name": "ETCDCTL_ENDPOINT"
      }

or using pass-environment-to-command in some way?

**Comment by markhowells** [comment]
Errr, I seem to have misunderstood.  The deploy script can access passed in environment variables. I would still like to be able to map env vars. to passed in parameters though.

**Comment by moorereason** [comment]
Some changes were merged an hour before this issue was created that should fix Issue #53.  Is that the same issue you are describing?  If so, please update to the latest revision and see if that fixes your issue.

**Comment by markhowells** [comment]
Lol.  That explain a lot :)  It has indeed fixed the problem I saw. Thanks

I'll close the issue now.
