### ISSUE TITLE
Cannot build webhook

### ISSUE THREAD

**Issue by fbartels** [adnanh/webhook#58]
Hi, I just updated my local checkout to the latest version, but cannot build webhook anymore. I have previously built version 2.3.5 with the same steps.

```
$ git rev-parse master
8de1a519269b2171f925d085e744ddc7167effa8
$ go version
go version go1.3.3 linux/arm
$ go build
# _/.../git/webhook
./webhook.go:183: h.ParseJSONParameters(&headers, &query, &payload) used as value
./webhook.go:197: assignment count mismatch: 2 = 1
./webhook.go:238: assignment count mismatch: 2 = 1
./webhook.go:244: h.ExtractCommandArgumentsForEnv undefined (type *hook.Hook has no field or method ExtractCommandArgumentsForEnv) 
```

**Comment by adnanh** [comment]
It looks like your repository is somehow out of sync. 

Building webhook with go 1.3.3 (on linux/amd64 though, but it shouldn't matter) works for me without any problems.

```
➜  webhook git:(master) ✗ git rev-parse master
8de1a519269b2171f925d085e744ddc7167effa8
➜  webhook git:(master) ✗ go version
go version go1.3.3 linux/amd64
➜  webhook git:(master) ✗ go build
➜  webhook git:(master) ✗ ~/projects/go/bin/webhook -verbose
[webhook] 2015/11/20 10:14:31 version 2.3.6 starting
```

Could you please try deleting the webhook, clone the repository again and then try building the webhook again?

**Comment by fbartels** [comment]
Hi, thanks for you fast reply, it took some time to test your answer, but now I have finally been able to build webhook again. Removing the actual git repo did not change anything, but removing the second checkout from my gopath, and reissuing "go get github.com/adnanh/webhook" did the trick.

**Comment by adnanh** [comment]
Awesome :-)
