### ISSUE TITLE
ip-whitelist seems not to work

### ISSUE THREAD

**Issue by StephanHarrer** [adnanh/webhook#584]
Hello,

I did several test with ip-address whitelist but seems not to work. Here is my config:
```
[
   {
      "id": "mein_webhook",
      "execute-command": "/usr/local/custom/webhook/pytest.py",
      "command-working-directory": "/usr/local/custom/webhook/",
      "pass-arguments-to-command":
      [
        {
          "source": "entire-payload"
        }
      ],
      "trigger-rule":
        { "match": { "type": "ip-whitelist", "ip-range": "192.168.10.0/24" } }
   }
]
```

same with `{ "match": { "type": "ip-whitelist", "ip-range": "192.168.10.2/32" } }` => Match one exact ip address.

In both cases the trigger not match regarding the "-verbose" output.
Whitout trigger-rule all works fine.

Source of the hook request is 192.168.10.2 

Regards
Stephan

**Comment by Mikecarbon** [comment]
.92

**Comment by Mikecarbon** [comment]
.397

**Comment by moorereason** [comment]
@StephanHarrer, what version of webhook are you running?  Can you enable and share debug output?

**Comment by StephanHarrer** [comment]
Hello @moorereason ,

sorry for the inconvenience. I was so naive to think that I get the latest version with the official package of Ubuntu.

The Ubuntu package has the version 2.5.0-2, with this the error occurs. Now I have the pre build package of version 2.8.0 in use and now everything works!!!

Thanks for pushing me in the right direction.

Regards
Stephan
