### ISSUE TITLE
How to make it more secure? I just copy-paste script from Hook-Examples.md

### ISSUE THREAD

**Issue by nyngwang** [adnanh/webhook#587]
I'm concerned about Github webhook, and the following is the only related part related to my question:

Can I change `"name"` to `"X-Hub-Signature-256"` to try to make it more secure? I read a thread from issues saying that this is more secure. Any advice?

```json
{
  "match":
  {
    "type": "payload-hmac-sha1",
    "secret": "******",
    "parameter":
    {
      "source": "header",
      "name": "X-Hub-Signature"
    }
  }
},
```

**Comment by adnanh** [comment]
Sure, just make sure you adjust the `"type"` accordingly to a `"payload-hmac-sha256"`
