### ISSUE TITLE
Passing arguments of the format [-st string]

### ISSUE THREAD

**Issue by alexkfarrell** [adnanh/webhook#593]
Thank you for you work!

I want to run a program like `python webhook_test.py -st string -v` where "-st" is the name of the input but to run the program still requires the entire "-st 'some string to pass for the argument'" argument to function. I've added my .json hook definition.

`[
 {
  "id": "test-webhook",
   "execute-command": "/home/duty/Desktop/webhook_test.py",
   "incoming-payload-content-type": "application/json",
   "response-message": "Success\n",
   "command-working-directory": "/home/duty/Desktop",
   "pass-arguments-to-command":
   [
    {
     "source": "payload",
     "name": "-v"
    },
    {
     "source": "payload",
     "name": "-st"
    }
   ]
 }
]`

I'm using the following to call the webhook: `curl -H "Content-Type: application/json" -X POST -d '{"-st":"-st 'Hello'", "-v":"-v"}' http://hook_ip:9000/hooks/test-webhook`

However, when the webhook calls the Python code, it sends the input for -st as "-st Hello" and not as -st 'Hello' which therefore doesn't allow the program to run correctly.
This makes the program call `python webhook_test.py "-st Hello" -v` instead of what I need, `python webhook_test.py -st "Hello" -v`

Any help would be greatly appreciated, and please let me know if you need more information.

**Comment by adnanh** [comment]
Would this work:

```json
[{
	"id": "test-webhook",
	"execute-command": "/home/duty/Desktop/webhook_test.py",
	"incoming-payload-content-type": "application/json",
	"response-message": "Success\n",
	"command-working-directory": "/home/duty/Desktop",
	"pass-arguments-to-command": [{
		"source": "string",
		"name": "-v"
	}, {
		"source": "string",
		"name": "-st"
	}, {
		"source": "payload",
		"name": "-st"
	}]
}]
```

and 

```bash
curl -H "Content-Type: application/json" -X POST -d '{"-st":"Hello"}' http://hook_ip:9000/hooks/test-webhook
```

**Comment by alexkfarrell** [comment]
Thank you - this is exactly what I needed!
