### ISSUE TITLE
change port not working 

### ISSUE THREAD

**Issue by beimengyeyu** [adnanh/webhook#599]
https://github.com/adnanh/webhook/blob/master/docs/Webhook-Parameters.md
-port not working
<img width="771" alt="image" src="https://user-images.githubusercontent.com/107797432/184626148-491e6f32-c092-49d7-a632-e5401fa3f46c.png">

**Comment by beimengyeyu** [comment]
centos 8

**Comment by moorereason** [comment]
What version of webhook?

**Comment by beimengyeyu** [comment]
> What version of webhook?

2.8.0

**Comment by adnanh** [comment]
Try starting with: `./webhook -hooks hooks.json -port 8888 -verbose`
