### ISSUE TITLE
how to get the webhook body

### ISSUE THREAD

**Issue by SrIzan10** [adnanh/webhook#609]
hey, is there any way to get the webhook body? like, what github sends to the server

**Comment by stevetrease** [comment]
I’ve just figured this out. It is documented under special cases on this page. ]][https://github.com/adnanh/webhook/blob/master/docs/Referencing-Request-Values.md](url)

If you want to pass the entire payload as JSON string to your command you can use

{
  "source": "entire-payload"
}

**Comment by adnanh** [comment]
Or alternatively you can pass the raw request body as a file to your command and then do whatever you need to do with it.

In your hook definition add:
`"pass-file-to-command": [ { "name": "something", "source": "raw-request-body" } ]`
and the filename with the body contents will be available in your command as an environment variable HOOK_SOMETHING

Keep in mind that it will be automatically deleted after the hook is done with execution.
