### ISSUE TITLE
trying to use YAML

### ISSUE THREAD

**Issue by Techmahindro** [adnanh/webhook#612]
i am trying to use a hooks.yaml file instead of hooks.json but i am getting the error when loading the webhook

[webhook] 2022/11/23 11:12:32 version 2.8.0 starting
[webhook] 2022/11/23 11:12:32 setting up os signal watcher
[webhook] 2022/11/23 11:12:32 attempting to load hooks from hook3.yaml
[webhook] 2022/11/23 11:12:32 os signal watcher ready
[webhook] 2022/11/23 11:12:32 couldn't load hooks from file! error unmarshaling JSON: json: cannot unmarshal object into Go value of type hook.Hooks
[webhook] 2022/11/23 11:12:32 serving hooks on https://0.0.0.0:9000/hooks/{id}
[webhook] 2022/11/23 11:17:32 [6a2470] incoming HTTP POST request from 172.17.12.16:33957
[webhook] 2022/11/23 11:17:32 [6a2470] 404 | 15 B | 51.874µs | 172.27.27.4:9000 | POST /hooks/testing_start

What am I doing wrong?

**Comment by msglueck** [comment]
```
- id: some-hook
  execute-command: "/opt/some_command.py"
```
works for me. maybe post your config so we can see what you're trying to achieve

**Comment by msglueck** [comment]
otherwise this https://github.com/adnanh/webhook/blob/master/hooks.yaml.example is a very good starting point
