### ISSUE TITLE
Webhook is inactive (dead)

### ISSUE THREAD

**Issue by st3fus** [adnanh/webhook#613]
Hey there, having some issues with webhook executing my deploy.sh script, i get a 200 as response but the script isnt executed. (I can see that since when I make some changes to my app, I have to manually run the script. I'll paste my scrips and files here so you can see them. I did check other similar threads but those didn't help me.

hooks.json file:

```
[
  {
    "id": "autodeploy",
    "execute-command": "/home/ubuntu/datadrill-infra-apps/deliverko/staging/deploy.sh",
    "command-working-directory": "/home/ubuntu/datadrill-infra-apps/deliverko/staging/",
    "response-message": "Executing deploy script..."
  }
]
```

webhook.service file:

```
[Unit]
Description=Webhooks

[Service]
ExecStart=/usr/bin/webhook -hooks /home/ubuntu/datadrill-infra-apps/deliverko/staging/webhooks/hooks.json -hotreload

[Install]
WantedBy=multi-user.target
```

deploy.sh:
```
#!/bin/bash

sudo docker compose pull
sudo docker compose -f docker-compose.yml --env-file .env down
sudo docker compose -f docker-compose.yml --env-file .env up -d
```

ngnix.conf: (It's not a whole file, just copied the line that I added for webhook, these lines are under server { )

```
location /hooks/ {
			proxy_pass http://127.0.0.1:9000/hooks/;
	    }

```
Output of systemctl status webhook.service:
![image](https://user-images.githubusercontent.com/112018215/205337088-dbe976fc-aeb0-48bd-ad50-6d8221e72b35.png)

Any ideas what else can I try?

**Comment by moorereason** [comment]
Add `-verbose` to the `ExecStart` command in your `webhook.service` unit file.  You should see logs of incoming connections.

**Comment by st3fus** [comment]
I made it work, now I got another problem on another EC2 instance...

sudo apt-get install webhook is returning this:
![image](https://user-images.githubusercontent.com/112018215/212058868-b1baddf5-f874-4b2d-90ac-dc27f5d2b627.png)

Any ideas whats wrong?

**Comment by st3fus** [comment]
![image](https://user-images.githubusercontent.com/112018215/212060792-625772ba-604e-4085-b6aa-02ecc0b2e7ad.png)

I even tried manually download and installing from the ubuntu deb repo, but then it breaks because libc6 is not version >= 2.34 but when I try to update libc6, it says 2.32 is the latest......................

**Comment by st3fus** [comment]
sudo apt-get install webhook is still not working, says: Unable to locate package webhook

And go build github.com/adnanh/webhook says: go.mod file not found in current directory or any parent directory; see 'go help modules'

Any solutions?

**Comment by st3fus** [comment]
Kudos to this fella, much appreciated

https://github.com/adnanh/webhook/issues/222#issuecomment-570794237

**Comment by st3fus** [comment]
So, made some changes to my webhook.service and copied the new changed file over since I had to switch to secure, since I got a domain for that app.

![image](https://user-images.githubusercontent.com/112018215/216618605-f91345ca-e533-462f-ad0b-c4771764c570.png)
This is the current issue, nothing seems to help to make it active. Any solutions?

**Comment by adnanh** [comment]
Seems like it's trying to open some file in `/home/ubuntu/datadrill-i...` but it's cut out by the screenshot. Maybe a file permission issue?

**Comment by st3fus** [comment]
> Seems like it's trying to open some file in `/home/ubuntu/datadrill-i...` (it's cut out by the screenshot). Maybe a file permission issue?

All good, I've fixed it. Yeah, it was opening the wrong files for certificates, I forgot to change folders, my bad totally. Thanks a lot!
