### ISSUE TITLE
Handling OPTIONS preflight requests

### ISSUE THREAD

**Issue by smileart** [adnanh/webhook#617]
Not an issue, but perhaps a question: having this config (see below) I'm trying to trigger a hook from the browser (using `fetch`), but before sending POST request it sends a standard preflight OPTIONS request and surely, it fails cause if I specify `"http-methods": ["POST", "OPTIONS"]` it triggers the script without parameters and with `"http-methods": ["POST"]` it responds with 404. 

One workaround would be to have the script echo OK when there's no ARGV (and that's what I'm doing now), but it'd be nice to have multiple handlers with the same `id`, but different `http-methods` to handle them separately, i.e. responding to OPTIONS straight away, without triggering the script, or having GET and POST on the same endpoint / id. Is there any recommended way to achieve this? Did I miss something in the docs?

Thank you!

````json
[
  {
    "id": "script",
    "execute-command": "script.sh",
    "command-working-directory": "/Users/blah-blah/hooks",
    "include-command-output-in-response": true,
    "http-methods": ["POST"]
    "response-headers": [
      {
        "name": "Access-Control-Allow-Origin",
        "value": "*"
      }
    ],
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "some_param"
      },
    ]
  }
]
````

**Comment by adnanh** [comment]
Sorry for the late reply, life's been pretty busy :)

We've had many discussions about multiple hooks with the same id, and we've settled not to have them in order to keep  project simplicity. 

Proposed "workaround" is exactly what you are doing, having a wrapper script that figures what to do, based on the input. In that regard, it could feel a bit cleaner if you passed the `{ "source": "request", "name": "method" }` as an argument to the wrapper command, and have the handling procedure based on that instead of the empty ARGV.

Hope that helps a little bit!

**Comment by serge-bedzhyk** [comment]
Got it. No prob. Thank you for your reply.

**Comment by smileart** [comment]
Got it. No prob. Thank you for your reply.

**Comment by drmdshahid** [comment]
Other way around is to use nginx reverse proxy to filter out options request, for eg.:

```
location /hooks/ {
    # 1. Handle browser pre-flight checks natively at the proxy level
    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
    }

    # 2. Add headers for standard execution states
    add_header 'Access-Control-Allow-Origin' '*' always;
    
    # 3. Pass clean traffic to the Go app
    proxy_pass http://ip:port;
}
```

This worked for me without adding http-methods or response-headers in hooks.json; nor changing the script to handle requests/payload.
