### ISSUE TITLE
SEO issue with this wonderful tool???

### ISSUE THREAD

**Issue by legitYosal** [adnanh/webhook#618]
Yep thats very troubling, when ever trying to search any thing related to this project we are bombarded with unrelated links, actually it is impossible to search any thing on this project, any hopes on fixing this maybe by changing the name of this repository?

**Comment by adnanh** [comment]
Thank you for your feedback! Unfortunately, I won't change the name of the repository, but we should definitely look into improving the docs and building a better knowledge-base so that you don't have to search for things on Google :)
