### ISSUE TITLE
is the docker image still supported?

### ISSUE THREAD

**Issue by pgrm** [adnanh/webhook#63]
Hi, I've found https://hub.docker.com/r/adnanh/webhook/ and wanted to use it, to build my own container which would respond to web hooks. However I saw that in beginning of November after at first adding a description about the image, it got removed again few days later.

May I ask why the docker documentation got removed again?

**Comment by adnanh** [comment]
We did not want to maintain the Dockerfile in this repository (see #50), so it got moved into [webhook-contrib](https://github.com/adnanh/webhook-contrib/tree/master/docker) repository.

**Comment by pgrm** [comment]
@adnanh thx for the clarification. than the first question still stays, according to https://hub.docker.com/r/adnanh/webhook/builds/ there hasn't been a successful build since beginning of November. As far as I see it, this is also the docker image referenced from the https://github.com/adnanh/webhook-contrib/issues repository. Is there maybe another image which I didn't find?

and secondly - maybe the link to the discussion could be mentioned in the readme, as it was suggested?

thx

**Comment by adnanh** [comment]
The Dockerfile in webhook-contrib repository should serve as a guide on how to make your own image.

I am going to include a link to this discussion for the others interested in running webhook inside a container in the README.md in this repository.

I will also remove docker image from docker hub, as it's not maintained anymore, and it's now misleading users.

**Comment by pgrm** [comment]
this clarifies everything, thx

**Comment by adnanh** [comment]
Now there is a good dockerized version of webhook at https://github.com/almir/docker-webhook

**Comment by lookingcloudy** [comment]
Pretty cool utility.   I couldn't get this to run properly in a docker container.  Webhooks itself runs fine, but can't get the build script on the host computer to run properly due to paths, access to resources that aren't mapped to the container, etc.

**Comment by kachkaev** [comment]
Same problem as @lookingcloudy reports. Just asked @almir how to control host dockers from a dockerised `webhook` instance: https://github.com/almir/docker-webhook/issues/2. If anyone else knows the answer, will be great if you share!

**Comment by LWlook** [comment]
If somebody is searching for a working image. I made an image on dockerhub based on [almir/docker-webhook](https://github.com/almir/docker-webhook/) and the official docker image, to control docker containers of the host from inside this container.
More information on [lwlook/webhook](https://hub.docker.com/r/lwlook/webhook)

**Comment by adnanh** [comment]
> If somebody is searching for a working image. I made an image on dockerhub based on [almir/docker-webhook](https://github.com/almir/docker-webhook/) and the official docker image, to control docker containers of the host from inside this container. More information on [lwlook/webhook](https://hub.docker.com/r/lwlook/webhook)

I can add it to README.md if you want?

**Comment by LWlook** [comment]
Yes, would be nice. Probably this will help somebody someday.

**Comment by regisin** [comment]
@LWlook could you potentially give an example of how controlling the other containers would work? That's exactly what I'm looking for, but I can't figure it out.

**Comment by LWlook** [comment]
@regisin I just deployed the container like in the "Running the container"-Section described. Then i made an script with for example "docker compose up -d". But you can call in the script every docker command and it will be called on the host.

**Comment by regisin** [comment]
I must be missing something. When the hook is triggered and it runs `docker compose up -d` it says `no configuration file provided: not found`.

Could you provide the functioning `hooks.json`, `docker-compose.yaml`, and `redeploy.sh` files?

**Comment by LWlook** [comment]
You have to make the docker-compose.yaml accessible in the container (eg mount a volume with the docker-compose file). If the docker-compose is not in the working dir, than you have to cd to that dir, or specify the location (docker compose -f /path/in/container/to/dockerfile.yaml up -d)

Check if the neccessary files are accessible IN the container and on the correct location (eg the scripts are in /opt/scripts).

**Comment by HADB** [comment]
It's already 2024. Shouldn't docker be officially supported?

**Comment by spacecitycoog** [comment]
2026 --- any docker support coming?
