### ISSUE TITLE
Retrieving the webhook id from the header

### ISSUE THREAD

**Issue by alexwesemann** [adnanh/webhook#642]
Gents!

First of all, great work. The solution I am building is working quite well (getting an iot payload into a MySQL database). However, I would like to use the identifier of each received webhook as a unique key value. How can I retrieve this value?
My hooks.json looks like this:
![image](https://github.com/adnanh/webhook/assets/74415724/ebd6c376-2bd4-4f66-8aa3-230ae99e5769)

I am looking for this value (which is unique for each delivered item):
![image](https://github.com/adnanh/webhook/assets/74415724/ddd224a8-0a84-42c7-b95a-74da81853b15)

Is there an additional line I have to add to the hooks.json?

Hope to hear from you soon.
KR
Alex

**Comment by moorereason** [comment]
That GUID has to be in the HTTP request somewhere in order for webhook to use it.

**Comment by alexwesemann** [comment]
Yeah I understand, but just cannot find it. My header looks like this:

1  {
2    "Accept": "text/plain, application/json, application/*+json, */*",
3    "User-Agent": "Apache-HttpClient/4.5.13 (Java/17.0.2)",
4    "Content-Type": "application/json",
5    "Content-Length": "326",
6    "Accept-Encoding": "gzip,deflate",
7    "Things-Plug-Uuid": "fbaeaf5d-1634-4fab-96a0-1c74c4294556",
8    "Things-Message-Token": "82495b58556093855f6a485c3609e7e972fbfc2306b995f5b5344058f60ac679",
9    "Things-Device-Barcode": "NULL"
10 }

Just don't know where to find it. Any ideas?

**Comment by alexwesemann** [comment]
And no, it's not the "Things-Plug-Uuid" as that is generated through the remote iot device itself.

**Comment by moorereason** [comment]
webhook can only work with what is sent to it by the remote system. If it's not in the URL parameters, headers, or body, then it's inaccessible.

**Comment by alexwesemann** [comment]
Ok, thanks! I will generate a random uuid in python which then will be used as unique id in the database. Should work out fine.
