### ISSUE TITLE
Collapse Parameter into MatchRule

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#65]
### Proposal

Collapse the `Parameter` fields into the `MatchRule` struct:

``` go
type MatchRule struct {
    Regex     string   `json:"regex,omitempty"`
    Secret    string   `json:"secret,omitempty"`
    Source    string   `json:"source,omitempty"` // Parameter.Source
    Subject   string   `json:"name,omitempty"`   // Parameter.Name
    Type      string   `json:"type,omitempty"`
    Value     string   `json:"value,omitempty"`
}
```

Which would give us a simplified `match` definition:

``` json
"match":
{
  "type": "value",
  "source": "payload",
  "subject": "ref",
  "value": "refs/heads/master"
}
```
### Backward Compatibility

It should be possible to leave the `MatchRule.Parameter` field in place for backward compatibility.  We can just copy `Parameter.Source` and `Parameter.Name` into their `MatchRule` counterparts.  We would declare `Parameter` as deprecated in the documentation and remove it at some later date.
### The Argument Type

We would keep the `Argument` type for use with `pass-arguments-to-command`, etc.

**Comment by adnanh** [comment]
:+1:
