### ISSUE TITLE
Deprecate Regex field

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#66]
### Proposal

Deprecate the `MatchRule.Regex` field in favor of using `MatchRule.Value`.

``` json
{
  "match":
  {
    "type": "regex",
    "value": ".*",
    "parameter":
    {
      "source": "payload",
      "name": "ref"
    }
  }
}
```

I can't think of a good reason to keep `Regex` around as a stand-alone `string` field when the `Value` field can serve the same purpose.
### Backward Compatibility

Keep `MatchRule.Regex` around for a time and simply copy it's value into `MatchRule.Value`.

**Comment by adnanh** [comment]
:+1:
