### ISSUE TITLE
webhook hook not running bash script

### ISSUE THREAD

**Issue by ArrnaudMoreau22** [adnanh/webhook#661]
I have a webhook setup in my VPS. webhook running and loading the hook.json.

Here is the hook with the bare minimum to debug : 
`[
  {
    "id": "deploy-webhook",
    "execute-command": "/home/arnaud/update.sh",
    "command-working-directory": "/home/arnaud",
    "response-message": "Script deploy-webhook lancé avec succès."
  }
]
`

and i can't manage to make it run the update.sh file. 
`
#!/bin/bash
LOG_FILE="/home/arnaud/update.log"
echo "------- $(date) -------" >> $LOG_FILE
echo "Début du script de mise à jour" >> $LOG_FILE

echo "Déplacement dans le répertoire du projet" >> $LOG_FILE
cd /home/arnaud/timemanager/T-POO-700-PAR_3 && echo "Dans le répertoire $(pwd)" >> $LOG_FILE

echo "Tentative de pull depuis Git" >> $LOG_FILE
git pull origin main >> $LOG_FILE 2>&1

echo "Arrêt des conteneurs Docker existants" >> $LOG_FILE
docker compose down >> $LOG_FILE 2>&1

echo "Reconstruction et démarrage des conteneurs Docker" >> $LOG_FILE
docker compose up --build -d >> $LOG_FILE 2>&1
echo "Script de mise à jour terminé" >> $LOG_FILE
`
There is no log meaning it doesn't run.
My webhook service says it's running, it loaded the hook.json correctly and see's the github webhook and send à 200 ok status back to github. But it doesn't execute here the hook or the update.sh.

I can run the update.sh manually correctly.  
I don't understand what i am missing here

**Comment by moorereason** [comment]
My guess is that it's a permission issue. How are you running the webhook service? Are you sure it has permission to your home directory?

**Comment by ArrnaudMoreau22** [comment]
here is how it looks like : 
cat /etc/systemd/system/webhook.service
[Unit]
Description=GitHub Webhook

[Service]
Type=simple
User=arnaud
Group=arnaud
ExecStart=/usr/bin/webhook -hooks /home/arnaud/hooks.json -verbose -port 9000
Restart=on-failure

[Install]
WantedBy=multi-user.target


and groups arnaud : arnaud : arnaud sudo users docker

**Comment by ArrnaudMoreau22** [comment]
> My guess is that it's a permission issue. How are you running the webhook service? Are you sure it has permission to your home directory?
here is how it looks like :
cat /etc/systemd/system/webhook.service
[Unit]
Description=GitHub Webhook

[Service]
Type=simple
User=arnaud
Group=arnaud
ExecStart=/usr/bin/webhook -hooks /home/arnaud/hooks.json -verbose -port 9000
Restart=on-failure

[Install]
WantedBy=multi-user.target

and groups arnaud : arnaud : arnaud sudo users docker

**Comment by moorereason** [comment]
And what do the systemd logs look like for webhook when you try it?

**Comment by ArrnaudMoreau22** [comment]
> And what do the systemd logs look like for webhook when you try it?

#After restart of the service and before sending the hook from github

Oct 28 12:00:56 vps-bdf8b891 systemd[1]: Stopped webhook.service - GitHub Webhook.
Oct 28 12:00:56 vps-bdf8b891 systemd[1]: Started webhook.service - GitHub Webhook.
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 version 2.8.0 starting
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 setting up os signal watcher
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 attempting to load hooks from /home/arnaud/hooks.json
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 found 1 hook(s) in file
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56         loaded: deploy-webhook
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 serving hooks on http://0.0.0.0:9000/hooks/{id}
Oct 28 12:00:56 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:00:56 os signal watcher ready


#After sending the hook i have this extra line
Oct 28 12:03:10 vps-bdf8b891 webhook[2369]: [webhook] 2023/10/28 12:03:10 [402f5b] 200 | 2 B | 341.903µs | 91.134.88.54:9000 | POST /

**Comment by ArrnaudMoreau22** [comment]
> And what do the systemd logs look like for webhook when you try it?

Thanks for making me pay extra attention to this. So my error was on the url to trigger the hook, 
i was sending the webhook to : http://my-ip:9000 instead of http://my-ip:9000/hooks/deploy-webhook
