### ISSUE TITLE
Specify Response headers?

### ISSUE THREAD

**Issue by childoftv** [adnanh/webhook#67]
Specifically it would be useful to specify: Access-Control-Allow-Origin in the response so that the hook could be called from js served from a different location or port.

**Comment by adnanh** [comment]
It would be a nice feature, I agree.

As a current workaround, you could put webhook behind an nginx instance and have the nginx proxy_pass requests to webhook, whilst adding those headers back in the response.

**Comment by adnanh** [comment]
Implemented on development branch.

**Comment by adnanh** [comment]
Released this as 2.3.8.

**Comment by childoftv** [comment]
👍
