### ISSUE TITLE
how to set  shell $PATH

### ISSUE THREAD

**Issue by qhyuTT** [adnanh/webhook#672]
my shell code:
export PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/jdk1.8.0_201/bin:/home/swcares/.local/bin:/home/swcares/bin:/usr/local/jdk1.8.0_201/bin

hooks.yaml:
- id: redeploy-screen
  execute-command: "reploy-screen.sh"
  command-workingrectory: "/opt/app"
  pass-arguments-to-command:
  - source: string
    name: screen-task.jar
  - source: string
    name:  restart

and webhook response: 
error in exec: "reploy-screen.sh": executable file not found in $PATH

**Comment by para-do-x** [comment]
Hi qhyuTT, 

did you tried:
execute-command: "/opt/app/reploy-screen.sh"

That's the way I run my scripts over webhook. 

Br,

para-do-x

**Comment by adnanh** [comment]
Also, you seem to have a typo in `command-working-directory`

**Comment by qhyuTT** [comment]
> Also, you seem to have a typo in `command-working-directory`



> Hi qhyuTT,
> 
> did you tried: execute-command: "/opt/app/reploy-screen.sh"
> 
> That's the way I run my scripts over webhook.
> 
> Br,
> 
> para-do-x

**Comment by qhyuTT** [comment]
> Hi qhyuTT,
> 
> did you tried: execute-command: "/opt/app/reploy-screen.sh"
> 
> That's the way I run my scripts over webhook.
> 
> Br,
> 
> para-do-x

yeah，change my execute-command to /opt/app/reploy-screen.sh can running shell。thank you

**Comment by qhyuTT** [comment]
> Also, you seem to have a typo in `command-working-directory`

yes，thank you，i solved my question
