### ISSUE TITLE
Add a (unique) folder with images for dynamic responses

### ISSUE THREAD

**Issue by actuariat** [adnanh/webhook#676]
The solution here [base64](https://github.com/adnanh/webhook/issues/136) doesn't solve the issue, even though elegant for one image.

The image changes before every request so we need a way to post the new image as a response. 

This way you complete the web hook solution: the image can be a plot of the requests or similar.

**Comment by moorereason** [comment]
Please better explain your scenario and use case.  I bet you can solve this within the `execute_command` script when `include-command-output-in-response` is true.

**Comment by actuariat** [comment]
OK, let's kepp it simple—  every 5 minutes a new complicated image it is generated on the server, output.jpg

I need the webhook to display the latest image generated on the server, using webhook. 

This is the setting:

{
    "id": "itst",
    "include-command-output-in-response": true,
    "response-headers": [
      {
        "name": "Content-Type",
        "value": "text/html"
      }
    ],
    "execute-command": "echo",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "<meta http-equiv='Content-type' content='text/html; charset=utf-8'/><html style='height: 100%;'><head><title>test</title></head><body style='margin: 0px; height: 100%'><img style='-webkit-user-select:none; display:block; margin:auto; padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);' **src=output.jpg**''></body></html>"
      }
    ]
  }

**Comment by moorereason** [comment]
Assuming a Linux host, try something like this:

```json
{
    "id": "itst",
    "include-command-output-in-response": true,
    "response-headers": [
      {
        "name": "Content-Type",
        "value": "text/html"
      }
    ],
    "execute-command": "/path/to/showpage.sh",
    "pass-arguments-to-command": [
      {
        "source": "string",
        "name": "/path/to/output.jpg"
      }
    ]
}
```

showpage.sh:
```bash
#!/usr/bin/bash
echo -n '<**meta1** http-equiv="Content-type" content="text/html; charset=utf-8"/><html style="height: 100%;"><head><title>test</title></head><body style="margin: 0px; height: 100%"><img style="-webkit-user-select:none; display:block; margin:auto; padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);" **src="data:/image/jpeg,'
base64 -w 0 $1
echo '**"></body></html>'
```

**Comment by actuariat** [comment]
Thank you, I fix it like this, it works now:

`#!/usr/bin/bash
echo -n '<meta http-equiv="Content-type" content="text/html; charset=utf-8"/><html style="height: 100%;"><head><title>test</title></head><body style="margin: 0px; height: 100%"><img style="-webkit-user-select:none; display:block; margin:auto; padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);" src="data:image/jpeg;base64,'
base64 -w 0 $1
echo '"></body></html>'`

Not particularly elegant; it clutters the logs by logging every single image in its entirety.

**Comment by moorereason** [comment]
> Not particularly elegant; it clutters the logs by logging every single image in its entirety.

Where is this being logged?  Unless you're running `webhook` with debug enabled, it should not log the response body.  Please explain.

**Comment by actuariat** [comment]
I run it like this:

webhook -hooks wb.json -hotreload -logfile  webhook.out -port 80&

I think anyone should run it like this. It is one of your strong points—at least for me was the deciding factor. 

Maybe we should work on: **command output**, not to display the entire script.

**Comment by moorereason** [comment]
@actuariat,
I'm glad this issue is resolved for you.

I've opened a separate issue about adding the ability to control command output logging.
