### ISSUE TITLE
Build servers with no public static ip

### ISSUE THREAD

**Issue by joeblew99** [adnanh/webhook#68]
I have a build server in the office that is not publically addressable.
To make it receive bitbucket web hooks I can use ngrok.
Does this sound like a good idea for your project ?

**Comment by joeblew99** [comment]
I am not sure if this project allows publishing web hooks or just consuming them :)

**Comment by adnanh** [comment]
Sure, you can set up webhook to serve the hooks on your build machine, and then use (ngrok)[https://ngrok.com/docs#expose] to expose the webhook outside :-)

**Comment by moorereason** [comment]
To be clear, this project consumes webhooks.

**Comment by joeblew99** [comment]
Thanks. That clears it up for me.
I will try out mating it with ngrok. Should work
