### ISSUE TITLE
How to properly display output in desired format to telegram?

### ISSUE THREAD

**Issue by H4nT0x111** [adnanh/webhook#686]
Hi, I'm trying to push an alert from an external system => webhook server => telegram. But now I'm having the following problem:
The output information is not as I expected, specifically this is `webhook.json`
![2024-05-07_15h49_03](https://github.com/adnanh/webhook/assets/135039924/b3b1b18d-96f8-4af8-a070-fe9d16982116)
`webhook-endpoint.sh`
![2024-05-07_15h50_39](https://github.com/adnanh/webhook/assets/135039924/44467fba-b3c3-4cff-81e4-64fec252988a)
I tried to test with Postman, this is `request body`
![2024-05-07_15h52_08](https://github.com/adnanh/webhook/assets/135039924/43645c0b-a4af-4605-8044-27d8844bb0de)
and the result on Telegram app
![image](https://github.com/adnanh/webhook/assets/135039924/5dc56ca7-2b6d-49b4-972a-7d3fd79c3350)
As you can see, the output content displays the {"text":......} part but I only want to display the body of that response (just the value of the key text). When I try with just plain text, it shows the error `error parsing body payload due to unsupported content type header: text/plain` and the output on telegram only shows `null` like this.
![image](https://github.com/adnanh/webhook/assets/135039924/023014a1-acbf-4d9e-bd7f-56b0febd71ca)
Do you have any way to resolve this problem? Please help me to fix it. Thanks

**Comment by adnanh** [comment]
If you want to pass the "text" property from the payload object, you need to specify it like this:
```
"pass-arguments-to-command": [ {"source": "payload", "name": "text" } ]
```
