### ISSUE TITLE
Feature Request: Allow using env vars in conf file (for secrets)

### ISSUE THREAD

**Issue by sisrael-dn** [adnanh/webhook#698]
Hi,

Is there any chance for reading parts of conf from existing env vars? 
 I would like to avoid putting secrets in conf file for obvious security reasons.
For, instead  this rule in conf file
```
{
  "match":
  {
    "type": "value",
    "secret": "yoursecret",
    "parameter":
    {
      "source": "header",
      "name": "X-Toen"
    }
  }
}
```
I'd like be able to do something like this:
```
{
  "match":
  {
    "type": "value",
    "secret": "$MY_SECRET_ENV_VAR",
    "parameter":
    {
      "source": "header",
      "name": "X-Token"
    }
  }
}
```

And on startup the webhook up would load  `MY_SECRET_ENV_VAR` from env and use it

Thanks,
Shay

**Comment by moorereason** [comment]
Yes, see the `getenv` function in the [Templates documentation](https://github.com/adnanh/webhook/blob/master/docs/Templates.md).

**Comment by sisrael-dn** [comment]
@moorereason Thank you for pointing me to the right doc!
