### ISSUE TITLE
Posts as x-www-form-urlencoded don't work

### ISSUE THREAD

**Issue by moorereason** [adnanh/webhook#7]
First off, thanks for publishing this project.  It looks promising.

I ran into an issue trying to receive a POST hook from Bitbucket.  Bitbucket sends a x-www-form-urlencoded POST with the JSON content in the ``payload`` form variable -- they don't send the JSON payload in the body.  I was able to modify ``hookHandler()`` to decode the JSON, but I had to hardcode the ``payload`` map index:

```go
} else if contentType == "application/x-www-form-urlencoded" {
    fd, err := url.ParseQuery(string(body))
    if err != nil {
        log.Printf("error parsing form payload %+v\n", err)
    } else {
        fv := helpers.ValuesToMap(fd)
        decoder := json.NewDecoder(strings.NewReader(fv["payload"].(string)))
        decoder.UseNumber()
        err := decoder.Decode(&payload)
        if err != nil {
            log.Printf("error parsing JSON payload %+v\n", err)
        }
    }
}
```

With that change, I'm able to match simple paths (``canon_url`` and ``repository.absolute_url``), but I'm unable to match ``commits.0.branch``.  I've yet to look into why.

I'm testing webhook with curl and sending [Bitbucket's sample payload](https://confluence.atlassian.com/display/BITBUCKET/POST+hook+management).  Here's a simplified version of what I'm doing:

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
  -d 'payload={"canon_url": "https://bitbucket.org"}' \
  http://localhost:9000/hooks/example
```

I wanted to see if you can duplicate the form decoding problem.  I also wanted to see what you think about adding another option to the hook definition format.  I'm thinking something like ``form-variable`` would work.  I would set that to ``payload``, and webhook would know to access that form variable to find the JSON payload.

**Comment by adnanh** [comment]
Thanks for the write up! I'll take a look into this as soon as possible and will post you with an update and a solution... :-)

**Comment by adnanh** [comment]
I'm thinking about adding a property on the hook named `json-parameters` which would contain a list of parameters that the user expects to contain JSON strings. Upon receiving the request, webhook would then try to parse those values as JSON and the user could use them just like the parameters in JSON formatted payload. (`parameter.key.anotherkey`). Solving the issue you currently have... What do you think?

**Comment by moorereason** [comment]
So as an example, I could define ``"json-parameters": [ "mypayload" ]`` in hooks.json, and webhook would decode the ``mypayload`` form variable as JSON.  Then I would reference the JSON items like this:

```json
{
  "match": {
    "type": "value",
    "parameters": {
      "source": "payload",
      "name": "mypayload.commits.0.branch"
    },
    "value": "needle"
  }
}
```
I like the idea.

However, ``json-parameters`` sounds a little ambiguous to me.  It might confuse people into thinking it has something to do with the ``match.parameter`` triggers from the hook package.  What about ``http-json-parameters``?  But either way, you make the call.  It'll be great.  :smile:

**Comment by adnanh** [comment]
Exactly that. Maybe `parse-parameters-value-as-json`? :-)

**Comment by adnanh** [comment]
I'll get this done tonight.

**Comment by moorereason** [comment]
Success!!

**Comment by adnanh** [comment]
Awesome! :-)
