### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by DarkDrim** [adnanh/webhook#70]
Error "parsing JSON: couldn't retrieve argument for {Source:payload Name:payload}" work with BitBucket.
before everything was good
whats wrong?

Thanks

**Comment by moorereason** [comment]
Can you provide more information?  It sounds like it was working and then just stopped working.  ?  Did you update webhook?  What version of webhook are you running?

**Comment by adnanh** [comment]
What payload is bitbucket sending? What is the configuration of your hook in hooks.json file?

**Comment by DarkDrim** [comment]
Thanks for your answers.
hooks.json:
`
[
  {
    "id": "redep-it-hook",
    "execute-command": "/home/it/ho/redeploy.sh",
    "command-working-directory": "/home/it/ho",
    "parse-parameters-as-json":
    [
      {
        "source": "payload",
        "name": "payload"
      }
    ],
    "pass-arguments-to-command":
    [
      {
        "source": "string",
        "name": "123"
      },
      {
        "source": "payload",
        "name": "payload.commits.0.author"
      }
    ]
  }
]
`

BitBucket send request on push to repo.
It happened after the server is not working day. Then I re-launched webhook.

Start webhook: `nohup ./webhook -hooks hooks.json -verbose -port 9000`

**Comment by DarkDrim** [comment]
Today I downloaded the latest version of webhook again, all the same.

**Comment by adnanh** [comment]
can you try removing `"parse-parameters-as-json": [ { "source": "payload", "name": "payload" } ]` from the `hooks.json` and then restart webhook?

**Comment by DarkDrim** [comment]
I do the same, the exact same error.
Even if I just send your inquiry to:
curl -X POST http://192.168.1.229:9000

**Comment by adnanh** [comment]
Can you copy the exact output of the command: `curl -v -X POST http://192.168.1.229:9000`

**Comment by adnanh** [comment]
Turns out the Bitbucket has updated the event payloads. Try replacing `{ "source": "payload", "name": "payload.commits.0.author" }` with `{ "source": "payload", "name": "actor.username" }`

**Comment by DarkDrim** [comment]
`* Rebuilt URL to: http://192.168.1.229:9000/
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.229...
* Connected to 192.168.1.229 (192.168.1.229) port 9000 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.1.229:9000
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 13 Apr 2016 09:53:53 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 192.168.1.229 left intact
`

Replaced payload, yet all the same

**Comment by adnanh** [comment]
Sorry, try hitting the actual hook: `curl -v -X POST http://192.168.1.229:9000/hooks/redep-it-hook`

**Comment by DarkDrim** [comment]
`
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.229...
* Connected to 192.168.1.229 (192.168.1.229) port 9000 (#0)
> POST /hooks/redep-it-hook HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.1.229:9000
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 13 Apr 2016 10:00:04 GMT
< Content-Length: 80
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 192.168.1.229 left intact
error parsing JSON: couldn't retrieve argument for {Source:payload Name:payload}
`

**Comment by DarkDrim** [comment]
In hooks.json:
`
[
  {
    "id": "redep-it-hook",
    "execute-command": "/home/it/ho/redeploy.sh",
    "command-working-directory": "/home/it/ho"
  }
]
`

**Comment by adnanh** [comment]
Are you sure you restarted webhook?

**Comment by DarkDrim** [comment]
Yes. Now he says that the team is running, but the command fails for some reason.
[webhook] 2016/04/13 06:58:41 command output:
[webhook] 2016/04/13 06:58:41 finished handling redep-it-hook

Script:
`
#!/bin/bash
cd /saveren
echo Started...
git checkout master && git pull
git checkout dev && git pull
git checkout prod && git pullt
branch=$(git for-each-ref --count=1 --sort='-committerdate' --format='%(refname:short)' refs/heads)
echo Current branch is: $branch
git checkout $branch

if [ "dev" == "$branch" ]; then
        cd /saveren/fe
        rm -rf static-dev
        mkdir static-dev
        cp data/dev/. static-dev/ -R
fi

if [ "prod" == "$branch" ]; then
        cd /saveren/fe
        rm -rf static-prod
        mkdir static-prod
        cp data/prod/. static-prod/ -R
fi

echo Restarting servers...
cd /saveren/fe && sh fe-dev-restart.sh && sh fe-prod-restart.sh
cd /saveren/be && sh be-restart.sh
`

**Comment by DarkDrim** [comment]
Problem with:
 "parse-parameters-as-json":
    [
      {
        "source": "payload",
        "name": "payload"
      }
    ]
(BitBucket)

**Comment by adnanh** [comment]
Yes, I asked you to remove that from your `hooks.json` file. Did it work after that?

**Comment by DarkDrim** [comment]
Yes, after remove and restart webhook

**Comment by adnanh** [comment]
Awesome. :-)

**Comment by moorereason** [comment]
Can we add this sample config to the wiki?

**Comment by adnanh** [comment]
I guess the original example is now outdated, so we should update it. Do you mind doing it?

**Comment by moorereason** [comment]
Wiki updated.
