### ISSUE TITLE
Enable loading multiple JSON files

### ISSUE THREAD

**Issue by almir** [adnanh/webhook#72]
It would be useful if multiple JSON files containing hooks could be loaded instead of one huge file.
A huge file is difficult to maintain and difficult to read.

This functionality can be implemented either by modifying the `-hooks` switch to accept array instead of string, or by specifying `-hooks` parameter multiple times (preferred way), for example:

``` shell
webhook -verbose -hooks 1sthooksfile.json -hooks 2ndhooksfile.json -hooks 3rdhooksfile.json -hotreload
```

**Comment by xlr-8** [comment]
Another enhancement could be to load from a directory ```-hooks_dir```, and an other one could be to support both Json & Yaml
