### ISSUE TITLE
Attach webhook builds to github releases

### ISSUE THREAD

**Issue by dgellow** [adnanh/webhook#73]
Hello,

Could you add webhook builds to your github releases? 
You can use tools like [gox](https://github.com/mitchellh/gox) to create builds for multiple platforms without too much hassle (in theory).

**Comment by josegonzalez** [comment]
Note: [gh-release](https://github.com/progrium/gh-release) may be useful for uploading packages automatically :)

**Comment by adnanh** [comment]
:+1: will do.
