### ISSUE TITLE
Multiple hooks ID not executed properly

### ISSUE THREAD

**Issue by xlr-8** [adnanh/webhook#76]
Cool work, thanks a lot!

**Description of problem:**
I'm currently testing webhook, and I found out, that you can't have multiple hooks triggered with one name. Theoretically you can, but in practice you can't, I'm still learning go, so please correct me, if there is something I did not get.

In your webhook.go code we can see this loop: https://github.com/adnanh/webhook/blob/master/webhook.go#L190-L242
Snippets:
```golang
if err != nil {
        msg := fmt.Sprintf("error parsing JSON: %s", err)
        log.Printf(msg)
        w.WriteHeader(http.StatusBadRequest)
        fmt.Fprintf(w, msg)
        return
}
```

```golang
if err != nil {
        msg := fmt.Sprintf("error evaluating hook: %s", err)
        log.Printf(msg)
        w.WriteHeader(http.StatusInternalServerError)
        fmt.Fprintf(w, msg)
        return
}
```

```golang
if ok {
        log.Printf("%s hook triggered successfully\n", h.ID)

        for _, responseHeader := range h.ResponseHeaders {
                w.Header().Set(responseHeader.Name, responseHeader.Value)
        }   

        if h.CaptureCommandOutput {
                response := handleHook(h, &headers, &query, &payload, &body)
                fmt.Fprintf(w, response)
        } else {
                go handleHook(h, &headers, &query, &payload, &body)
                fmt.Fprintf(w, h.ResponseMessage)
        }   

        return
}
```

Which has many return that break the for loop (whether it succeeded or not), I would suggest to have a less restrictive behaviour with ```continue``` and log an error message at the end if really nothing executed.

**How reproducible:**
Always

**Steps to reproduce:**
1. Create hooks.json with different hooks and 2 with the same name, but different command/arg
2. Rerun webhook if not hotreload
3. Do action to trigger the hook
4. Observe the logs

ex of hooks.json file used (I also varied the orders of hooks, just in case):
```bash
> cat hooks.json
[
  {
    "id": "webhook2",
    "execute-command": "/tmp/script2.sh",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "head_commit.id"
      },
      {
        "source": "payload",
        "name": "head_commit.author.name"
      },
      {
        "source": "payload",
        "name": "head_commit.author.email"
      }
    ]
  },
  {
    "id": "webhook",
    "execute-command": "/tmp/script3.sh",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "head_commit.id"
      },
      {
        "source": "payload",
        "name": "head_commit.author.name"
      },
      {
        "source": "payload",
        "name": "head_commit.author.email"
      }
    ]
  },
  {
    "id": "webhook",
    "execute-command": "/tmp/script1.sh",
    "pass-arguments-to-command":
    [
      {
        "source": "payload",
        "name": "head_commit.id"
      },
      {
        "source": "payload",
        "name": "head_commit.author.name"
      },
      {
        "source": "payload",
        "name": "head_commit.author.email"
      }
    ]
  }
]
```

Testing scripts look like this (just to know what is called with which arguments):
```bash
> tail -n +1 /tmp/script*
==> /tmp/script1.sh <==
#!/bin/bash

echo $0
echo $@

==> /tmp/script2.sh <==
#!/bin/bash

echo $0
echo $@

==> /tmp/script3.sh <==
#!/bin/bash

echo $0
echo $@
```

**Expected results:**
To have all matching hooks executed, because I don't want the execution to be stopped. Whether it ran fine or not (if typo in one, if service unavailable, if you just want multiple tasks run, etc).

**Additional info**:
Attached is a first draft of a patch suggested.
[fix-return.patch.txt](https://github.com/adnanh/webhook/files/306536/fix-return.patch.txt)

**Comment by adnanh** [comment]
Correct, this is indeed an issue and not an expected behavior. Could you please create a PR into the development branch with proposed fixes?

Thanks!

**Comment by xlr-8** [comment]
Sure, working on it.
