### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by vincentserpoul** [adnanh/webhook#77]
Hi,

first time user, maybe it's a conf issue, maybe a hook issue.
I tried both the docker and compile from source.

`deploy/webhook -hooks ./deploy/deployhook.json  -verbose`

`[webhook] 2016/06/09 09:27:33 version 2.3.8 starting`
`[webhook] 2016/06/09 09:27:33 setting up os signal watcher`
`[webhook] 2016/06/09 09:27:33 attempting to load hooks from ./deploy/deployhook.json`
`[webhook] 2016/06/09 09:27:33 os signal watcher ready`
`[webhook] 2016/06/09 09:27:33 loaded 1 hook(s) from file`
`[webhook] 2016/06/09 09:27:33 	> deploy-webhook`
`[webhook] 2016/06/09 09:27:33 starting insecure (http) webhook on :9000`

after each hook is triggered, I get:

`[webhook] 2016/06/09 09:27:51 Started POST /`
`[webhook] 2016/06/09 09:27:51 Completed 404 Not Found in 141.541µs`

My config is the following:

`[`
`  {`
`    "id": "deploy-webhook",`
`    "execute-command": "/home/test/deploy/deploy.sh",`
`    "command-working-directory": "/home/test/www/"`
`  }`
`]`

Any idea what the error could be?

**Comment by xlr-8** [comment]
Hi,

It seems like your POSTing on / (cf. logs), but your webhook is 'deploy-webhook'.
You might want to try to modify your URL to match your hook name and prefix.

By default the prefix is: 'hooks' in webhook.go file:
```golang
hooksURLPrefix = flag.String("urlprefix", "hooks", "url prefix to use for served hooks (protocol://yourserver:port/PREFIX/:hook-id)")
```
So you might want to modify your hook (in github, slack or whatever), with something like:
```
http://IPADDRESS:9000/hooks/deploy-webhook
```

cheers

**Comment by vincentserpoul** [comment]
Thanks, I was sure it was something simple! Here it is.
Hopefully, it will be useful for other people in need.
