### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dAnjou** [adnanh/webhook#8]
Is there or will there be any kind of authentication?

**Comment by adnanh** [comment]
What exactly do you mean by authentication? The HTTP Basic Auth, or do you just want to verify the source of the request?

Currently the webhook providers such as Github, Bitbucket, and Slack use tokens and signatures to ensure you the payload and the requests are coming from the trusted source (only you and the webhook source know that secret).

You can use that information in combination with the trigger-rule to verify and authorize only them to trigger your script.

If you want to restrict the sources the requests are coming from, you can use firewall on the machine, and for the basic authentication you can put webhook behind the nginx instance and set up authentication on the nginx. Basically using [NGINX Basic Auth](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) and [NGINX Proxy Module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html).

**Comment by dAnjou** [comment]
That makes sense. Thanks.
