### ISSUE TITLE
Remove multiple hooks with the same id

### ISSUE THREAD

**Issue by adnanh** [adnanh/webhook#82]
All it does is add ambiguity and makes our codebase dirty.

The usefulness of the feature is questionable and can be achieved by having a single hook with a script/program that will decide what needs to be done.

**Comment by xlr-8** [comment]
Would close: https://github.com/adnanh/webhook/issues/78

**Comment by amq** [comment]
> a script/program that will decide what needs to be done

But then the whole matching logic of _webhook_ would be unused, leaving almost no added value.

The ideal way of handling this would be have a single endpoint with the ids being "virtual", meaning that the id which first matches, runs.
