### ISSUE TITLE
Configuration mistake, misconception about trigger rules or bug?

### ISSUE THREAD

**Issue by fbartels** [adnanh/webhook#83]
Hi,

just recently I noticed something, where I am not 100% sure if it has been the same all along (currently using 2.3.9).

I have  for example to following hook:
 ```
[
  {
    "id": "test",
    "execute-command": "echo",
    "trigger-rule":
    {
      "match":
      {
        "type": "payload-hash-sha1",
        "secret": "yoursecret",
        "parameter":
        {
          "source": "url",
          "name": "token"
        }
      }
    }
  }
]
```

When I now call http://my-ip:9000/hooks/test (for example through my browser) I get the following answer displayed:
```Hook rules were not satisfied.```
and simultaneously webhook will log the following:
```
[webhook] 2016/06/27 15:07:32 test got matched (1 time(s))
[webhook] 2016/06/27 15:07:32 test got matched (1 time(s)), but didn't get triggered because the trigger rules were not satisfied
[webhook] 2016/06/27 15:07:32 Completed 200 OK in 119us
```

If I now change my url to ```http://my-ip:9000/hooks/test?token=test```
I will now get the following response:
```
error evaluating hook: invalid payload signature 39b5b946e0d0144df4ea088c3e195c9118b86dd9
```

And this is basically telling me: "hey, you used the wrong secret! try this one instead!" (since the payload signature in the response is acutally the sha1 of my defined secret.

Is this a configuration mistake? or a bug?

**Comment by moorereason** [comment]
It looks like it's working as intended.  You're asking webhook to match a URL parameter that either doesn't exist or is invalid.  The command should not be triggered in either case.

**Comment by fbartels** [comment]
Yes, that was not what I meant. The hook does not execute when the wrong token is sent, but webhook also does tell you how the token should be. A not so secret secret if you will. 

In other words, you can't really use payload-hash-sha1 for authentication.

**Comment by moorereason** [comment]
@fbartels, webhook uses your secret to calculate a HMAC SHA1 of the payload.  It's not showing you the secret.  If this was unclear, maybe you can suggest an improvement to the documentation or help us to make it more clear to new users.

**Comment by fbartels** [comment]
No, but its showing you the sha1. And when you call ?token=sha1-of-token, then your call will succeed.

**Comment by moorereason** [comment]
Unless I'm mistaken, it's not showing the sha1 to the remote agent.  It's only logging it on the server side.

**Comment by adnanh** [comment]
You are correct. It leaks out the calculated SHA1 of the payload that it's expecting, this is a bug, no idea how this slipped out unnoticed!

**Comment by fbartels** [comment]
Hi Adnan,

thanks for the fix. I did a manual checkout and build of 2.4.0 and can confirm that I cannot reproduce the issue anymore.

**Comment by adnanh** [comment]
:+1: thanks for reporting:)
