### ISSUE TITLE
[security] server responds with correct payload signature in error

### ISSUE THREAD

**Issue by mullender** [adnanh/webhook#85]
If you configure:
```
"trigger-rule": {
      "match": {
        "type": "payload-hash-sha1",
        "secret": "<secret>",
        "parameter": {
          "source": "header",
          "name": "X-Hub-Signature"
        }
      }
    }
```

And you make a curl request to the server, that contains an invalid `X-Hub-Signature` (the header must be present, but invalid)
```
curl -H 'X-Hub-Signature: dummy' http://webhook-app1.foo/echo-webhook
```

Then the server will respond:
```
error evaluating hook: invalid payload signature <signature>
```

Then repeating the `curl` with the returned signature will succeed:
```
curl -H 'X-Hub-Signature: <signature>' http://webhook-app1.foo/echo-webhook
```

Although useful for debugging, it also defeats the signature verification based security.

**Comment by adnanh** [comment]
I knew I saw this earlier, #83

**Comment by moorereason** [comment]
@adnanh, you're probably right that this was fixed earlier.  I may have jumped the gun, but I still think we shouldn't disclose the expected MAC.

@mullender, what version of webhook were you using?

**Comment by mullender** [comment]
@moorereason I was running version 2.3.7
