### ISSUE TITLE
[enhancement] non-zero exit codes should result in non-200 status codes

### ISSUE THREAD

**Issue by mullender** [adnanh/webhook#88]
When the executed command exits with a non-0 exit code, the http status code should not be 200.
This would allow for simper webhook monitoring.

**Comment by kachkaev** [comment]
I agree with @mullender. This and #87 seem like crucial features in webhook usage. Otherwise CI build tools have no way of knowing if a deploy went well.

**Comment by adnanh** [comment]
Please note that this is only possible if you are using "include-command-output-in-response" flag.

Will be added in 2.5.0
