### ISSUE TITLE
Document "source": "url" (GET params)

### ISSUE THREAD

**Issue by kachkaev** [adnanh/webhook#97]
Currently this possible use case is not appearing neither in the docs nor in examples:

```json
    "trigger-rule":
    {
      "match":
      {
        "type": "value",
        "value": "123",
        "parameter":
        {
          "source": "url",
          "name": "token"
        }
      }
    }
```
I mean `"source": "url"` here. GET params are referred as `query`, which is what I have attempted to name them in the first place: `{ "source": "query", "name": "token" }`. It took a while to figure out that `url` needs to be used instead of `query` (had to read the source for that).

Would be good all accepted values for `source` were listed somewhere in `README.md` or at least used in the example.

Thanks a lot for making this tool available @adnanh!

**Comment by moorereason** [comment]
Anyone can update the wiki docs.  No PR required.

**Comment by kachkaev** [comment]
Ah, sure! Done: https://github.com/adnanh/webhook/wiki/Hook-Examples

Could you please have a look at #87 and #88?
