### ISSUE TITLE
Ability to specify environment variables that don't begin with HOOK_

### ISSUE THREAD

**Issue by wjessop** [adnanh/webhook#98]
It'd be great to be able to specify environment variables that will get set that aren't prefixed by HOOK_. The situation I just hit was needing to set HOME on a command. The underlying (puppet) libraries that were complaining about HOME not being set would have been a PITA to map HOOK_HOME to HOME in (probably requiring us to run our own forks).

**Comment by adnanh** [comment]
Agreed, the `EnvName` property should specify the full environment variable name, and it should not be prefixed by `HOOK_`. It will be fixed in `2.5.0`

**Comment by wjessop** [comment]
Perfect, thanks!
